/**
 * POST /api/tester-report
 *
 * Receives beta tester feedback from /tester hub, builds a Markdown
 * report, attaches it to an email, and sends it via Resend to the
 * product owner.
 *
 * Body: { testerName: string, feedback: Record<string, { rating, note }> }
 */

import { NextRequest, NextResponse } from "next/server";

const TO      = "bechir.bensaid@gmail.com";
const FROM    = "HTR Tester <noreply@htr.health>";
const SUBJECT = (name: string, date: string) =>
  `[Beta Feedback] ${name} — ${date}`;

type Rating = "works" | "issues" | "broken";
interface FeedbackEntry { rating: Rating; note: string }

const EMOJI: Record<Rating, string> = {
  works:  "✅",
  issues: "⚠️",
  broken: "❌",
};

// ── Build the Markdown report ────────────────────────────────────────────────

function buildMarkdown(
  testerName: string,
  feedback: Record<string, FeedbackEntry>,
  date: string
): string {
  const total  = Object.keys(feedback).length;
  const works  = Object.values(feedback).filter((f) => f.rating === "works").length;
  const issues = Object.values(feedback).filter((f) => f.rating === "issues").length;
  const broken = Object.values(feedback).filter((f) => f.rating === "broken").length;

  const lines: string[] = [
    `# HTR Beta Tester Feedback Report`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| **Tester** | ${testerName} |`,
    `| **Submitted** | ${date} |`,
    `| **Pages rated** | ${total} |`,
    `| ✅ Works | ${works} |`,
    `| ⚠️ Issues | ${issues} |`,
    `| ❌ Broken | ${broken} |`,
    ``,
    `---`,
    ``,
  ];

  // Group by status for readability — broken first, then issues, then works
  const order: Rating[] = ["broken", "issues", "works"];
  const headings: Record<Rating, string> = {
    broken: "❌ Broken Pages",
    issues: "⚠️ Pages with Issues",
    works:  "✅ Working Pages",
  };

  for (const rating of order) {
    const entries = Object.entries(feedback).filter(([, v]) => v.rating === rating);
    if (entries.length === 0) continue;

    lines.push(`## ${headings[rating]}`, ``);
    for (const [href, entry] of entries) {
      lines.push(`### \`${href}\``);
      if (entry.note.trim()) {
        lines.push(``, `> ${entry.note.trim().replace(/\n/g, "\n> ")}`, ``);
      } else {
        lines.push(``);
      }
    }
  }

  lines.push(`---`, ``, `*Generated by the HTR Beta Tester Hub*`);
  return lines.join("\n");
}

// ── Build the HTML email body ────────────────────────────────────────────────

function buildHtml(
  testerName: string,
  feedback: Record<string, FeedbackEntry>,
  date: string
): string {
  const total  = Object.keys(feedback).length;
  const works  = Object.values(feedback).filter((f) => f.rating === "works").length;
  const issues = Object.values(feedback).filter((f) => f.rating === "issues").length;
  const broken = Object.values(feedback).filter((f) => f.rating === "broken").length;

  const badgeRow = (label: string, count: number, color: string) =>
    `<td style="text-align:center;padding:12px 16px;background:${color};border-radius:8px;min-width:80px">
      <div style="font-size:20px;font-weight:900;color:#0f172a">${count}</div>
      <div style="font-size:11px;color:#475569;margin-top:2px">${label}</div>
    </td>`;

  const entryRows = (rating: Rating) =>
    Object.entries(feedback)
      .filter(([, v]) => v.rating === rating)
      .map(
        ([href, entry]) => `
        <tr>
          <td style="padding:10px 0;border-bottom:1px solid #f1f5f9;vertical-align:top">
            <div style="display:flex;align-items:center;gap:8px">
              <span style="font-size:16px">${EMOJI[rating]}</span>
              <code style="font-size:12px;font-weight:700;color:#1e293b;background:#f8fafc;padding:2px 6px;border-radius:4px">${href}</code>
            </div>
            ${entry.note.trim() ? `<div style="font-size:12px;color:#64748b;margin:6px 0 0 24px;padding:6px 10px;background:#f8fafc;border-left:3px solid #e2e8f0;border-radius:0 4px 4px 0">${entry.note.trim()}</div>` : ""}
          </td>
        </tr>`
      )
      .join("");

  const section = (rating: Rating, title: string, headerColor: string) => {
    const rows = entryRows(rating);
    if (!rows) return "";
    return `
      <tr><td style="padding:20px 0 8px">
        <div style="font-size:13px;font-weight:800;text-transform:uppercase;letter-spacing:0.08em;color:${headerColor};margin-bottom:8px">${title}</div>
        <table width="100%" cellpadding="0" cellspacing="0">${rows}</table>
      </td></tr>`;
  };

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f8fafc;margin:0;padding:32px 16px">
  <table width="600" cellpadding="0" cellspacing="0" align="center" style="background:#fff;border-radius:12px;border:1px solid #e2e8f0;overflow:hidden">

    <!-- Header -->
    <tr><td style="background:#0f172a;padding:24px 32px">
      <div style="font-size:18px;font-weight:900;color:#fff">🧪 Beta Tester Feedback</div>
      <div style="font-size:12px;color:#94a3b8;margin-top:4px">Health Transformation Review Platform</div>
    </td></tr>

    <!-- Meta -->
    <tr><td style="padding:24px 32px 0">
      <div style="font-size:14px;color:#475569">
        <strong style="color:#0f172a">${testerName}</strong> submitted feedback on <strong>${date}</strong> — <strong>${total}</strong> pages rated.
      </div>
      <table cellpadding="0" cellspacing="8" style="margin-top:16px">
        <tr>
          ${badgeRow("✅ Works", works,  "#dcfce7")}
          <td style="width:8px"></td>
          ${badgeRow("⚠️ Issues", issues, "#fef9c3")}
          <td style="width:8px"></td>
          ${badgeRow("❌ Broken", broken, "#fee2e2")}
        </tr>
      </table>
      <p style="font-size:12px;color:#94a3b8;margin:12px 0 0">Full details in the attached <code>.md</code> file.</p>
    </td></tr>

    <!-- Sections -->
    <tr><td style="padding:8px 32px 24px">
      <table width="100%" cellpadding="0" cellspacing="0">
        ${section("broken", "❌ Broken Pages",       "#ef4444")}
        ${section("issues", "⚠️ Pages with Issues",  "#d97706")}
        ${section("works",  "✅ Working Pages",       "#16a34a")}
      </table>
    </td></tr>

    <!-- Footer -->
    <tr><td style="background:#f8fafc;padding:16px 32px;border-top:1px solid #e2e8f0">
      <p style="font-size:11px;color:#94a3b8;margin:0">Sent automatically by the HTR Beta Tester Hub</p>
    </td></tr>
  </table>
</body>
</html>`;
}

// ── Route handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  let body: { testerName?: string; feedback?: Record<string, FeedbackEntry> };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const testerName = (body.testerName ?? "Anonymous Tester").trim() || "Anonymous Tester";
  const feedback   = body.feedback ?? {};

  if (Object.keys(feedback).length === 0) {
    return NextResponse.json({ error: "No feedback to send" }, { status: 400 });
  }

  const date     = new Date().toLocaleString("en-US", { dateStyle: "full", timeStyle: "short" });
  const markdown = buildMarkdown(testerName, feedback, date);
  const html     = buildHtml(testerName, feedback, date);

  // Encode the .md file as base64 for Resend attachment
  const mdBase64 = Buffer.from(markdown, "utf-8").toString("base64");
  const filename = `HTR-Feedback-${testerName.replace(/\s+/g, "-")}-${new Date().toISOString().slice(0, 10)}.md`;

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from:        FROM,
      to:          TO,
      subject:     SUBJECT(testerName, date),
      html,
      attachments: [{ filename, content: mdBase64 }],
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    console.error("Resend error:", err);
    return NextResponse.json({ error: "Failed to send email" }, { status: 502 });
  }

  return NextResponse.json({ ok: true });
}
