// Phase 8a part 3 — source-integrity corrections for the last two courses: Health Equity Analytics (hea-*) and
// Healthcare Interoperability & Data Exchange (interop-*, ehr-business-case-roi). Same op shape as _phase8a_ops.mjs.
// Applied with: node scripts/_phase8a_apply2.mjs [--commit] --only=<docId>. Ledger: docs/audits/phase7b_sources_2026-10.jsonl, "part":"8a".

const TRUONG = 'Truong HP, Luke AA, Hammond G, Wadhera RK, Reidhead M, Joynt Maddox KE, "Utilization of Social Determinants of Health ICD-10 Z-Codes Among Hospitalized Patients in the United States, 2016–2017," Medical Care 2020 (PMC7666017): 269,929 of 14.3M NIS admissions (1.9%) carried an SDOH Z-code. The previously cited PMC12608873 is Hau et al., Healthcare (Basel) 2025, a VA trial cohort study that reports 99.2% of SDOH codes were outpatient — it does not contain the 1.9% figure.';
const HEI = 'Federal Register 88 FR 22120 (12 Apr 2023, CY2024 MA/Part D final rule) finalized the Health Equity Index reward to replace the reward factor starting with 2027 Star Ratings; CMS CY2027 MA/Part D final rule fact sheet (2 Apr 2026) — HEI reward not implemented, historical reward factor continued.';

const NHQDR = 'AHRQ, 2017 National Healthcare Quality and Disparities Report: Introduction and Methods (stacks.cdc.gov/view/cdc/85040), pp.4, 10-11: disparity = absolute difference significant at p<0.05 AND relative difference [p1-p2]/p2 >= 10%; "The largest subgroup or the subgroup that often received the best healthcare is used as the reference group"; statistics with n<30 or RSE>30% suppressed. NBK600456 = "Methods of the National Healthcare Quality and Disparities Report and Related Chartbooks" (NCBI esummary).';
const MMD = 'CMS OMH, MMD Tool FAQs (cms.gov/About-CMS/Agency-Information/OMH/Downloads/MMDT-FAQs.pdf): Population View has ten outcome measures on "up to 60 specific chronic and potentially disabling conditions" and 27 preventive services, plus ESRD/disability; Hospital View; suppression for confidentiality. CMS press release 17 Mar 2016: launched to increase understanding of disparities.';

const RUSH = 'Ansell DA et al., "Health Equity as a System Strategy: The Rush University Medical Center Framework," NEJM Catalyst May 2021, DOI 10.1056/CAT.20.0674 (full text via cultureofhealth-leaders.org PDF): strategy launched from Chicago racial life-expectancy gaps / CHNA; "In January 2017, we organized an internal Anchor Mission committee that set targets for local hiring, career pathways, local spend, and volunteering"; Health Equity Governance Committee for inequities in outcomes; the West Side Anchor Committee is a cross-institution body of six West Side health anchors.';

export const OPS = [
  // ---------------- hea-measurement-foundations
  { id: 'hea-measurement-foundations', key: 'l1s1sg1', verdict: 'MISATTRIBUTED', claim: 'stat "1.9% inpatient admissions coded with an SDOH Z-code" sourced to "Peer-reviewed SDOH Z-code adoption study, PMC" (PMC12608873)', sources: TRUONG,
    stats: { __byLabel: { 'Inpatient admissions coded with an SDOH Z-code': { context: 'Truong et al., Medical Care 2020 — 2016–2017 National Inpatient Sample' } } },
    mirrorPairs: [['Inpatient admissions coded with an SDOH Z-code despite CDC/WHO emphasis', 'Inpatient admissions coded with an SDOH Z-code, 2016–2017'], ['PMC, SDOH Z-code adoption study', 'Truong et al., Medical Care 2020 (National Inpatient Sample)'], ['Peer-reviewed SDOH Z-code adoption study, PMC', 'Truong et al., Medical Care 2020 — 2016–2017 National Inpatient Sample']] },
  { id: 'hea-measurement-foundations', key: 'l1s4p2', verdict: 'MISATTRIBUTED', claim: '"one peer-reviewed study found that only about 1.9% of inpatient hospital admissions carried an SDOH Z-code" (cited to PMC12608873)', sources: TRUONG,
    pairs: [['one peer-reviewed study found that only about 1.9% of inpatient hospital admissions carried an SDOH Z-code', 'an analysis of the 2016–2017 National Inpatient Sample (Truong et al., Medical Care, 2020) found that only about 1.9% of inpatient hospital admissions carried an SDOH Z-code']] },
  { id: 'hea-measurement-foundations', key: 'src4', verdict: 'MISATTRIBUTED', claim: 'source [4] "SDOH ICD-10 Z-code adoption study — PMC12608873 — ~1.9% of inpatient admissions"', sources: TRUONG,
    pairs: [['[4] SDOH ICD-10 Z-code adoption study — https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12608873/ — ~1.9% of inpatient admissions coded with an SDOH Z-code',
      '[4] Truong HP et al., "Utilization of Social Determinants of Health ICD-10 Z-Codes Among Hospitalized Patients in the United States, 2016–2017," Medical Care (2020) — https://pmc.ncbi.nlm.nih.gov/articles/PMC7666017/ — 1.9% of 14.3 million admissions carried an SDOH Z-code']] },
  { id: 'hea-measurement-foundations', key: 'l1qz', verdict: 'UNVERIFIABLE', claim: 'quiz explanation: Z-code use is low "despite CDC/WHO emphasis on their use"', sources: 'No CDC or WHO campaign promoting SDOH Z-code use located; the codes are part of ICD-10-CM (maintained by CDC/NCHS) and the Gravity Project–AMA coding guide is real (AMA/Gravity Project, 2023).',
    pairs: [['National data shows SDOH Z-code use around 1.9% of inpatient admissions despite CDC/WHO emphasis on their use and active crosswalk tools from the Gravity Project and AMA',
      'National Inpatient Sample data (Truong et al., 2020) show SDOH Z-codes on about 1.9% of inpatient admissions, even though the codes are part of ICD-10-CM and the Gravity Project and AMA publish crosswalk tools for them']] },
  { id: 'hea-measurement-foundations', key: 'l1s2p1', verdict: 'INACCURATE', claim: 'HEROI weights attributed to "Chapter 10, section 13.1" of the book', sources: 'HTR_Book_v42 §10.13.1 "HEROI Components" (weights 25/25/25/15/10); HealthEquityStudio.tsx line 465 uses the same weights',
    pairs: [['(Chapter 10, section 13.1)', '(Chapter 10, section 10.13.1)']] },
  { id: 'hea-measurement-foundations', key: 'l1s3p2', verdict: 'INACCURATE', claim: 'Health Equity Index reward described as "previously proposed" (it was finalized in April 2023, then not implemented)', sources: HEI,
    pairs: [['did not implement the previously proposed Health Equity Index reward for Star Ratings', 'did not implement the Health Equity Index reward for Star Ratings that CMS had finalized in 2023']],
    mirrorPairs: [['declined to implement the previously proposed Health Equity Index reward', 'declined to implement the Health Equity Index reward it had finalized in 2023'],
      ['the Health Equity Index reward was proposed but not adopted for 2027.', 'the Health Equity Index reward was finalized in 2023 but not implemented for 2027.']] },
  { id: 'hea-measurement-foundations', key: 'l1tw', verdict: 'INACCURATE', claim: 'takeaway "CMS declined to implement a proposed Health Equity Index reward"', sources: HEI,
    pairs: [['CMS declined to implement a proposed Health Equity Index reward for 2027', 'CMS declined to implement its previously finalized Health Equity Index reward for 2027']] },,
  // ---------------- hea-disparity-decomposition
  { id: 'hea-disparity-decomposition', key: 'l2s1p2', verdict: 'INACCURATE', claim: 'AHRQ NHQDR "computes rate ratios ... as its headline disparity statistic"', sources: NHQDR,
    pairs: [['computes rate ratios between each priority population and a reference group as its headline disparity statistic.', 'uses both scales at once: it counts a gap as a disparity only when the absolute difference between a priority population and its reference group is statistically significant and the relative difference is at least 10%.']],
    mirrorPairs: [['computes rate ratios between each priority population and a reference group for its headline disparity tables.', 'counts a gap as a disparity only when the absolute difference between a priority population and its reference group is statistically significant and the relative difference is at least 10%.']] },
  { id: 'hea-disparity-decomposition', key: 'l2s1p3', verdict: 'INACCURATE', claim: '"AHRQ\'s NHQDR reports rate ratios rather than differences alone"', sources: NHQDR,
    pairs: [['This is exactly why AHRQ\'s NHQDR reports rate ratios rather than differences alone — the ratio surfaces gaps that a raw percentage-point comparison can hide.', 'This is why AHRQ\'s NHQDR tests the relative difference alongside the absolute one — the relative scale surfaces gaps that a raw percentage-point comparison can hide.']] },
  { id: 'hea-disparity-decomposition', key: 'l2s3p1', verdict: 'UNVERIFIABLE', claim: '"AHRQ\'s own methodology documentation is explicit that reference-group selection is an ongoing, actively reviewed methods decision"', sources: NHQDR,
    pairs: [['AHRQ\'s own methodology documentation is explicit that reference-group selection is an ongoing, actively reviewed methods decision, not a fixed convention: comparing', 'AHRQ\'s NHQDR methods documentation states its choice explicitly — the largest subgroup or the subgroup that typically receives the best care (for example non-Hispanic White, high income, private insurance) — and the choice matters: comparing']],
    mirrorPairs: [['AHRQ\'s own methodology documentation is explicit that this choice matters and is under continuous review: comparing', 'AHRQ\'s NHQDR methods documentation states its choice explicitly (the largest subgroup or the one that typically receives the best care), and the choice matters: comparing']] },
  { id: 'hea-disparity-decomposition', key: 'l2qz', verdict: 'UNVERIFIABLE', claim: 'quiz explanation: "the reference-group effect AHRQ\'s methodology documentation flags as a disclosed choice"', sources: NHQDR,
    pairs: [['this is exactly the reference-group effect AHRQ\'s methodology documentation flags as a disclosed choice.', 'which is why AHRQ\'s NHQDR methods documentation states its reference groups explicitly.']] },
  { id: 'hea-disparity-decomposition', key: 'l2s4p1', verdict: 'INACCURATE', claim: 'arithmetic: a rate from 20 patients "can swing from a 5% disparity to a 25% disparity with just two additional events" (two events on n=20 move a rate 10 points, 5% -> 15%)', sources: 'Arithmetic: 1/20 = 5%, 3/20 = 15%. AHRQ NHQDR 2017 Methods p.4: estimates with n<30 or RSE>30% suppressed.',
    pairs: [['can swing from a 5% disparity to a 25% disparity with just two additional events', 'can jump from 5% to 15% with just two additional events (1 of 20 to 3 of 20)']],
    mirrorPairs: [['can swing from a 5% disparity to a 25% disparity with two additional events', 'can jump from 5% to 15% with two additional events (1 of 20 to 3 of 20)']] },
  { id: 'hea-disparity-decomposition', key: 'l2ex1', verdict: 'INACCURATE', claim: 'MMD Tool tracks "18-plus chronic conditions"; launched "to make the reference-group and small-numbers problems ... solvable"', sources: MMD,
    pairs: [['launched the MMD Tool in March 2016 to make the reference-group and small-numbers problems this lesson describes solvable for public users', 'launched the MMD Tool in March 2016 to increase understanding of disparities among Medicare beneficiaries — and in doing so it makes the reference-group and small-numbers problems this lesson describes solvable for public users'],
      ['The tool tracks prevalence across 18-plus chronic conditions plus end-stage renal disease and disability status', 'The tool tracks up to 60 chronic and potentially disabling conditions plus end-stage renal disease and disability status']],
    mirrorPairs: [['in March 2016 specifically to solve the reference-group and small-numbers problems for public users.', 'in March 2016 to increase understanding of disparities among Medicare beneficiaries, and its design settles the reference-group and small-numbers problems for public users.'],
      ['across 18-plus chronic conditions.', 'across up to 60 chronic and potentially disabling conditions.']],
    mirrorObjects: [{ match: { label: 'Chronic conditions the MMD Tool tracks by race/ethnicity, geography, and dual-eligibility', value: '18+' }, set: { label: 'Chronic and potentially disabling conditions the MMD Tool tracks', value: 'Up to 60' } }] },
  { id: 'hea-disparity-decomposition', key: 'src2', verdict: 'INACCURATE', claim: 'source [2] described as "rate ratio methodology"', sources: NHQDR,
    pairs: [['— rate ratio methodology and reference-group documentation', '— disparity test (significant absolute difference plus relative difference of at least 10%), reference groups, and small-sample suppression']] },,
  // ---------------- hea-stratified-quality-measurement
  { id: 'hea-stratified-quality-measurement', key: 'l3s3p1', verdict: 'INACCURATE', claim: 'CMS "proposed a Health Equity Index reward — initially branded the Excellent Health Outcomes for All reward" (it was finalized in 2023 as the HEI and renamed EHO4all later)', sources: HEI + ' Rename: CY2025 final rate announcement renamed the HEI reward "Excellent Health Outcomes for All" (Rise Health / Becker\'s Payer coverage).',
    pairs: [['CMS proposed a Health Equity Index reward — initially branded the "Excellent Health Outcomes for All" reward — as a new', 'In April 2023 CMS finalized a Health Equity Index reward — later renamed the "Excellent Health Outcomes for All" reward — as a new']],
    mirrorPairs: [['the payment incentive that had been proposed as a Health Equity Index reward for Star Ratings', 'the renamed Health Equity Index reward CMS had finalized in 2023 for Star Ratings'],
      ['CMS did not implement the previously proposed Health Equity Index reward for 2027', 'CMS did not implement the Health Equity Index reward it had finalized in 2023 (set to begin with 2027 Star Ratings)']] },
  { id: 'hea-stratified-quality-measurement', key: 'l3tw', verdict: 'INACCURATE', claim: 'takeaways: "a proposed Health Equity Index reward"; Rush "converted stratified data into an Anchor Mission committee with authority over hiring, purchasing, and community investment"', sources: HEI + ' ' + RUSH,
    pairs: [['CMS declined to implement a proposed Health Equity Index reward for 2027', 'CMS declined to implement its previously finalized Health Equity Index reward for 2027'],
      ['Rush University Medical Center converted stratified data into an Anchor Mission committee with authority over hiring, purchasing, and community investment — not just a clinical protocol change.', 'Rush University Medical Center turned a documented life-expectancy gap into standing structures — an Anchor Mission committee with local hiring and spending targets, and a Health Equity Governance Committee steering improvement work on outcome inequities — not just a clinical protocol change.']] },
  { id: 'hea-stratified-quality-measurement', key: 'l3ex1', verdict: 'INACCURATE', claim: 'Rush case: strategy "built around what stratified quality and screening data showed"; "the West Side Anchor Committee" described as Rush\'s Anchor Mission structure tasked with hiring/purchasing/investment', sources: RUSH,
    pairs: [['documented in a 2021 NEJM Catalyst case study titled "Health Equity as a System Strategy," treated stratified data as an organizing principle for the whole institution rather than a compliance artifact filed once a year by the quality department. Rush built its strategy around what stratified quality and screening data showed about its surrounding West Side Chicago neighborhood.',
        'documented in a May 2021 NEJM Catalyst article, "Health Equity as a System Strategy: The Rush University Medical Center Framework" (Ansell et al.), started from what its community health needs assessment showed: large life-expectancy gaps between downtown Chicago and the West Side neighborhoods Rush serves. Rush made equity a system strategy, with an executive lead reporting to the CEO and executive pay tied to a Diversity Index.'],
      ['Concretely, that meant forming a dedicated Anchor Mission structure — the West Side Anchor Committee — explicitly tasked with translating what the data showed into hiring, purchasing, and community-investment decisions, not only clinical protocol changes.',
        'Concretely, Rush organized an internal Anchor Mission committee in January 2017 that set targets for local hiring, career pathways, local spending, and volunteering, reporting to senior leadership twice a year, and a multidisciplinary Health Equity Governance Committee that steers improvement projects on racial, ethnic, gender, and age inequities in patient outcomes — the kind of gap only stratified data can surface. (The separate West Side Anchor Committee coordinates six West Side health systems through West Side United.)']] ,
    mirrorPairs: [['treated data stratification as a system-level strategy rather than a compliance exercise: Rush restructured its own operations around what stratified data showed about its West Side Chicago neighborhood, including forming a dedicated Anchor Mission committee to translate what the numbers found into hiring, purchasing, and investment decisions in the surrounding community — not just clinical protocol changes.',
        'treated health equity as a system-level strategy rather than a compliance exercise: starting from the life-expectancy gap its community health needs assessment documented on Chicago\'s West Side, Rush formed an internal Anchor Mission committee with targets for local hiring, career pathways, local spending, and volunteering, and a Health Equity Governance Committee to steer improvement work on racial, ethnic, gender, and age inequities in patient outcomes — not just clinical protocol changes.'],
      ['It organized hiring, purchasing, and community investment decisions (an anchor-mission approach) around what the stratified data showed', 'It organized hiring, purchasing, and community investment decisions (an anchor-mission approach) around the health gaps it had documented in its community'],
      ['translating what stratified data showed into structural, community-facing action (an anchor-mission committee)', 'translating documented health gaps into structural, community-facing action (an anchor-mission committee)']] },
  { id: 'hea-stratified-quality-measurement', key: 'src4', verdict: 'INACCURATE', claim: 'source [4] described as a "West Side Anchor Committee case study" with no authors', sources: RUSH,
    pairs: [['[4] Rush University Medical Center, "Health Equity as a System Strategy," NEJM Catalyst 2021 — https://catalyst.nejm.org/doi/full/10.1056/CAT.20.0674 — West Side Anchor Committee case study',
      '[4] Ansell DA, Oliver-Hightower D, Goodman LJ, Lateef OB, Johnson TJ, "Health Equity as a System Strategy: The Rush University Medical Center Framework," NEJM Catalyst, May 2021 — https://catalyst.nejm.org/doi/full/10.1056/CAT.20.0674 — Anchor Mission committee, Health Equity Governance Committee, West Side United']] },
];

// ---- Health Equity Analytics Lesson 4: hea-sdoh-burden-scoring
const ADI = 'Neighborhood Atlas (neighborhoodatlas.medicine.wisc.edu): "The ADI was refined, adapted, and validated to the census block group/neighborhood level by Amy Kind, MD, PhD and her research team at the University of Wisconsin-Madison"; the index originated with HRSA and Singh GK, Am J Public Health 2003;93(7):1137-43 (17 census indicators). Kind AJH, Buckingham WR, NEJM 2018;378:2456-2458 introduced the Neighborhood Atlas; it did not publish the ADI as a new approach.';
OPS.push(
  { id: 'hea-sdoh-burden-scoring', key: 'l4s3p2', verdict: 'MISATTRIBUTED', claim: 'Kind & Buckingham "published" the Area Deprivation Index in a 2018 NEJM perspective', sources: ADI,
    pairs: [['Amy Kind and William Buckingham published a distinct approach, the Area Deprivation Index (ADI), in a 2018 New England Journal of Medicine perspective, "Making Neighborhood-Disadvantage Metrics Accessible."',
      'A distinct approach is the Area Deprivation Index (ADI), an older federally developed index that Amy Kind\'s team at the University of Wisconsin–Madison refined, adapted, and validated to the census block-group level; Kind and William Buckingham described that work in a 2018 New England Journal of Medicine perspective, "Making Neighborhood-Disadvantage Metrics Accessible — The Neighborhood Atlas."']],
    mirrorPairs: [["Amy Kind and William Buckingham published the Area Deprivation Index (ADI) methodology in a 2018 *New England Journal of Medicine* perspective, 'Making Neighborhood-Disadvantage Metrics Accessible.'",
      "The Area Deprivation Index (ADI) is an older federally developed index that Amy Kind's team at the University of Wisconsin-Madison refined, adapted, and validated to the census block-group level; Kind and William Buckingham described that work in a 2018 *New England Journal of Medicine* perspective, 'Making Neighborhood-Disadvantage Metrics Accessible — The Neighborhood Atlas.'"],
      ['Despite that infrastructure and explicit CDC and WHO emphasis on their use, one peer-reviewed study found only about 1.9%', 'Despite that infrastructure, an analysis of the 2016–2017 National Inpatient Sample (Truong et al., Medical Care, 2020) found only about 1.9%']] },
  { id: 'hea-sdoh-burden-scoring', key: 'l4t1', verdict: 'MISATTRIBUTED', claim: 'comparison table credits the ADI as "Built_By: Kind & Buckingham, U. Wisconsin"', sources: ADI,
    pairs: [['Kind & Buckingham, U. Wisconsin', 'Federal (HRSA) origin; block-group version by Kind lab, U. Wisconsin']] },
  { id: 'hea-sdoh-burden-scoring', key: 'l4s6p2', verdict: 'MISATTRIBUTED', claim: '"explicit CDC and WHO emphasis on using these codes, one peer-reviewed study found only about 1.9%" (cited to PMC12608873)', sources: TRUONG + ' No CDC or WHO campaign promoting SDOH Z-code use located.',
    pairs: [['Despite that infrastructure and explicit CDC and WHO emphasis on using these codes, one peer-reviewed study found only about 1.9% of inpatient hospital admissions carried an SDOH Z-code.',
      'Despite that infrastructure, an analysis of the 2016–2017 National Inpatient Sample (Truong et al., Medical Care, 2020) found only about 1.9% of inpatient hospital admissions carried an SDOH Z-code.']] },
  { id: 'hea-sdoh-burden-scoring', key: 'l4tw', verdict: 'INACCURATE', claim: 'takeaway states the 2016-2017 figure in present tense: "Only about 1.9% of inpatient admissions carry an SDOH Z-code"', sources: TRUONG,
    pairs: [['Only about 1.9% of inpatient admissions carry an SDOH Z-code,', 'In 2016–2017 national inpatient data only about 1.9% of admissions carried an SDOH Z-code (Truong et al., 2020),']] },
  { id: 'hea-sdoh-burden-scoring', key: 'src4', verdict: 'MISATTRIBUTED', claim: 'source [4] "SDOH ICD-10 Z-code adoption study — PMC12608873 — ~1.9% of inpatient admissions coded"', sources: TRUONG,
    pairs: [['[4] SDOH ICD-10 Z-code adoption study — https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12608873/ — ~1.9% of inpatient admissions coded',
      '[4] Truong HP et al., "Utilization of Social Determinants of Health ICD-10 Z-Codes Among Hospitalized Patients in the United States, 2016–2017," Medical Care (2020) — https://pmc.ncbi.nlm.nih.gov/articles/PMC7666017/ — 1.9% of 14.3 million admissions coded']] },
);

// ---- Health Equity Analytics Lesson 5: hea-equity-weighted-economics
const ROBSON = 'Robson M, Asaria M, Cookson R, Tsuchiya A, Ali S, "Eliciting the level of health inequality aversion in England," Health Economics 2017;26(10):1328-1334 (eprints.whiterose.ac.uk/114209; PMC6120144 related): online survey n=244, median Atkinson 10.95, Kolm 0.15, implying health gains to the poorest fifth weighted 6-7x those to the richest fifth. No Cookson et al. 2017 "illustrative default" of epsilon = 0.5 located; PMC7813213 (DCEA Comes of Age, Value in Health 2021), the cited source, contains no epsilon value.';
const KP = 'AHA press release 20 Jun 2017 (aha.org/press-releases/2017-06-20-aha-recognizes-kaiser-permanente-2017-equity-care-award): award for the Equitable Care Health Outcomes (ECHO) program implemented 2010 — clinical and culturally responsive strategies to close disparity gaps in hypertension management for African-Americans and colorectal cancer screening for Hispanic populations — plus board diversity (42% people of color) and $37.1M (2016) for healthy eating/active living. The release does not describe "shared disparity data" across departments.';
const L5_KP_OLD = 'Kaiser Permanente received the American Hospital Association\'s 2017 Equity of Care Award for embedding disparity reduction into its operating structure system-wide — physicians, nurses, and staff across its integrated system working from shared disparity data rather than each department tracking equity independently and inconsistently.';
const L5_KP_NEW = 'Kaiser Permanente received the American Hospital Association\'s 2017 Equity of Care Award largely for its Equitable Care Health Outcomes (ECHO) program, launched in 2010 to close two specific, measured gaps: hypertension control among African-American members and colorectal cancer screening among Hispanic members. The AHA also cited the diversity of Kaiser\'s board and its community health investment.';
OPS.push(
  { id: 'hea-equity-weighted-economics', key: 'l5s2p2', verdict: 'FABRICATED', claim: '"Cookson and colleagues\' 2017 illustrative work used ε = 0.5 as a default representing mild inequality aversion"', sources: ROBSON,
    pairs: [['Cookson and colleagues\' 2017 illustrative work used ε = 0.5 as a default representing mild inequality aversion; larger values place sharply more priority on health gains for the worst-off group.',
      'Larger values place progressively more priority on health gains for the worst-off group. When Robson, Asaria, Cookson, Tsuchiya, and Ali surveyed 244 members of the English public (Health Economics, 2017), the median response implied an Atkinson ε of 10.95 — enough to weight health gains to the poorest fifth of society six to seven times as highly as gains to the richest fifth.']],
    mirrorPairs: [['Cookson and colleagues\' 2017 illustrative work used ε = 0.5 as a default representing mild inequality aversion; larger values put sharply more weight on health gains for the worst-off group.',
      'Larger values put progressively more weight on health gains for the worst-off group; a 2017 survey of the English public (Robson et al., Health Economics) elicited a median Atkinson ε of 10.95, weighting gains to the poorest fifth six to seven times those to the richest fifth.']] },
  { id: 'hea-equity-weighted-economics', key: 'l5s3sg1', verdict: 'FABRICATED', claim: 'stat "0.5 — Illustrative default ε (mild inequality aversion) used in Cookson et al. 2017"', sources: ROBSON,
    statsByIndex: { 2: { value: '10.95', label: 'Median Atkinson ε elicited from the English public (survey, n = 244)', context: 'Robson et al., Health Economics 2017' } } },
  { id: 'hea-equity-weighted-economics', key: 'l5tw', verdict: 'FABRICATED', claim: 'takeaway: "Cookson et al.\'s 2017 illustrative work used ε = 0.5 as a mild-aversion default"', sources: ROBSON,
    pairs: [['Cookson et al.\'s 2017 illustrative work used ε = 0.5 as a mild-aversion default', 'a 2017 survey of the English public (Robson et al.) elicited a median ε of 10.95'],
      ['Kaiser Permanente\'s 2017 AHA Equity of Care Award illustrates that a composite equity score is only as useful as the management structure built to act on it.', 'Kaiser Permanente\'s 2017 AHA Equity of Care Award, earned largely for its ECHO program targeting two specific measured gaps, illustrates that an equity score is only as useful as the sustained work built to act on it.']],
    mirrorPairs: [['Cookson et al.\'s illustrative work used ε = 0.5 as a mild-aversion default', 'a 2017 survey of the English public (Robson et al.) elicited a median Atkinson ε of 10.95'],
      ['illustrated at 0.5 by Cookson et al. 2017, not a regulatory mandate', 'elicited in studies such as Robson et al. 2017 (median 10.95 among the English public), not a regulatory mandate']] },
  { id: 'hea-equity-weighted-economics', key: 'l5ex2', verdict: 'INACCURATE', claim: 'Kaiser 2017 AHA Equity of Care Award "for embedding disparity reduction into its operating structure system-wide ... working from shared disparity data"', sources: KP,
    pairs: [[L5_KP_OLD, L5_KP_NEW], ['the one Kaiser\'s recognition illustrates directly: a composite score is only as useful as the organizational structure built around acting on what it shows.', 'the one ECHO illustrates: Kaiser picked specific measured gaps and worked them as a standing program, and a composite score is only as useful as the organizational structure built around acting on what it shows.']],
    mirrorPairs: [['Kaiser Permanente received the American Hospital Association\'s 2017 Equity of Care Award for embedding disparity reduction into its operating structure — physicians, nurses, and staff across its integrated system working from shared disparity data rather than each department tracking equity independently. The lesson for anyone building or using a composite like HEROI is the same one Kaiser\'s recognition illustrates:',
      'Kaiser Permanente received the American Hospital Association\'s 2017 Equity of Care Award largely for its Equitable Care Health Outcomes (ECHO) program, launched in 2010 to close measured gaps in hypertension control among African-American members and colorectal cancer screening among Hispanic members. The lesson for anyone building or using a composite like HEROI is the one ECHO illustrates:']] },
  { id: 'hea-equity-weighted-economics', key: 'src2', verdict: 'MISATTRIBUTED', claim: 'source [2] "ε=0.5 illustrative default from Cookson et al. 2017" attributed to PMC7813213', sources: ROBSON,
    pairs: [['[2] Distributional Cost-Effectiveness Analysis Comes of Age — https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7813213/ — equity weights, Atkinson index, ε=0.5 illustrative default from Cookson et al. 2017',
      '[2] Cookson R et al., "Distributional Cost-Effectiveness Analysis Comes of Age," Value in Health (2021) — https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7813213/ — DCEA methods and equity weights; Robson M, Asaria M, Cookson R, Tsuchiya A, Ali S, "Eliciting the level of health inequality aversion in England," Health Economics 2017;26(10):1328-1334 — median Atkinson ε 10.95']] },
  { id: 'hea-equity-weighted-economics', key: 'src3', verdict: 'INACCURATE', claim: 'source [3] gives no basis for the award', sources: KP,
    pairs: [['AHA Recognizes Kaiser Permanente with 2017 Equity of Care Award — https://www.aha.org/press-releases/2017-06-20-aha-recognizes-kaiser-permanente-2017-equity-care-award', 'AHA Recognizes Kaiser Permanente with 2017 Equity of Care Award — https://www.aha.org/press-releases/2017-06-20-aha-recognizes-kaiser-permanente-2017-equity-care-award — ECHO program (2010), board diversity, community health investment']] },
);

// ---- Health Equity Analytics Lesson 6: hea-from-score-to-action
const GALL = 'Gallifant J, Kistler EA, Nakayama LF, et al., "Disparity dashboards: an evaluation of the literature and framework for health equity improvement," Lancet Digital Health 2023 (PMC10639125): "only six evaluated the use of a disparity dashboard as part of a wider process to identify clinical disparities, hypothesize potential interventions, or track progress to a given goal." One review, not "a body of research [that] has converged". The paper does not mention Moffitt; Moffitt\'s Disparities Dashboard (clinical metrics stratified by race, ethnicity, gender, language preference) is described by Quality Interactions (qualityinteractions.com/blog/what-are-leading-organizations-doing-to-achieve-health-equity) and Moffitt\'s 2020 diversity report.';
const CMSFW = 'CMS Framework for Health Equity 2022-2032 (cms.gov/files/document/cms-framework-health-equity.pdf): Priority 2 = "Assess Causes of Disparities Within CMS Programs, and Address Inequities in Policies and Operations to Close Gaps" — a commitment about CMS\'s own programs, not a call on other organizations.';
const RUSH6 = RUSH + ' Catholic Health World, 1 Oct 2019 ("Chicago hospitals unite to address socioeconomic needs of West Side residents"): West Side ConnectED = AMITA Saints Mary and Elizabeth, University of Illinois Hospital, Rush, Mount Sinai; seven-question ED screening tool; Catholic Charities convened and linked ~30 partner agencies; funded by West Side United and IHA. AMA ("From screening to shelves") — Rush screens patients routinely and partners with the Greater Chicago Food Depository. "CommunityHealth" as a Rush screening partner not found; no source says the West Side Anchor Committee was formed to act on Rush screening data.';
const L6_RUSH_OLD = 'Rush University Medical Center\'s SDOH screening effort, built with community partners including Catholic Charities, the Greater Chicago Food Depository, and CommunityHealth (Chicago\'s largest free clinic), did not stop at collecting screening data. Rush formed a West Side Anchor Committee explicitly to convert what the screening and stratified quality data showed into standing operating processes — shared goals, common referral pathways, and joint investment decisions with those community partners.';
const L6_RUSH_NEW = 'Rush University Medical Center screens patients routinely for social needs such as housing, food access, and violence, and works with the Greater Chicago Food Depository on food programs. In West Side ConnectED, Rush, the University of Illinois Hospital, AMITA Health Saints Mary and Elizabeth Medical Center, and Mount Sinai Hospital share a seven-question emergency-department screening tool, and Catholic Charities linked the hospitals to about 30 partner agencies ready to take referrals. Inside Rush, an Anchor Mission committee organized in January 2017 sets targets for local hiring, career pathways, local spending, and volunteering and reports to senior leadership twice a year, and a Health Equity Governance Committee steers improvement work on inequities in patient outcomes (Ansell et al., NEJM Catalyst, 2021).';
OPS.push(
  { id: 'hea-from-score-to-action', key: 'l6s2p1', verdict: 'INACCURATE', claim: '"A body of published research on disparity dashboards has converged on a consistent finding" (one 2023 review)', sources: GALL,
    pairs: [['A body of published research on disparity dashboards has converged on a consistent finding: dashboards that stratify data by race, ethnicity, or other subgroup are increasingly common, but dashboards demonstrably tied to a specific accountability structure — someone whose job it is to act when a gap appears — are much rarer.',
      'A 2023 Lancet Digital Health review of the disparity-dashboard literature (Gallifant et al.) found that dashboards stratifying data by race, ethnicity, or other subgroup are increasingly common, but only six of the studies it evaluated used a dashboard as part of a wider process to identify disparities, hypothesize interventions, or track progress toward a goal. Dashboards tied to someone whose job it is to act when a gap appears are the exception.']],
    mirrorPairs: [['A body of published research on disparity dashboards has converged on a consistent finding: dashboards that stratify data by race, ethnicity, or other subgroup are common, but dashboards that are demonstrably tied to a specific accountability structure — someone whose job it is to act when a gap appears — are much rarer.',
      'A 2023 Lancet Digital Health review of the disparity-dashboard literature (Gallifant et al.) found that stratified dashboards are common, but only six of the studies it evaluated used a dashboard as part of a wider process to identify disparities, hypothesize interventions, or track progress toward a goal. Dashboards tied to someone whose job it is to act when a gap appears are the exception.'],
      ['The consistent finding is that stratified dashboards are common, but ones tied to a real accountability structure that acts on the data are much rarer', 'A 2023 Lancet Digital Health review found stratified dashboards common but few embedded in a wider process to identify disparities, test interventions, and track progress']] },
  { id: 'hea-from-score-to-action', key: 'l6st1', verdict: 'INACCURATE', claim: 'CMS Framework Priority 2 described as "assess causes of disparities within an organization\'s own programs and operations"', sources: CMSFW,
    pairs: [['This maps directly onto Priority 2 of the CMS Framework for Health Equity 2022–2032: assess causes of disparities within an organization\'s own programs and operations, not just document their existence.',
      'It mirrors Priority 2 of the CMS Framework for Health Equity 2022–2032, in which CMS commits to assess the causes of disparities within its own programs and address inequities in its policies and operations, not just document that disparities exist.']],
    mirrorPairs: [['This maps directly to Priority 2 of the CMS Framework for Health Equity 2022–2032: assess causes of disparities within programs and operations, not just their existence.',
      'It mirrors Priority 2 of the CMS Framework for Health Equity 2022–2032, in which CMS commits to assess causes of disparities within its own programs and address inequities in its policies and operations.']] },
  { id: 'hea-from-score-to-action', key: 'l6s4h', verdict: 'FABRICATED', claim: 'heading "From Screening Data to an Anchor-Mission Committee"', sources: RUSH6,
    pairs: [['Case Study: From Screening Data to an Anchor-Mission Committee', 'Case Study: From Screening to Standing Committees']],
    mirrorPairs: [['Case study: from screening data to an anchor-mission committee', 'Case study: from screening to standing committees']] },
  { id: 'hea-from-score-to-action', key: 'l6ex1', verdict: 'FABRICATED', claim: 'Rush "formed a West Side Anchor Committee explicitly to convert what the screening and stratified quality data showed" with partners incl. "CommunityHealth"', sources: RUSH6,
    pairs: [[L6_RUSH_OLD, L6_RUSH_NEW], ['That committee is this lesson\'s governance loop made concrete: a named structure', 'Those committees are this lesson\'s governance loop made concrete: named structures'],
      ['Rush University Medical Center — West Side Anchor Committee', 'Rush University Medical Center — From Screening to Standing Committees']],
    mirrorPairs: [[L6_RUSH_OLD.replace(/’/g, "'") , L6_RUSH_NEW],
      ['That committee is the \'someone whose job it is to act\' this lesson\'s governance loop describes, made concrete.', 'Those committees are the \'someone whose job it is to act\' this lesson\'s governance loop describes, made concrete.'],
      ['Rush University Medical Center\'s West Side Anchor Committee was formed specifically to convert SDOH screening and stratified quality data into standing operational decisions with community partners.',
        'Rush University Medical Center\'s internal Anchor Mission committee, organized in January 2017, sets standing targets for local hiring, career pathways, local spending, and volunteering.'],
      ['This matches the case study directly: the committee was formed to translate what screening data showed into shared goals, referral pathways, and investment decisions with partners like Catholic Charities and the Greater Chicago Food Depository.',
        'This matches the case study (Ansell et al., NEJM Catalyst 2021): the committee owns standing targets and reports to senior leadership twice a year — a named structure whose job is to act.']] },
  { id: 'hea-from-score-to-action', key: 'l6tw', verdict: 'INACCURATE', claim: 'takeaways restate the dashboard "research finds", Priority 2 as a call on organizations, and the fabricated Rush West Side Anchor Committee role', sources: GALL + ' | ' + CMSFW + ' | ' + RUSH6,
    pairs: [['Published research on disparity dashboards finds that stratified dashboards are common, but dashboards tied to a real accountability structure that acts on the data are much rarer — measurement alone does not produce action.',
      'A 2023 Lancet Digital Health review (Gallifant et al.) found that only six of the dashboard studies it evaluated used the dashboard within a wider process to identify disparities, test interventions, or track progress toward a goal — measurement alone does not produce action.'],
      ['CMS\'s Framework for Health Equity 2022–2032 explicitly calls for assessing causes of disparities within an organization\'s own programs and operations, not only documenting that disparities exist.',
        'In Priority 2 of its Framework for Health Equity 2022–2032, CMS commits to assessing the causes of disparities within its own programs and operations, not only documenting that disparities exist — a discipline any organization can apply to its own.'],
      ['Rush University Medical Center\'s West Side Anchor Committee is a concrete, named structure that converted SDOH and quality data into standing operational decisions with community partners.',
        'Rush University Medical Center pairs routine social-needs screening (including the West Side ConnectED emergency-department collaborative) with named standing bodies — an Anchor Mission committee and a Health Equity Governance Committee — that own targets and act on what the data show.']] },
  { id: 'hea-from-score-to-action', key: 'l6qz', verdict: 'INACCURATE', claim: 'quiz explanation: literature "specifically identifies dashboards lacking a defined accountability structure as prone to sitting unused"', sources: GALL,
    pairs: [['The disparity-dashboard research literature specifically identifies dashboards lacking a defined accountability structure as prone to sitting unused', 'A 2023 review of the disparity-dashboard literature found few dashboards embedded in a wider process to identify disparities, test interventions, and track progress']] },
  { id: 'hea-from-score-to-action', key: 'src2', verdict: 'MISATTRIBUTED', claim: 'source [2] credited with the Moffitt Disparities Dashboard, which it does not mention', sources: GALL,
    pairs: [['[2] Disparity dashboards: an evaluation of the literature and framework for health equity improvement — https://pmc.ncbi.nlm.nih.gov/articles/PMC10639125/ — the measurement-without-action finding; Moffitt Cancer Center Disparities Dashboard',
      '[2] Gallifant J et al., "Disparity dashboards: an evaluation of the literature and framework for health equity improvement," Lancet Digital Health (2023) — https://pmc.ncbi.nlm.nih.gov/articles/PMC10639125/ — only six evaluated studies used a dashboard within a wider improvement process. Moffitt Cancer Center Disparities Dashboard: Quality Interactions, "What are leading organizations doing to achieve health equity" — https://www.qualityinteractions.com/blog/what-are-leading-organizations-doing-to-achieve-health-equity']] },
  { id: 'hea-from-score-to-action', key: 'src3', verdict: 'INACCURATE', claim: 'source [3] "Priority 2, assessing causes of disparities"', sources: CMSFW,
    pairs: [['— Priority 2, assessing causes of disparities', '— Priority 2, assess causes of disparities within CMS programs']] },
  { id: 'hea-from-score-to-action', key: 'src4', verdict: 'FABRICATED', claim: 'source [4] cited for a "West Side Anchor Committee" role it does not describe', sources: RUSH6,
    pairs: [['[4] Rush University Medical Center, "Health Equity as a System Strategy," NEJM Catalyst 2021 — https://catalyst.nejm.org/doi/full/10.1056/CAT.20.0674 — West Side Anchor Committee',
      '[4] Ansell DA et al., "Health Equity as a System Strategy: The Rush University Medical Center Framework," NEJM Catalyst, May 2021 — https://catalyst.nejm.org/doi/full/10.1056/CAT.20.0674 — Anchor Mission committee, Health Equity Governance Committee; Catholic Health World, "Chicago hospitals unite to address socioeconomic needs of West Side residents" (Oct 1, 2019) — West Side ConnectED']] },
);

// ======== Healthcare Interoperability & Data Exchange ========
// ---- interop-hl7-v2 (hl7-v2-legacy-messaging)
const HL7PB = 'HL7 Version 2 Product Brief via NLM Health Data Standards tutorial (nlm.nih.gov/oet/ed/healthdatastandards/03-300.html): "95% of U.S. healthcare organizations" and "more than 35 countries" use HL7 v2. No source located for "85% of all healthcare data exchanges" or "15 billion HL7 v2 messages annually" (searched); these are dropped.';
const MLLPPORT = 'IANA Service Name and Transport Protocol Port Number Registry (iana.org, search "hl7"): hl7 = port 2575 tcp/udp. Port 6660 is not a recognized HL7 convention (Mirth defaults to 6661); interfaces are configured per agreement.';
const HL7HIST = 'HL7 Version 2.6 standard, ch.1 Introduction (hl7.eu/HL7v2x/v26/std26/ch01.html): "HL7 ... established in March 1987 on the occasion of a conference hosted by Dr. Sam Schultz at the Hospital of the University of Pennsylvania." Medblocks history: March 29-31, 1987, Philadelphia; v2 published 1988.';
OPS.push(
  { id: 'interop-hl7-v2', key: 's1p2', verdict: 'UNVERIFIABLE', claim: '"Estimates place HL7 v2 at handling roughly 85% of all healthcare data exchanges ... over 15 billion HL7 v2 messages annually"', sources: HL7PB,
    pairs: [['Estimates place HL7 v2 at handling roughly 85% of all healthcare data exchanges in the United States, with American hospitals collectively processing over 15 billion HL7 v2 messages annually. ', '']] },
  { id: 'interop-hl7-v2', key: 's1stats', verdict: 'UNVERIFIABLE', claim: 'stats "85% Healthcare Data Exchanges" and "15B+ Messages Annually"', sources: HL7PB, removeStats: ['s2', 's4'] },
  { id: 'interop-hl7-v2', key: 's1p3', verdict: 'UNVERIFIABLE', claim: '"Most health systems will run HL7 v2 well into the 2040s"', sources: 'Forecast with no source; dropped the specific decade.',
    pairs: [['Most health systems will run HL7 v2 well into the 2040s alongside FHIR, not instead of it.', 'Most health systems will run HL7 v2 alongside FHIR for many years to come, not replace it outright.']] },
  { id: 'interop-hl7-v2', key: 's4p3', verdict: 'UNVERIFIABLE', claim: '"A large academic medical center may operate 800 to 1,200 active HL7 interfaces"', sources: 'No source located for the 800-1,200 range; specific dropped.',
    pairs: [['may operate 800 to 1,200 active HL7 interfaces', 'may operate a very large number of active HL7 interfaces']] },
  { id: 'interop-hl7-v2', key: 's5p2', verdict: 'INACCURATE', claim: 'MLLP "has no standard port — port 6660 is commonly used by convention"', sources: MLLPPORT,
    pairs: [['It has no standard port — port 6660 is commonly used by convention — and it requires', 'IANA registers port 2575 for HL7, though in practice each interface listens on whatever port the two parties agree — and it requires']] },
  { id: 'interop-hl7-v2', key: 'tkwy', verdict: 'UNVERIFIABLE', claim: 'takeaways repeat "an estimated 85% of U.S. healthcare data exchanges" and "over 15 billion v2 messages per year"', sources: HL7PB,
    pairs: [['and now handles an estimated 85% of U.S. healthcare data exchanges.', 'and remains the dominant messaging standard in U.S. hospitals.'],
      ['95% of U.S. healthcare organizations use HL7 v2; American hospitals process over 15 billion v2 messages per year.', 'HL7 International reports that 95% of U.S. healthcare organizations use HL7 v2 and more than 35 countries have implemented it.']] },
  { id: 'interop-hl7-v2', key: 'src1', verdict: 'MISATTRIBUTED', claim: 'source [1] (Medblocks) credited with the Hospital of the University of Pennsylvania venue, which it does not state', sources: HL7HIST,
    pairs: [['— Confirms HL7 was founded in March 1987 at the Hospital of the University of Pennsylvania and that HL7 v2 was published in 1988 with billing and lab results workflows.',
      '— March 29–31, 1987 founding meeting in Philadelphia; Version 2 published in 1988. Venue and host: HL7 Version 2.6 standard, Chapter 1 Introduction — https://www.hl7.eu/HL7v2x/v26/std26/ch01.html — "a conference hosted by Dr. Sam Schultz at the Hospital of the University of Pennsylvania."']] },
  { id: 'interop-hl7-v2', key: 'src4', verdict: 'INACCURATE', claim: 'source [4] description "absence of a standard port (port 6660 by convention)"', sources: MLLPPORT,
    pairs: [['the absence of a standard port (port 6660 by convention), and the reliance on TLS for security.', 'and the reliance on TLS for security. IANA port registry: hl7 = 2575/tcp — https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=hl7']] },
  { id: 'interop-hl7-v2', key: 'src5', verdict: 'FABRICATED', claim: 'source [5] URL blog.interfaceware.com/custom-segments-hl7-z-segments/ returns 404', sources: 'curl 2026-10-09: 404. Replacement iNTERFACEWARE Infopedia "Z-segments" definition (indexed; same content: custom segments begin with Z; receiving applications usually ignore unknown Z-segments).',
    pairs: [['"Custom Segments: HL7 Z-segments" — iNTERFACEWARE Blog — https://blog.interfaceware.com/custom-segments-hl7-z-segments/', '"Z-segments" — iNTERFACEWARE Infopedia — https://infopedia.interfaceware.com/definition/z-segments/']] },
  { id: 'interop-hl7-v2', key: 's1p1', verdict: 'FABRICATED', claim: 'fallback text: founders "met at a hotel in Philadelphia"; v2 "carrying an estimated 95% of all clinical data transactions"; "300+ active HL7 interfaces"; stat "95% of US hospital data transactions"; unsourced "real-world" failure case undetected "for 6 months"', sources: HL7HIST + ' | ' + HL7PB + ' | fallback case study has no source; reframed as illustrative and the unsourced 6-month detail dropped.',
    mirrorPairs: [['who met at a hotel in Philadelphia.', 'who met at the Hospital of the University of Pennsylvania in Philadelphia.'],
      ['carrying an estimated 95% of all clinical data transactions in US hospitals to this day.', 'used today, HL7 International reports, by 95% of U.S. healthcare organizations.'],
      ['A large hospital system may have 300+ active HL7 interfaces, each requiring ongoing maintenance.', 'A large hospital system may run a very large number of active HL7 interfaces, each requiring ongoing maintenance.'],
      ['of US hospital data transactions use HL7 v2', 'of U.S. healthcare organizations use HL7 v2 (HL7 International)'],
      ['Real-world HL7 v2 failure: medication errors from interface mismatches', 'Illustrative HL7 v2 failure: medication errors from interface mismatches'],
      ['A hospital integrated a new pharmacy system with their EHR via HL7 v2.', 'Consider a hospital that integrates a new pharmacy system with its EHR via HL7 v2.'],
      ['The EHR expected drug codes in the standard CE data type field within OBX. Because the interface was not correctly mapped, medications arrived as free text strings with no structured code. Pharmacists could not perform automated drug interaction checks. The error went undetected for 6 months because the data \'looked right\' on screen.',
        'The EHR expects drug codes in a standard coded (CE) field. Because the interface is not correctly mapped, medications arrive as free-text strings with no structured code, and pharmacists cannot run automated drug-interaction checks. Errors like this can go unnoticed for a long time because the data \'looks right\' on screen.']] },
);

// ---- interop-fhir-intro (hl7-fhir-introduction)
const G10 = 'Sequoia Project RCE, FHIR Roadmap for TEFCA Exchange Version 2.0 (Dec 2023), p.2: health IT developers had to provide "upgraded API technology certified to this new certification criterion by no later than December 31, 2022" (deadline moved from 24 months after publication by ONC\'s Nov 2020 Interim Final Rule, 85 FR 70064).';
const TEFCAR = 'FHIR Roadmap for TEFCA Exchange v2.0 (rce.sequoiaproject.org, Dec 2023): four stages; Stage 2 (QHIN-Facilitated FHIR Exchange) planned for "full production availability in CY 2024"; Stage 3 QHIN-to-QHIN FHIR exchange "expected to begin to be piloted in CY 2025". A plan with targets, not a record of completion, and it does not state a requirement on all QHINs.';
const GRIEVE = 'HL7 International, "FHIR Celebrates 10th Birthday" (info.hl7.org/fhir-10th-birthday): Grahame Grieve, Melbourne, Australia, Principal at Health Intersections; FHIR "originally called \'Resources for Healthcare\'". The page does not mention a listserv post or his title; "Fresh Look at Healthcare Interoperability" was not the proposal\'s name.';
const EPICN = 'No public source located for "340+" Epic App Showroom SMART apps "as of 2025" or "thousands" of apps registered on fhir.epic.com (searched); specifics dropped.';
OPS.push(
  { id: 'interop-fhir-intro', key: 's1p3', verdict: 'UNVERIFIABLE', claim: 'Grieve "published a proposal on the HL7 listserv" and "has served as FHIR Product Director at HL7 International ever since" (2011)', sources: GRIEVE,
    pairs: [['published a proposal on the HL7 listserv under the name "Resources for Healthcare."', 'put forward a proposal called "Resources for Healthcare."'],
      ['and Grieve has served as FHIR Product Director at HL7 International ever since.', 'and Grieve went on to lead its development as HL7\'s FHIR Product Director.']],
    mirrorPairs: [['In 2011, a New Zealand health informaticist named Grahame Grieve published a proposal called \'Fresh Look at Healthcare Interoperability.\'', 'In 2011, an Australian health informaticist named Grahame Grieve put forward a proposal originally called \'Resources for Healthcare.\''],
      ['Grahame Grieve publishes \'Fresh Look at Healthcare Interoperability.\' HL7 begins FHIR development.', 'Grahame Grieve proposes \'Resources for Healthcare.\' HL7 begins FHIR development.'],
      ['FHIR STU3 becomes the first version widely implemented in EHR products. Apple Health Records uses STU3.', 'FHIR STU3 published, with substantial maturation of the resource set.'],
      ['{"year":"2023","label":"R4B and R5"', '{"year":"2022–2023","label":"R4B and R5"'],
      ['Health IT vendors will not migrate to R5 until regulatory and implementation guide support catches up — a process that typically takes 3–5 years.', 'Health IT vendors will not migrate to R5 until regulatory and implementation guide support catches up.']] },
  { id: 'interop-fhir-intro', key: 's2p2', verdict: 'INACCURATE', claim: '"The specification also defines a $search operation"', sources: 'HL7 FHIR R4 RESTful API (hl7.org/fhir/R4/http.html): search is a RESTful interaction (GET [base]/[type]?params or POST _search), not a $-operation.',
    pairs: [['The specification also defines a $search operation with a rich query syntax', 'The specification also defines a search interaction with a rich query syntax']] },
  { id: 'interop-fhir-intro', key: 's4p1', verdict: 'INACCURATE', claim: '(g)(10) "compliance deadline in May 2022"', sources: G10,
    pairs: [['EHR developers were given 24 months from the publication date to update their technology, placing the compliance deadline in May 2022.', 'EHR developers were originally given 24 months from publication to update their technology; ONC\'s November 2020 interim final rule moved the deadline to December 31, 2022.']] },
  { id: 'interop-fhir-intro', key: 's4p3', verdict: 'INACCURATE', claim: 'TEFCA FHIR Roadmap "requiring all QHINs to progressively implement FHIR API exchange — with Stages 1 and 2 completing in 2024"', sources: TEFCAR,
    pairs: [['laid out a phased four-stage plan requiring all QHINs to progressively implement FHIR API exchange — with Stages 1 and 2 completing in 2024.', 'laid out a phased four-stage plan for FHIR exchange under TEFCA, targeting full production availability of QHIN-facilitated FHIR exchange (Stage 2) in 2024 and pilots of QHIN-to-QHIN FHIR exchange (Stage 3) in 2025.']] },
  { id: 'interop-fhir-intro', key: 's4stats', verdict: 'INACCURATE', claim: 'stats "EHR Developer Deadline May 2022" and "TEFCA Stages 1 & 2 — QHINs complete ... 2024"', sources: G10 + ' | ' + TEFCAR,
    stats: { s3: { value: 'Dec 31, 2022', context: 'Deadline for EHR developers to ship the § 170.315(g)(10) FHIR R4 API — originally 24 months after publication, extended by ONC\'s November 2020 interim final rule' },
      s4: { value: 'CY 2024', label: 'TEFCA Stage 2 Target', context: 'FHIR Roadmap v2.0 target for full production availability of QHIN-facilitated FHIR exchange' } } },
  { id: 'interop-fhir-intro', key: 's5p3', verdict: 'UNVERIFIABLE', claim: '"thousands of third-party applications have registered" on fhir.epic.com; Epic App Showroom "hosts over 340 SMART on FHIR applications"', sources: EPICN,
    pairs: [['Epic operates fhir.epic.com, a developer portal through which thousands of third-party applications have registered. The Epic App Showroom (formerly App Orchard) hosts over 340 SMART on FHIR applications.', 'Epic operates fhir.epic.com, a developer portal for building against its FHIR APIs, and the Epic Showroom (successor to App Orchard) lists third-party applications, many of them SMART on FHIR apps.']] },
  { id: 'interop-fhir-intro', key: 's5stats', verdict: 'UNVERIFIABLE', claim: 'stat "340+ applications registered in Epic\'s SMART on FHIR marketplace as of 2025"', sources: EPICN, removeStats: ['s3'] },
  { id: 'interop-fhir-intro', key: 'tk1', verdict: 'INACCURATE', claim: 'takeaway: "hundreds of certified third-party applications"', sources: EPICN + ' Third-party apps are not "certified" under the ONC program.',
    pairs: [['with hundreds of certified third-party applications now operating in clinical workflows.', 'with third-party applications now operating in clinical workflows.']] },
  { id: 'interop-fhir-intro', key: 'src5', verdict: 'MISATTRIBUTED', claim: 'source [5] described as confirming Grieve\'s role as FHIR Product Director', sources: GRIEVE,
    pairs: [['— Official HL7 retrospective confirming Grahame Grieve\'s authorship of the original FHIR proposal in 2011 and his ongoing role as FHIR Product Director at HL7 International.', '— Official HL7 retrospective on FHIR\'s origins: Grahame Grieve (Melbourne, Australia) and the standard\'s original name, "Resources for Healthcare."']] },
  { id: 'interop-fhir-intro', key: 'src7', verdict: 'INACCURATE', claim: 'source [7] described as "with Stages 1 and 2 completing in 2024"', sources: TEFCAR,
    pairs: [['with Stages 1 and 2 completing in 2024.', 'targeting Stage 2 production availability in CY 2024 and Stage 3 pilots in CY 2025; also restates the December 31, 2022 (g)(10) deadline.']] },
  { id: 'interop-fhir-intro', key: 's1stats', verdict: 'UNVERIFIABLE', claim: 'fallback key_stat "1B+ FHIR API calls per month across US health systems ... As of 2024"', sources: 'No source located for 1B+ monthly FHIR API calls (searched); replaced with the verified R4 resource count (145, HL7 FHIR R4 resource list).',
    mirrorObjects: [{ match: { year: '2023', label: 'R4B and R5' }, set: { year: '2022–2023' } }, { match: { type: 'key_stat', value: '1B+', label: 'FHIR API calls per month across US health systems' }, set: { value: '145', label: 'resource types defined in FHIR R4', context: 'HL7 FHIR R4 resource list. Each is a discrete, independently addressable unit of healthcare data; R4 remains the U.S. regulatory baseline.' } }] },
);

// ---- interop-cda-ccda (cda-ccda-clinical-documents)
const CCDAV = 'hl7.org/cda/us/ccda/package-list.json: C-CDA 3.0.0 trial-use 2024-05-18 (USCDI v4); 4.0.0 trial-use 2025-06-20 (USCDI v5); 5.0.0 trial-use 2026-06-13 (USCDI v6) = current. All are STU (trial-use), not normative. hl7.org/fhir/us/ccda/package-list.json: C-CDA on FHIR 2.0.0 trial-use published 2026-06-05 (1.2.0 was 2024-03-12).';
const CG = 'eCFR 45 CFR 170.205(a)(5): "C-CDA Templates for Clinical Notes R2.1 Companion Guide, Release 2 ... The adoption of this standard expires on January 1, 2026"; (a)(6) adopts Companion Guide Release 4.1. It is the Companion Guide R2 adoption that expired, not C-CDA 2.1 as such.';
const CONS = 'HL7 C-CDA IG (hl7.org/cda/us/ccda): C-CDA harmonized prior guides from the HL7 Health Story project, IHE, HITSP C32 and the original CCD within ONC\'s S&I Framework. No source located for the count "seven" (searched); count dropped.';
const MU2 = 'CMS Stage 2 Meaningful Use, Summary of Care core measure (77 FR 53968, Sept 4 2012): summary of care record for >50% of transitions of care/referrals, >10% transmitted electronically — not "every transition ... where feasible".';
const DAM18 = 'D\'Amore J et al., "Interoperability Progress and Remaining Data Quality Barriers of Certified Health Information Technologies," AMIA Annu Symp Proc 2018 (PMC6371305): "The automated tools used in this work identified 13 times more issues than schematron validation alone" — one study, not "studies".';
const ATL = 'healthit.gov blog "Introducing Leidos as a new ONC-ATL" (2022) lists Drummond Group, ICSA Labs, SLI Compliance and Leidos as ONC-ATLs; no source ranks any as "the two largest". cda-validation.nist.gov now states "These tools have moved" (immunization/syndromic suites to Prometheus Computing) — no CDA validator there. No public "Lantana Group Schematron Validator" located. ONC Scorecard has no documented "70%" risk threshold.';
const DAM14 = 'D\'Amore JD et al., "Are Meaningful Use Stage 2 certified EHRs ready for interoperability? Findings from the SMART C-CDA Collaborative," JAMIA 2014;21(6):1060-8: 91 sample C-CDAs from 21 technologies, 615 observations of errors and data-expression issues in 11 areas. No JAMIA study found reporting "60% of C-CDAs received at a large academic medical center".';
OPS.push(
  { id: 'interop-cda-ccda', key: 's2p1', verdict: 'UNVERIFIABLE', claim: 'C-CDA consolidated "seven previously separate CDA implementation guides"', sources: CONS,
    pairs: [['drove the consolidation of seven previously separate CDA implementation guides into a single, nationally harmonized specification.', 'drove the consolidation of previously separate CDA implementation guides — from the HL7 Health Story project, IHE, HITSP C32, and the original CCD — into a single, nationally harmonized specification.']] },
  { id: 'interop-cda-ccda', key: 's2p3', verdict: 'INACCURATE', claim: '"C-CDA 4.0 has been published as the current normative version, and C-CDA 5.0 is in active ballot"; "regulatory adoption of C-CDA 2.1 expired as a standalone certification basis on January 1, 2026"', sources: CCDAV + ' | ' + CG,
    pairs: [['However, the HL7 community moved quickly: C-CDA 4.0 has been published as the current normative version, and C-CDA 5.0 is in active ballot. The regulatory adoption of C-CDA 2.1 expired as a standalone certification basis on January 1, 2026, marking a transition to newer versions aligned with the US Core Data for Interoperability (USCDI) requirements.',
      'The HL7 community then moved quickly: C-CDA 3.0 (May 2024, USCDI v4), 4.0 (June 2025, USCDI v5), and 5.0 (June 2026, USCDI v6) — all Standards for Trial Use — with 5.0 the current version. On the regulatory side, ONC\'s adoption of the C-CDA R2.1 Companion Guide, Release 2 expired on January 1, 2026; certification now references Companion Guide Release 4.1, aligned with USCDI v3.']] },
  { id: 'interop-cda-ccda', key: 's3p1', verdict: 'INACCURATE', claim: 'MU Stage 2 required C-CDA exchange "for every transition of care and referral where feasible"', sources: MU2,
    pairs: [['required eligible professionals and eligible hospitals to electronically exchange summary care records using C-CDA for every transition of care and referral where feasible.', 'required eligible professionals and eligible hospitals to provide a summary of care record for more than 50% of transitions of care and referrals — and to transmit more than 10% electronically — using certified technology that produced those records as C-CDA documents.']] },
  { id: 'interop-cda-ccda', key: 's3st', verdict: 'UNVERIFIABLE', claim: 'step: "consolidating seven prior guides"', sources: CONS,
    pairs: [['consolidating seven prior guides into one US-realm standard', 'consolidating earlier Health Story, IHE, HITSP, and CCD guides into one US-realm standard']] },
  { id: 'interop-cda-ccda', key: 's4p2', verdict: 'INACCURATE', claim: 'C-CDA on FHIR "currently version 1.2.0 STU 1 ... with version 2.0.0 in continuous build development"', sources: CCDAV,
    pairs: [['(currently version 1.2.0 STU 1, based on FHIR R4, with version 2.0.0 in continuous build development)', '(version 2.0.0, published June 2026 as a Standard for Trial Use, based on FHIR R4)']] },
  { id: 'interop-cda-ccda', key: 's4p3', verdict: 'UNVERIFIABLE', claim: '"Tens of thousands of EHR installations generate and consume C-CDA documents daily"', sources: 'No count located; specific dropped.',
    pairs: [['Tens of thousands of EHR installations generate and consume C-CDA documents daily', 'EHR installations across the country generate and consume C-CDA documents daily']] },
  { id: 'interop-cda-ccda', key: 's4cmp', verdict: 'INACCURATE', claim: 'C-CDA "Mature: 20+ years of production use" (C-CDA dates from 2011; CDA R2 from 2005)', sources: CONS,
    pairs: [['Mature: 20+ years of production use', 'Mature: built on CDA R2 (2005), C-CDA in production since the early 2010s']] },
  { id: 'interop-cda-ccda', key: 's5p1', verdict: 'INACCURATE', claim: '"Studies have found that automated tools identify approximately thirteen times more issues"', sources: DAM18,
    pairs: [['Studies have found that automated tools identify approximately thirteen times more issues than schematron validation alone', 'One study (D\'Amore et al., AMIA 2018) found that automated tools identified 13 times more issues than schematron validation alone']] },
  { id: 'interop-cda-ccda', key: 's5p3', verdict: 'UNVERIFIABLE', claim: '"The two largest ATLs in the US are Drummond Group and ICSA Labs"; "Lantana Group\'s Schematron Validator"; "NIST CDA Validation tool hosted at cda-validation.nist.gov"', sources: ATL,
    pairs: [['The two largest ATLs in the US are Drummond Group and ICSA Labs. Both test C-CDA creation and reception as part of the 45 CFR 170.315(b)(1) Transitions of Care criterion. Real-world implementation teams also rely on the Lantana Group\'s Schematron Validator and the NIST CDA Validation tool hosted at cda-validation.nist.gov.',
      'ONC-ATLs such as Drummond Group and SLI Compliance test C-CDA creation and reception as part of the 45 CFR 170.315(b)(1) Transitions of Care criterion.']] },
  { id: 'interop-cda-ccda', key: 's5call', verdict: 'FABRICATED', claim: '"A score below 70% signals real interoperability risk"', sources: ATL,
    pairs: [[' A score below 70% signals real interoperability risk for receiving systems.', ' Treat a falling score as an early warning for receiving systems.']] },
  { id: 'interop-cda-ccda', key: 'tw1', verdict: 'INACCURATE', claim: 'takeaways: "C-CDA 4.0 is the current normative HL7 version, with 5.0 in active ballot"; "The two largest ONC-Authorized Testing Laboratories — Drummond Group and ICSA Labs"; "v1.2.0 STU 1"', sources: CCDAV + ' | ' + ATL,
    pairs: [['C-CDA 4.0 is the current normative HL7 version, with 5.0 in active ballot.', 'C-CDA 5.0 (June 2026, trial use, USCDI v6) is the current HL7 version.'],
      ['The two largest ONC-Authorized Testing Laboratories — Drummond Group and ICSA Labs — test', 'ONC-Authorized Testing Laboratories such as Drummond Group and SLI Compliance test'],
      ['The C-CDA on FHIR IG (v1.2.0 STU 1, FHIR R4) bridges both worlds.', 'The C-CDA on FHIR IG (v2.0.0, FHIR R4) bridges both worlds.'],
      ['Automated best-practice tools catch approximately 13 times more quality issues than schematron validation alone.', 'In one study (D\'Amore et al., 2018), automated tools caught 13 times more quality issues than schematron validation alone.']] },
  { id: 'interop-cda-ccda', key: 'src2', verdict: 'INACCURATE', claim: 'source [2] "C-CDA v4.0.0 ... current published normative version"', sources: CCDAV,
    pairs: [['[2] Consolidated CDA (C-CDA) v4.0.0 — HL7 International, IG Home Page — https://hl7.org/cda/us/ccda/ — Confirms C-CDA 4.0 as current published normative version; documents C-CDA 2.1 and 3.0 history and document types.', '[2] Consolidated CDA (C-CDA) — HL7 International, IG Home Page — https://hl7.org/cda/us/ccda/ — Current version 5.0.0 (trial use, June 2026, USCDI v6); version history 3.0 (2024), 4.0 (2025); document types.']] },
  { id: 'interop-cda-ccda', key: 'src5', verdict: 'INACCURATE', claim: 'source [5] "C-CDA on FHIR v1.2.0 ... Confirms C-CDA on FHIR STU 1 (v1.2.0)"', sources: CCDAV,
    pairs: [['[5] C-CDA on FHIR v1.2.0 — HL7 International Implementation Guide — http://hl7.org/fhir/us/ccda/ — Confirms C-CDA on FHIR STU 1 (v1.2.0) based on FHIR R4;', '[5] C-CDA on FHIR — HL7 International Implementation Guide — https://hl7.org/fhir/us/ccda/ — Current version 2.0.0 (trial use, June 2026), based on FHIR R4;']] },
  { id: 'interop-cda-ccda', key: 'src6', verdict: 'INACCURATE', claim: 'source [6] given no authors', sources: DAM18,
    pairs: [['[6] Interoperability Progress and Remaining Data Quality Barriers of Certified Health IT — PMC / National Library of Medicine —', '[6] D\'Amore J et al., "Interoperability Progress and Remaining Data Quality Barriers of Certified Health Information Technologies," AMIA Annual Symposium Proceedings 2018 —']] },
  { id: 'interop-cda-ccda', key: 's1p1', verdict: 'FABRICATED', claim: 'fallback: "A study published in JAMIA found that 60% of C-CDAs received at a large academic medical center had at least one data quality issue"; C-CDA "required for Meaningful Use attestation"; FHIR "Document resource profile"', sources: DAM14 + ' FHIR documents are Bundles of type "document" whose first entry is a Composition (hl7.org/fhir/R4/documents.html). Meaningful Use is now Medicare Promoting Interoperability; the requirement sits in ONC certification.',
    mirrorPairs: [['A study published in the Journal of the American Medical Informatics Association found that 60% of C-CDAs received at a large academic medical center had at least one data quality issue — medications listed as allergies, problem lists duplicated across sections, immunization dates missing.',
      'A 2014 study in the Journal of the American Medical Informatics Association (D\'Amore et al., SMART C-CDA Collaborative) examined 91 sample C-CDAs from 21 certified technologies and recorded 615 errors and data-expression issues in 11 areas — for example, omitted or misused allergic reactions and missing medication dose frequency.'],
      ['FHIR supports document exchange through its Document resource profile — essentially packaging FHIR resources', 'FHIR supports document exchange through document Bundles built around a Composition resource — essentially packaging FHIR resources'],
      ['However, C-CDA remains required for Meaningful Use attestation, most HIE networks, and transition of care workflows.', 'However, C-CDA remains required for ONC-certified EHR technology, most HIE networks, and transition of care workflows.']] },
);
