// Phase 8a part 5 — source-integrity corrections for the last six Healthcare Interoperability & Data Exchange lessons
// (interop-interface-engines onward). Same op shape as _phase8a_ops3.mjs. Applied with:
//   node scripts/_phase8a_apply4.mjs [--commit] --only=<docId>
// Ledger: docs/audits/phase7b_sources_2026-10.jsonl, "part":"8a".

export const OPS = [];

// ---- Interop: interop-interface-engines
const HL7B = 'HL7 Version 2 Product Brief, quoted in NLM "Health Data Standards and Terminologies: A Tutorial" (nlm.nih.gov/oet/ed/healthdatastandards/03-300.html): "95% of U.S. healthcare organizations and more than 35 countries were using it". The figure is for organizations, not hospital interfaces. No source located for "85% of all healthcare data exchanges", "15 billion+ messages annually" or "50,000-500,000 messages per day".';
const CLOV = 'Infor Cloverleaf product page (infor.com/products/cloverleaf, read 2026-10-10) gives no connected-application or messages-per-day totals; no source located for "500,000 applications" or "one billion messages daily" (Infor/NetApp case studies cite single deployments of 60-70 million messages per day).';
const COST = 'Cited source lifepoint.com/hl7-interface-engine-cost (read 2026-10-10) says only "each customization will usually cost thousands of dollars" — no $8,000 per-interface, $2-5M annual-spend, $500K-$2M licence or timeline figures. No primary source located for them.';
const MKT = 'Cited source healthcareintegrations.com/hl7-vs-fhir-which-standard-should-you-prioritize-in-2025 (Aug 27, 2025; read 2026-10-10) contains none of: 29.95% healthcare iPaaS CAGR, 60% FHIR build-time reduction, $450M (2024) / $1.12B (2032) market. 29.93% is a general (all-industry) iPaaS forecast; no healthcare-specific primary source located.';
const FORR = 'Rhapsody blog, "Total Economic Impact report: how Rhapsody delivers 193% ROI for health tech teams" (Aug 2024): Forrester Consulting TEI study commissioned by Rhapsody, interviewed health technology teams, 193% three-year ROI, NPV $1.59M. Rhapsody blog/BusinessWire (Feb 7, 2024): Best in KLAS Integration Engine for the 15th consecutive year (Corepoint 95.6, Rhapsody 93.0). rhapsody.health: "1,900+ healthcare teams in 31 countries".';
const ISC = 'InterSystems "InterSystems versus Mirth Connect" page: a large health system built its platform on HealthShare Health Connect in under a year; it supports 1,000 interfaces, 104 million messages per weekday and 136 connected systems — the page does not say it bridges Epic, translates ADT to FHIR, or describe its alerting. InterSystems "Success with healthcare data integration at scale": an Epic IDN saw a 330% increase in message volume after its Epic deployment (73 million per day).';
const MIRTH = 'NextGen Healthcare, "A new era for Mirth Connect" (announced March 19, 2025): Mirth Connect 4.6 moved from dual open-source/commercial licensing to a single proprietary licence; community fork Open Integration Engine launched spring 2025. NextGen Mirth page: powers "1/3 of all public Health Information Exchanges", used in over 40 countries.';
const CURESDL = '85 FR 70064 (Nov 4, 2020 interim final rule) moved the 45 CFR 170.315(g)(10) standardized FHIR API deadline to December 31, 2022.';
OPS.push(
  { id: 'interop-interface-engines', key: 'sg1', verdict: 'UNVERIFIABLE', claim: 'stats "95% of U.S. hospitals use HL7 v2" (source says organizations), "15B+ HL7 messages sent annually", "50,000-500,000 messages per day", "800+ interfaces", "$2-5M annual HL7 infrastructure spend"', sources: HL7B + ' | ' + COST + ' | ' + ISC,
    replaceBlock: { _type: 'statGrid', stats: [
      { _key: 'h0', label: 'of U.S. healthcare organizations use HL7 v2', value: '95%', context: 'HL7 Version 2 Product Brief — despite the standard dating from the late 1980s' },
      { _key: 'h1', label: 'countries using HL7 v2', value: '35+', context: 'HL7 Version 2 Product Brief' },
      { _key: 'h2', label: 'interfaces in one documented health system', value: '1,000', context: '136 connected systems and 104 million messages per weekday through InterSystems Health Connect' },
      { _key: 'h3', label: 'messages per day at one Epic IDN', value: '73M', context: 'A 330% rise in message volume after its Epic go-live (InterSystems case study)' }] } },
  { id: 'interop-interface-engines', key: 's2p1', verdict: 'MISATTRIBUTED', claim: '"An independent Forrester study found that health systems using Rhapsody achieved a 193% return ... driven primarily by reduced integration engineering time and improved data reliability" (Rhapsody-commissioned TEI of interviewed health tech teams)', sources: FORR,
    pairs: [['An independent Forrester study found that health systems using Rhapsody achieved a 193% return on investment over three years, driven primarily by reduced integration engineering time and improved data reliability.', 'A 2024 Forrester Consulting Total Economic Impact study, commissioned by Rhapsody, found a 193% three-year return on investment for the health technology teams it interviewed.']] },
  { id: 'interop-interface-engines', key: 's2p2', verdict: 'UNVERIFIABLE', claim: '"More than 500,000 applications are connected through Cloverleaf globally, with over one billion messages passing through the platform daily"', sources: CLOV,
    pairs: [[' More than 500,000 applications are connected through Cloverleaf globally, with over one billion messages passing through the platform daily.', '']] },
  { id: 'interop-interface-engines', key: 'cmp1', verdict: 'UNVERIFIABLE', claim: '"Higher upfront licensing cost ($500K–$2M+/year)"', sources: COST,
    pairs: [['Higher upfront licensing cost ($500K–$2M+/year)', 'Higher licensing costs']] },
  { id: 'interop-interface-engines', key: 'ex1', verdict: 'INACCURATE', claim: 'example embellishes the InterSystems case: "bridges Epic and multiple legacy systems, translates HL7 v2 ADT feeds into FHIR resources ... monitors every message queue in real time with automated alerting" (not in the source)', sources: ISC,
    pairs: [['A large integrated health system documented building a full enterprise integration platform on InterSystems HealthShare Health Connect in under 12 months. At go-live it supported 136 connected systems and over 1,000 active interfaces, processing 104 million messages on a typical weekday. The engine bridges Epic and multiple legacy systems, translates HL7 v2 ADT feeds into FHIR resources for downstream analytics, and monitors every message queue in real time with automated alerting when volume anomalies suggest a upstream system failure.', 'InterSystems reports that a large health system built its enterprise integration platform on HealthShare Health Connect in under a year; it now supports 1,000 interfaces and 136 connected systems and processes 104 million messages on a typical weekday. A separate InterSystems case study describes an Epic-based integrated delivery network whose message volume rose 330%, to 73 million messages a day, after its Epic go-live — the kind of growth that makes queue monitoring and volume alerting essential.']] },
  { id: 'interop-interface-engines', key: 's3p1', verdict: 'UNVERIFIABLE', claim: '"The healthcare iPaaS market is growing at nearly 30% annually"', sources: MKT,
    pairs: [[' The healthcare iPaaS market is growing at nearly 30% annually, driven by EHR interoperability mandates and the expansion of telehealth infrastructure.', ' Federal FHIR API mandates and the expansion of telehealth have accelerated their adoption in healthcare.']] },
  { id: 'interop-interface-engines', key: 'sg2', verdict: 'UNVERIFIABLE', claim: 'stats "29.95% iPaaS CAGR in healthcare", "60% reduction in app integration time with FHIR", "$1.12B projected market by 2032, up from $450M in 2024"', sources: MKT + ' Replacement stats: ' + FORR + ' | ' + MIRTH + ' | ' + CURESDL,
    replaceBlock: { _type: 'statGrid', stats: [
      { _key: 'm0', label: 'three-year ROI in a Rhapsody-commissioned Forrester study', value: '193%', context: 'Total Economic Impact study of interviewed health technology teams (2024)' },
      { _key: 'm1', label: 'certified FHIR API deadline', value: 'Dec 31, 2022', context: 'Standardized (g)(10) patient and population APIs required of certified health IT' },
      { _key: 'm2', label: 'MuleSoft API-led connectivity', value: '3-tier', context: 'System, Process, and Experience APIs organize integration complexity into manageable, reusable layers' },
      { _key: 'm3', label: 'Mirth Connect release that went proprietary', value: 'v4.6', context: 'Announced March 2025; the community forked the code as Open Integration Engine' }] } },
  { id: 'interop-interface-engines', key: 's4p1', verdict: 'UNVERIFIABLE', claim: '"four to twelve weeks ... three to four months ... six to eighteen months"; "The cost of a single custom point-to-point interface can reach $8,000 or more"', sources: COST,
    pairs: [['typically spans four to twelve weeks for a straightforward feed, and can stretch to three to four months for complex multi-system integrations involving custom segment mapping, error handling logic, and compliance with specific data governance rules. For a full enterprise implementation involving dozens of interfaces, the timeline often extends to six to eighteen months. The cost of a single custom point-to-point interface can reach $8,000 or more when labor is factored in, which helps explain why large health systems with hundreds of interfaces face annual integration budgets in the millions.', 'takes weeks for a straightforward feed and can stretch to months for complex multi-system integrations involving custom segment mapping, error handling logic, and compliance with specific data governance rules. A full enterprise implementation involving dozens of interfaces takes longer still. Every custom interface carries build and maintenance labor, which is why large health systems with hundreds of interfaces carry substantial annual integration budgets.']] },
  { id: 'interop-interface-engines', key: 's5p1', verdict: 'UNVERIFIABLE', claim: '"Organizations implementing FHIR-based integrations report up to 60% reductions in the time required to build new application connections"', sources: MKT,
    pairs: [[' Organizations implementing FHIR-based integrations report up to 60% reductions in the time required to build new application connections, compared to traditional HL7 v2 interface development.', '']] },
  { id: 'interop-interface-engines', key: 's5p2', verdict: 'UNVERIFIABLE', claim: '"In 2024, 95% of U.S. healthcare organizations were still using HL7 v2, and the standard handles an estimated 85% of all healthcare data exchanges"', sources: HL7B,
    pairs: [['In 2024, 95% of U.S. healthcare organizations were still using HL7 v2, and the standard handles an estimated 85% of all healthcare data exchanges.', 'HL7 International reports that 95% of U.S. healthcare organizations use HL7 v2.']] },
  { id: 'interop-interface-engines', key: 'tkwy', verdict: 'UNVERIFIABLE', claim: 'takeaways "HL7 v2 powers 95% of U.S. hospital interfaces and handles an estimated 85% of all healthcare data exchanges"; "Infor Cloverleaf (1 billion messages/day)"; "Building a single interface costs $8,000+ ... annual integration budgets of $2–5 million"', sources: HL7B + ' | ' + CLOV + ' | ' + COST,
    pairs: [['HL7 v2 powers 95% of U.S. hospital interfaces and handles an estimated 85% of all healthcare data exchanges, despite being developed in the 1980s.', 'HL7 v2 is used by 95% of U.S. healthcare organizations (HL7 International), despite being developed in the 1980s.'],
      ['Infor Cloverleaf (1 billion messages/day)', 'Infor Cloverleaf'],
      ['Building a single interface costs $8,000+ and takes weeks to months; large health systems carry annual integration budgets of $2–5 million for software, staff, and support.', 'Building a single interface takes weeks to months, and every interface must be retested when a connected system is upgraded — the change-management burden that drives large integration budgets.']] },
  { id: 'interop-interface-engines', key: 'src1', verdict: 'MISATTRIBUTED', claim: 'source [1] "193% ROI over three years per Forrester TEI study" (commissioned)', sources: FORR,
    pairs: [['193% ROI over three years per Forrester TEI study.', '193% three-year ROI per a Rhapsody-commissioned Forrester TEI study (2024).']] },
  { id: 'interop-interface-engines', key: 'src3', verdict: 'UNVERIFIABLE', claim: 'source [3] "Over 500,000 connected applications; more than one billion messages pass through Cloverleaf daily" (not on the page)', sources: CLOV,
    pairs: [['Claim: Over 500,000 connected applications; more than one billion messages pass through Cloverleaf daily; 20+ years in healthcare integration market.', 'Claim: Enterprise HL7/FHIR integration engine with a long track record in large health systems.']] },
  { id: 'interop-interface-engines', key: 'src4', verdict: 'INACCURATE', claim: 'source [4] URL/attribution: the 1,000/104M/136 figures come from InterSystems\' comparison page, not product documentation', sources: ISC,
    pairs: [['[4] InterSystems HealthShare Health Connect — InterSystems official documentation — https://www.intersystems.com/products/healthshare/health-connect/ — Claim: One documented deployment supports 1,000 interfaces, 104 million messages per weekday, and 136 connected systems.', '[4] InterSystems, "InterSystems versus Mirth Connect" and "Success with healthcare data integration at scale" — https://www.intersystems.com/lp/intersystems-versus-mirth-connect/ — Claim: One large health system supports 1,000 interfaces, 104 million messages per weekday, and 136 connected systems; an Epic IDN reached 73 million messages per day.']] },
  { id: 'interop-interface-engines', key: 'src5', verdict: 'UNVERIFIABLE', claim: 'source [5] "v2 handles 85% of all healthcare data exchanges; over 15 billion messages annually" (not in NLM page)', sources: HL7B,
    pairs: [['[5] HL7 v2 Dominance Statistics — NLM / CapMinds / Dataa.dev — https://www.nlm.nih.gov/oet/ed/healthdatastandards/03-300.html — Claim: 95% of U.S. healthcare organizations use HL7 v2; v2 handles 85% of all healthcare data exchanges; over 15 billion messages annually in the U.S.', '[5] NLM, Health Data Standards and Terminologies: A Tutorial (quoting the HL7 Version 2 Product Brief) — https://www.nlm.nih.gov/oet/ed/healthdatastandards/03-300.html — Claim: 95% of U.S. healthcare organizations and more than 35 countries use HL7 v2.']] },
  { id: 'interop-interface-engines', key: 'src6', verdict: 'UNVERIFIABLE', claim: 'source [6] "$8,000+; $2–5M annually; 4–6 weeks to 6–18 months" (not in the cited page)', sources: COST,
    pairs: [['Claim: Single custom interface can cost $8,000+; large health systems spend $2–5M annually on HL7 infrastructure; timeline ranges from 4–6 weeks (simple) to 6–18 months (enterprise).', 'Claim: Each interface customization usually costs thousands of dollars.']] },
  { id: 'interop-interface-engines', key: 'src7', verdict: 'UNVERIFIABLE', claim: 'source [7] "29.95% CAGR; 60%; $1.12B by 2032" (not in the cited page)', sources: MKT + ' | ' + CURESDL,
    pairs: [['[7] FHIR Adoption and iPaaS Market Growth — HealthcareIntegrations.com / MordorIntelligence / Folio3 — https://healthcareintegrations.com/hl7-vs-fhir-which-standard-should-you-prioritize-in-2025/ — Claim: Healthcare iPaaS market growing at 29.95% CAGR; FHIR reduces new integration build time by 60%; healthcare integration software market to reach $1.12B by 2032.', '[7] HL7 vs. FHIR: Which Standard Should You Prioritize in 2025? — HealthcareIntegrations.com — https://healthcareintegrations.com/hl7-vs-fhir-which-standard-should-you-prioritize-in-2025/ — Claim: Health systems must run HL7 v2 and FHIR side by side rather than choose one.']] },
  { id: 'interop-interface-engines', key: 'intro1', verdict: 'UNVERIFIABLE', claim: 'fallback: "A large academic medical center may have 400–600 active interfaces"; key_stat "400-600 active interfaces at a typical large hospital" with "$10,000–$50,000 per interface per year ... $5–25M annually"; Mirth described as current open-source/free (proprietary since v4.6) in concept card and quiz', sources: COST + ' | ' + MIRTH,
    mirrorPairs: [
      ['why a large hospital may have 500 active interfaces requiring constant maintenance', 'why a large hospital may run hundreds of active interfaces requiring constant maintenance'],
      ['A large academic medical center may have 400–600 active interfaces:', 'A large academic medical center may run hundreds of active interfaces:'],
      ['The total cost of interface ownership — including initial build, testing, ongoing maintenance, and monitoring — is estimated at $10,000–$50,000 per interface per year. A hospital with 500 interfaces faces $5–25M annually in interface maintenance costs alone.', 'One documented health system runs 1,000 interfaces across 136 connected systems (InterSystems). Every interface carries build, testing, maintenance, and monitoring costs for as long as it runs.'],
      ['Mirth Connect (open source, widely used in smaller organizations and HIEs)', 'Mirth Connect (long open source and widely used in smaller organizations and HIEs; proprietary since version 4.6 in 2025)'],
      ['Open-source interface engine maintained by NextGen. Free to use, large community, strong HL7 v2 support. Used by many HIEs and smaller organizations.', 'Interface engine maintained by NextGen; open source until version 4.6 (2025) moved it to a proprietary licence, prompting the Open Integration Engine community fork. Strong HL7 v2 support; NextGen says it powers a third of U.S. public HIEs.'],
      ['Mirth Connect\'s open-source model made it the interface engine of choice for regional HIEs and smaller organizations that needed capable integration without commercial licensing costs.', 'Mirth Connect\'s long-standing open-source model made it the interface engine of choice for regional HIEs and smaller organizations that needed capable integration without commercial licensing costs — until NextGen moved version 4.6 to a proprietary licence in 2025.'],
      ['An open-source platform widely used by HIEs and smaller organizations', 'A long-time open-source platform widely used by HIEs and smaller organizations']],
    mirrorObjects: [{ match: { label: 'active interfaces at a typical large hospital', value: '400-600' }, set: { label: 'interfaces in one documented health system', value: '1,000' } }] },
);

// ---- Interop: interop-snomed-loinc-rxnorm
const RXAPI = 'RxNav REST (rxnav.nlm.nih.gov/REST/rxcui/{id}/properties, queried 2026-10-10): RxCUI 860975 = "24 HR metformin hydrochloride 500 MG Extended Release Oral Tablet"; 861007 = "metformin hydrochloride 500 MG Oral Tablet" (SCD); 200256 = "repaglinide 1 MG Oral Tablet"; carvedilol 3.125 MG Oral Tablet = 686924 (SCD).';
const SCT = 'tx.fhir.org CodeSystem/$lookup (SNOMED CT, 2026-10-10): 73211009 = "Diabetes mellitus"; 44054006 = "Type 2 diabetes mellitus" (parent 73211009; finding sites endocrine pancreatic structure / endocrine system — no insulin-resistance relationship); 372687004 = "Amoxicillin" (substance); 91936005 = "Allergy to penicillin".';
const WHI = 'West Health Institute, "The Value of Medical Device Interoperability" (March 2013; Healthcare IT News, FierceHealthcare): medical device interoperability could save more than $30 billion a year (less redundant testing, manual data entry, adverse events, length of stay). It is a device-interoperability savings estimate, not a measure of semantic/terminology inefficiency.';
const COVID = 'loinc.org SARS-CoV-2 LOINC page: the Regenstrief LOINC team worked with APHL, CDC, FDA, labs and IVD manufacturers and published pre-release SARS-CoV-2 terms ahead of the normal release cycle; HHS CARES Act Section 18115 laboratory data reporting guidance (June 4, 2020) required LOINC-coded test results. No source for "all 50 states within weeks" or day/week delay comparisons between states.';
const HTI1 = 'HTI-1 final rule (89 FR 1192, published Jan 9, 2024; effective Feb 8, 2024): USCDI v3 with US Core 6.1.0 required of certified health IT by Jan 1, 2026. No source for a TEFCA "July 4, 2026" FHIR/US Core deadline. Information blocking CMPs (up to $1M per violation) are imposed by HHS-OIG on developers, HIEs and HINs (42 U.S.C. 300jj-52); providers face CMS disincentives instead (89 FR 54662).';
OPS.push(
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0003', verdict: 'INACCURATE', claim: '"Federal regulators — ONC, CMS, and the HHS Office of the National Coordinator" (ONC listed twice)', sources: 'ONC is the HHS Office of the National Coordinator for Health IT (renamed ASTP/ONC in 2024).',
    pairs: [['Federal regulators — ONC, CMS, and the HHS Office of the National Coordinator — mandate their use', 'Federal regulators — ONC (now ASTP/ONC) and CMS — mandate their use']] },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0015', verdict: 'INACCURATE', claim: 'Type 2 DM concept "is associated with insulin resistance" (no such SNOMED relationship)', sources: SCT,
    pairs: [['carries relationships expressing that it is a subtype of diabetes mellitus, involves the pancreas, and is associated with insulin resistance — information', 'carries relationships expressing that it is a subtype of diabetes mellitus and that its finding site is the endocrine pancreas — information']] },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0017', verdict: 'FABRICATED', claim: 'empty comparisonBlock (both sides blank labels, no points) — renders an empty card', sources: 'Sanity body inspected 2026-10-10: left/right label "" and points [].', removeBlock: true },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0025', verdict: 'UNVERIFIABLE', claim: 'stat "Languages Supported 30+"', sources: 'No current LOINC source located for 30+ languages (Vreeman et al. 2012: nine languages / 15 linguistic variants as of v2.36). LOINC 2.75 (2023) release notes: 101,632 terms. Six defining axes per LOINC Users\' Guide.',
    replaceBlock: { _type: 'statGrid', items: [{ label: 'Total Terms', value: '~101,600+' }, { label: 'Governing Body', value: 'Regenstrief Institute' }, { label: 'Founded', value: '1994' }, { label: 'Release Cadence', value: 'Twice yearly' }, { label: 'License Cost', value: 'Free' }, { label: 'Defining Axes', value: '6' }] } },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0033', verdict: 'INACCURATE', claim: '"CMS and ONC require LOINC codes on all structured lab result data exchanged via FHIR APIs"', sources: HTI1 + ' US Core Laboratory Result Observation binds Observation.code to LOINC (extensible).',
    pairs: [['CMS and ONC require LOINC codes on all structured lab result data exchanged via FHIR APIs as part of the 21st Century Cures Act regulations.', 'Certified FHIR APIs under the 21st Century Cures Act regulations must follow US Core, whose laboratory result profile binds the test code to LOINC.']] },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0036', verdict: 'UNVERIFIABLE', claim: '"enabling consistent surveillance reporting across all 50 states within weeks of the first tests becoming available"', sources: COVID,
    pairs: [['During the COVID-19 pandemic, the Regenstrief team rapidly created dedicated LOINC codes for SARS-CoV-2 diagnostic tests — enabling consistent surveillance reporting across all 50 states within weeks of the first tests becoming available.', 'During the COVID-19 pandemic, the Regenstrief team began coordinating with CDC, public health and reference labs, and test manufacturers in January 2020 and published dedicated SARS-CoV-2 test codes as pre-release terms, ahead of the normal release cycle.']] },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0049', verdict: 'INACCURATE', claim: 'RxCUI 860975 given for "Metformin HCl 500 mg oral tablet" (860975 is the 24 HR extended-release tablet)', sources: RXAPI,
    pairs: [["(RxCUI: 860975)", "(RxCUI: 861007)"]] },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0057', verdict: 'INACCURATE', claim: '"Suspected Type 2 diabetes mellitus using SNOMED CT concept 73211009" (73211009 = Diabetes mellitus); "RxCUI 860975" for metformin 500 mg oral tablet (ER code)', sources: SCT + ' | ' + RXAPI,
    pairs: [["The clinician's EHR problem list captures 'Suspected Type 2 diabetes mellitus' using SNOMED CT concept 73211009.", "The clinician's EHR problem list captures suspected diabetes using SNOMED CT concept 73211009 (Diabetes mellitus)."],
      ['carries RxCUI 860975 alongside', 'carries RxCUI 861007 alongside']] },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0062', verdict: 'UNVERIFIABLE', claim: '"with FHIR-formatted value sets available for the 2027 reporting period"', sources: 'No CMS/VSAC source located tying FHIR value sets to the 2027 reporting period (VSAC already serves value sets via a FHIR terminology API).',
    pairs: [['As CMS transitions its eCQMs to FHIR-based dQMs — with FHIR-formatted value sets available for the 2027 reporting period — VSAC becomes', 'As CMS transitions its eCQMs to FHIR-based dQMs, VSAC — which already serves value sets through a FHIR terminology API — becomes']] },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0071', verdict: 'MISATTRIBUTED', claim: '"The U.S. healthcare system loses an estimated $30 billion annually in avoidable inefficiencies ... traced in part to poor data interoperability at the semantic level" (WHI 2013 device-interoperability savings estimate)', sources: WHI,
    pairs: [['The U.S. healthcare system loses an estimated $30 billion annually in avoidable inefficiencies — including unnecessary repeat diagnostics, delayed treatment decisions, and administrative overhead — that can be traced in part to poor data interoperability at the semantic level.', 'For a sense of scale, the West Health Institute estimated in 2013 that making medical devices interoperable with each other and with EHRs could save more than $30 billion a year — through less redundant testing, less manual data entry, fewer adverse events, and shorter stays.']] },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0075', verdict: 'INACCURATE', claim: 'SNOMED "372687004 — Allergy to penicillin" (372687004 = Amoxicillin substance; Allergy to penicillin = 91936005)', sources: SCT,
    pairs: [['(e.g., 372687004 — Allergy to penicillin)', '(e.g., 91936005 — Allergy to penicillin)']] },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0077', verdict: 'INACCURATE', claim: 'carvedilol 3.125 mg "(RxCUI 200256)" (200256 = repaglinide 1 MG; carvedilol 3.125 MG Oral Tablet = 686924)', sources: RXAPI,
    pairs: [['(RxCUI 200256)', '(RxCUI 686924)']] },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0079', verdict: 'UNVERIFIABLE', claim: '"States that had already implemented LOINC-coded lab reporting could contribute data within days. Those relying on free-text ... delays of days to weeks"', sources: COVID,
    pairs: [[' States that had already implemented LOINC-coded lab reporting could contribute data within days. Those relying on free-text or non-standard codes required manual curation, introducing delays of days to weeks into public health surveillance — a real-world demonstration of what standardized terminology makes possible at scale.', ' HHS\'s June 2020 CARES Act laboratory reporting guidance then required LOINC-coded results, so every testing site reported the same test the same way — a real-world demonstration of what standardized terminology makes possible at scale.']] },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0082', verdict: 'FABRICATED', claim: '"HTI-1 Final Rule (effective 2025)"; "By July 4, 2026, networks participating in TEFCA must expose data via FHIR APIs aligned with US Core IG and USCDI v3"; "information blocking penalties of up to $1 million per violation under ONC enforcement authority"', sources: HTI1,
    pairs: [['The HTI-1 Final Rule (effective 2025) mandates specific minimum releases of SNOMED CT, LOINC, and RxNorm in certified systems. By July 4, 2026, networks participating in TEFCA (Trusted Exchange Framework and Common Agreement) must expose data via FHIR APIs aligned with US Core IG and USCDI v3 — with labs coded in LOINC, medications in RxNorm, and conditions in SNOMED CT. Non-compliance carries information blocking penalties of up to $1 million per violation under ONC enforcement authority.', 'The HTI-1 Final Rule (effective February 2024) mandates specific minimum releases of SNOMED CT, LOINC, and RxNorm in certified systems and made USCDI v3, exposed through US Core 6.1.0 FHIR APIs, the certification baseline from January 1, 2026 — with labs coded in LOINC, medications in RxNorm, and conditions in SNOMED CT. Developers, HIEs, and HINs that commit information blocking face civil monetary penalties of up to $1 million per violation, imposed by the HHS Office of Inspector General.']] },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0087', verdict: 'MISATTRIBUTED', claim: 'takeaway "Terminology failures ... contribute to $30+ billion in annual US healthcare inefficiency"', sources: WHI,
    pairs: [['Terminology failures — free-text drug names, uncoded allergy entries, non-standard lab identifiers — contribute to $30+ billion in annual US healthcare inefficiency and create direct patient safety risks.', 'Terminology failures — free-text drug names, uncoded allergy entries, non-standard lab identifiers — create direct patient safety risks and force manual curation every time data crosses an organizational boundary.']] },
  { id: 'interop-snomed-loinc-rxnorm', key: 'k0008', verdict: 'UNVERIFIABLE', claim: 'fallback key_stat context "350,000+ concepts and 1.5 million relationships"', sources: 'SNOMED International: more than 350,000 concepts; no source located for "1.5 million relationships" in the current release.',
    mirrorPairs: [["SNOMED CT's 350,000+ concepts and 1.5 million relationships make it the most comprehensive clinical ontology in existence.", "SNOMED CT's 350,000+ concepts, each formally defined by relationships to other concepts, make it the most comprehensive clinical terminology in existence."]] },
);

// ---- Interop: interop-uscdi
const USV = 'ISP USCDI page (isp.healthit.gov/united-states-core-data-interoperability-uscdi): v1 July 2020 errata; v2 July 2021; v3 July 2022 (Oct 2022 errata), 19 classes incl. "Unique Device Identifier(s) for a Patient\'s Implantable Device(s)" — no "Referral Notes" class (referral notes are a Clinical Notes element); v4 July 2023 (Oct 2023 errata) "added 20 data elements and one data class"; v5 July 16, 2024; v6 July 24, 2025. Particle Health USCDI changelog: v2 3 new classes / 22 new elements (incl. SOGI and SDOH); v3 2 new classes / 24 new elements, 94 total. ONC Standards Bulletin 2026-1: Draft v7 (Jan 29, 2026) 30 proposed additions.';
const PLUS = 'healthit.gov USCDI+ page: five domains listed (Public Health, Quality, Cancer, Behavioral Health, Maternal Health); "In December 2023, ONC launched a new USCDI+ platform"; no "13+ use cases", "launched 2021" or "voluntary" statement. ecqi.healthit.gov/uscdi-quality: Quality list draws on CMS eCQMs, the CMS Data Element Library, AHRQ Common Formats and NCQA HEDIS; developed with CDC, HRSA and CMS. No ONC source ties USCDI+ to TEFCA, and HTI-1 does not require USCDI+.';
const RULES = '85 FR 25642 (Cures Act Final Rule): USCDI v1, information blocking (45 CFR 171), (g)(10) FHIR API, EHI export (b)(10); no "500k patient records" developer threshold exists. HTI-1 (89 FR 1192): USCDI v3 by Jan 1, 2026, decision support intervention (DSI) algorithm-transparency criterion, discontinued year-named editions, TEFCA Manner exception; it neither requires USCDI+ nor "expands CEHRT scope to more developers".';
const PSY = 'ONC Data Brief No. 35 / Healthcare Innovation (2016), AHA 2015 IT Supplement: 96% of non-federal acute care hospitals possessed certified EHR technology in 2015; only 15% of psychiatric hospitals had adopted a basic EHR. No ONC source located for "86% ... only 67% of psychiatric hospitals".';
const CEHRTR = 'Certification is held by health IT developers\' products (45 CFR 170 Subpart E), not by hospitals; providers must use CEHRT meeting current criteria to satisfy Promoting Interoperability / MIPS PI, whose failure brings Medicare payment adjustments.';
OPS.push(
  { id: 'interop-uscdi', key: 'blk-v3-2', verdict: 'INACCURATE', claim: 'v3 class list includes "Referral Notes" and omits the Unique Device Identifier(s) class', sources: USV,
    pairs: [['Procedures, Provenance, Referral Notes, and Vital Signs.', 'Procedures, Provenance, Unique Device Identifier(s) for a Patient\'s Implantable Device(s), and Vital Signs.']] },
  { id: 'interop-uscdi', key: 'analogy-building-code', verdict: 'FABRICATED', claim: 'broken analogyBlock whose only text is "[Unhandled block type: analogyBlock]"', sources: 'Sanity body inspected 2026-10-10.', removeBlock: true },
  { id: 'interop-uscdi', key: 'ex-cehrt', verdict: 'INACCURATE', claim: 'hospital system faces "its next CEHRT certification renewal" and "risks losing certification" (certification belongs to the developer\'s product)', sources: CEHRTR,
    pairs: [['A regional hospital system using Epic or Oracle Health must ensure its EHR can receive and send all 94 data elements in USCDI v3 — including the new Health Insurance Information class and the equity-focused Disability Status elements — before its next CEHRT certification renewal. Failure to meet the January 1, 2026 deadline risks losing certification, which would disqualify the system from participating in MIPS and could result in Medicare payment penalties.', 'A regional hospital system using Epic or Oracle Health must make sure it is running its vendor\'s release certified to USCDI v3 — able to send and receive all 94 data elements, including the new Health Insurance Information class and the equity-focused Disability Status element. Certification belongs to the vendor\'s product, but the hospital carries the risk: without CEHRT that meets the updated criteria it cannot satisfy the Promoting Interoperability requirements, exposing it to Medicare payment reductions.']] },
  { id: 'interop-uscdi', key: 'compare-rules', verdict: 'FABRICATED', claim: 'Cures rule "Covered major EHR developers with ≥ 500k patient records"; HTI-1 "Expanded CEHRT scope to more health IT developers" and "Required support for USCDI+ use cases in certain programs"', sources: RULES,
    replaceBlock: { _type: 'comparisonBlock', title: '21st Century Cures Act Final Rule vs. HTI-1 Final Rule',
      left: { label: '21st Century Cures Act Final Rule (2020)', points: ['Established USCDI v1 as baseline for CEHRT', 'Required support for 52 data elements across 16 classes', 'Prohibited information blocking', 'Mandated patient access APIs using FHIR', 'Added an electronic health information (EHI) export criterion'] },
      right: { label: 'HTI-1 Final Rule (2024)', points: ['Upgraded baseline to USCDI v3 (94 elements, 19 classes)', 'Set January 1, 2026 as hard compliance deadline', 'Retired year-named certification editions', 'Added the TEFCA Manner information blocking exception', 'Strengthened algorithmic transparency and AI accountability provisions'] } } },
  { id: 'interop-uscdi', key: 'blk-plus-3', verdict: 'UNVERIFIABLE', claim: '"The first and most prominent USCDI+ domain is USCDI+ Quality, developed jointly by ONC and CMS"', sources: PLUS,
    pairs: [['The first and most prominent USCDI+ domain is USCDI+ Quality, developed jointly by ONC and CMS to support digital quality measurement.', 'The most developed USCDI+ domain is USCDI+ Quality, built by ONC with CMS, CDC, and HRSA to support digital quality measurement.']] },
  { id: 'interop-uscdi', key: 'sg-plus', verdict: 'UNVERIFIABLE', claim: 'stats "13+ USCDI+ use cases", "program launched 2021", "adoption is voluntary"', sources: PLUS,
    replaceBlock: { _type: 'statGrid', stats: [
      { _key: 'plus-s1', label: 'USCDI+ domains listed by ONC', value: '5', context: 'Public Health, Quality, Cancer, Behavioral Health, Maternal Health' },
      { _key: 'plus-s2', label: 'USCDI+ platform launched', value: 'Dec 2023' },
      { _key: 'plus-s3', label: 'USCDI+ operates at sector or program level', value: 'Sector' },
      { _key: 'plus-s4', label: 'USCDI+ Quality partner agencies', value: 'CMS, CDC, HRSA' }] } },
  { id: 'interop-uscdi', key: 'blk-ch-legacy', verdict: 'UNVERIFIABLE', claim: '"ONC data shows that while 86% of non-federal acute care hospitals have adopted a certified EHR, only 67% of psychiatric hospitals have done so"', sources: PSY,
    pairs: [['ONC data shows that while 86% of non-federal acute care hospitals have adopted a certified EHR, only 67% of psychiatric hospitals have done so — a gap that reflects real structural barriers in the certification upgrade pathway.', 'ONC data from 2015 showed 96% of non-federal acute care hospitals using certified EHR technology, while only 15% of psychiatric hospitals had adopted even a basic EHR — a gap rooted in their exclusion from the Meaningful Use incentive payments.']] },
  { id: 'interop-uscdi', key: 'blk-ch-lag', verdict: 'UNVERIFIABLE', claim: '"rulemaking — a process that takes 18-24 months"', sources: 'No source for an 18-24 month rulemaking duration; e.g., USCDI v3 (July 2022) was adopted by HTI-1 (Jan 2024).',
    pairs: [['regulatory baselines are set through formal rulemaking — a process that takes 18-24 months — there is always', 'regulatory baselines are set through formal rulemaking — USCDI v3, published in July 2022, was not adopted until the HTI-1 rule of January 2024 — there is always']] },
  { id: 'interop-uscdi', key: 'takeaway-main', verdict: 'INACCURATE', claim: 'takeaway "USCDI+ ... used in programs like TEFCA"', sources: PLUS,
    pairs: [['used in programs like TEFCA, CDC public health reporting, and CMS quality measurement.', 'used for CDC public health reporting, CMS quality measurement, cancer, behavioral health, and maternal health.']] },
  { id: 'interop-uscdi', key: 'blk-intro-1', verdict: 'INACCURATE', claim: 'fallback: "V2 (2022) added SDOH and health insurance information. V3 (2023) added sexual orientation and gender identity, health status assessments, facility information"; key_stat "USCDI version published in 2024" (v4 = July 2023) and "input through ONC\'s USCDI+ and SVAP"; quiz option years v2 (2022) / v3 (2023)', sources: USV,
    mirrorPairs: [
      ['V2 (2022) added social determinants of health data and health insurance information. V3 (2023) added sexual orientation and gender identity, health status assessments, facility information, and expanded clinical notes.', 'V2 (2021) added sexual orientation and gender identity and social determinants of health data. V3 (2022) added health insurance information, health status assessments, and facility information.'],
      ['USCDI v4 (2024) continued the expansion trajectory, adding behavioral health data elements, additional SDOH data, and expanded patient demographic data. Each annual update reflects stakeholder input through ONC\'s USCDI+ and Standards Version Advancement Process (SVAP).', 'USCDI v4 (July 2023) added 20 data elements and one data class, including alcohol use, substance use, physical activity, and medication adherence. Each annual update reflects stakeholder submissions through ONC\'s ONDEC system.'],
      ['USCDI v3 (2023)', 'USCDI v3 (2022)']],
    mirrorObjects: [{ match: { label: 'USCDI version published in 2024, expanding to include behavioral health and more SDOH data', value: 'v4' }, set: { label: 'USCDI version published in July 2023, adding substance use, physical activity, and medication adherence data', value: 'v4' } }] },
);
OPS.push(
  { id: 'interop-uscdi', key: 'blk-v2', verdict: 'INACCURATE', claim: 'SOGI presented as a current USCDI requirement without noting USCDI v3.1 (June 2025) removed/revised the Sex, Sexual Orientation and Gender Identity elements', sources: 'ISP USCDI Version 3.1 (June 2025): Sex, Sexual Orientation, and Gender Identity data elements removed or updated in Patient Demographics/Information, consistent with Executive Order 14168 (Jan 20, 2025).',
    pairs: [['Sexual Orientation and Gender Identity (SOGI) data elements — long requested by LGBTQ+ health advocates — and', 'Sexual Orientation and Gender Identity (SOGI) data elements — long requested by LGBTQ+ health advocates, and later removed or revised in USCDI v3.1 (June 2025) under Executive Order 14168 — and']] },
);

// ---- Interop: interop-hipaa-security
const SRDATE = '68 FR 8334 (Feb 20, 2003): Security Rule effective April 21, 2003; compliance date April 21, 2005 (April 21, 2006 for small health plans) — 45 CFR 164.318.';
const OCR23 = 'HHS OCR Annual Report to Congress on Breaches of Unsecured PHI for 2023: 732 breaches of 500+ that occurred in 2023, affecting 113,173,613 individuals (average 154,609); hacking/IT 590 breaches (81%) and 108,725,761 individuals (96%); largest 11,270,000 (HCA). HHS OCR press releases (2024): "a 264% increase in large breaches reported to OCR involving ransomware attacks" since 2018.';
const OCR24 = 'HHS OCR Report to Congress on HIPAA compliance for 2024 (HIPAA Journal summary): 22 financial penalties, $9,944,612 collected; 742 reports of 500+ breaches, 663 for incidents occurring in 2024, 242,908,056 individuals; hacking/IT 81% of breaches and 241,582,022 individuals (99.45%). No "fourteen ... cited Security Rule violations" figure in the source. National Law Review (2025): Risk Analysis Initiative launched October 2024 with eight enforcement actions by April 2025; 2016-2017 audit: "only 14 percent ... substantially fulfilling" risk analysis.';
const CUM = 'HIPAA Journal healthcare data breach statistics: October 2009 - April 30, 2026, 7,670 breaches of 500+ reported to OCR affecting 1,013,066,481 individuals (more than 2.9 times the U.S. population); Change Healthcare 192.7 million (HHS breach portal update, July 2025). No source for the "2009-2025: 7,357 breaches / 935 million" snapshot.';
const ELG = 'HHS OCR press release Jan 7, 2025 (HIPAA Journal, Nixon Peabody): $80,000 settlement with Elgon Information Systems, a Massachusetts EMR/billing business associate, after a March 2023 ransomware attack affecting ~31,000 people; OCR\'s 8th ransomware enforcement action and 2nd Risk Analysis Initiative action.';
const NPRMS = 'Federal Register 90 FR 898 (Jan 6, 2025) NPRM; comments closed March 7, 2025; McDermott (2026) / GovInfoSecurity: the 2026 Unified Agenda lists the rule as a long-term action with final action projected for July 2027 (the Sept 2025 agenda had May 2026). The NPRM proposes BAA transition provisions; no "180 days" BAA deadline located.';
const RW = 'HHS OCR 2024 ransomware enforcement press releases: Heritage Valley Health System $950,000; Plastic Surgery Associates of South Dakota $500,000; Cascade Eye and Skin Centers $250,000; Providence Medical Institute $240,000 civil money penalty — separate actions, not a single coordinated four-entity announcement.';
const IBM = 'IBM Cost of a Data Breach Report 2023: healthcare average $10.93M vs global average $4.45M (about 2.5 times).';
OPS.push(
  { id: 'interop-hipaa-security', key: 's1p1', verdict: 'INACCURATE', claim: 'Security Rule "took effect on April 21, 2005" (effective April 21, 2003; compliance April 21, 2005)', sources: SRDATE,
    pairs: [['was published as a final rule in February 2003 and took effect on April 21, 2005 — giving the industry two years to build compliance programs before enforcement began.', 'was published as a final rule in February 2003, took effect that April, and required compliance by April 21, 2005 — giving the industry two years to build compliance programs before enforcement began.']] },
  { id: 'interop-hipaa-security', key: 's2p3', verdict: 'INACCURATE', claim: '"In the fall of 2024, OCR launched a dedicated Risk Analysis Initiative and within six months had announced seven enforcement actions"', sources: OCR24,
    pairs: [['In the fall of 2024, OCR launched a dedicated "Risk Analysis Initiative" and within six months had announced seven enforcement actions — all citing', 'In October 2024, OCR launched a dedicated "Risk Analysis Initiative" and by April 2025 had announced eight enforcement actions — all citing']] },
  { id: 'interop-hipaa-security', key: 's2sg', verdict: 'INACCURATE', claim: 'stat "Risk Analysis Initiative Actions 7 ... in the first six months"', sources: OCR24,
    stats: { __byLabel: { 'Risk Analysis Initiative Actions': { value: '8', context: 'Enforcement actions under OCR\'s Risk Analysis Initiative from its October 2024 launch through April 2025' } } } },
  { id: 'interop-hipaa-security', key: 's2ex', verdict: 'INACCURATE', claim: '"In 2023, OCR investigated Elgon Information Systems ..." (attack March 2023; settlement announced January 2025)', sources: ELG,
    pairs: [['In 2023, OCR investigated Elgon Information Systems and determined that the company had failed to conduct a comprehensive and accurate risk analysis to identify all risks and vulnerabilities to ePHI. The case settled for $80,000 plus a corrective action plan.', 'After a March 2023 ransomware attack on Elgon Information Systems — a Massachusetts business associate providing EMR and billing services, with about 31,000 people affected — OCR found the company had failed to conduct an accurate and thorough risk analysis of the risks and vulnerabilities to ePHI. The case settled in January 2025 for $80,000 plus a corrective action plan, the second action under OCR\'s Risk Analysis Initiative.']] },
  { id: 'interop-hipaa-security', key: 's4p3', verdict: 'INACCURATE', claim: '"the final rule is expected to publish in 2026" (Unified Agenda now projects July 2027)', sources: NPRMS,
    pairs: [['The comment period closed March 7, 2025, and the final rule is expected to publish in 2026, with a 240-day compliance window after publication.', 'The comment period closed March 7, 2025. HHS has not finalized the rule: the 2026 Unified Agenda lists it as a long-term action with final action projected for July 2027. As proposed, organizations would have 240 days after final publication to comply.']] },
  { id: 'interop-hipaa-security', key: 's4steps', verdict: 'UNVERIFIABLE', claim: '"The proposed rule requires BAs to update agreements within 180 days of final rule publication"; title "Preparing for the 2025/2026 Security Rule Changes"', sources: NPRMS,
    pairs: [['The proposed rule requires BAs to update agreements within 180 days of final rule publication — begin identifying and renegotiating contracts now.', 'The proposed rule would require new business associate agreement terms, with a transition period for existing contracts — begin identifying and renegotiating contracts now.'],
      ['Preparing for the 2025/2026 Security Rule Changes', 'Preparing for the Proposed Security Rule Changes']] },
  { id: 'interop-hipaa-security', key: 's5p1', verdict: 'UNVERIFIABLE', claim: '"Between 2009 and 2025, OCR received reports of 7,357 healthcare data breaches ... 935 million Americans"; "In 2023, OCR logged 746 large breaches" (OCR: 732)', sources: CUM + ' | ' + OCR23,
    pairs: [['Between 2009 and 2025, OCR received reports of 7,357 healthcare data breaches affecting 500 or more individuals, collectively exposing the protected health information of more than 935 million Americans — nearly three times the U.S. population, reflecting', 'From October 2009 through April 2026, OCR received reports of 7,670 healthcare data breaches affecting 500 or more individuals, collectively exposing the protected health information of more than 1 billion individuals — more than 2.9 times the U.S. population, reflecting'],
      ['In 2023, OCR logged 746 large breaches affecting an average of 154,609 individuals each.', 'In 2023, OCR logged 732 large breaches affecting an average of 154,609 individuals each.']] },
  { id: 'interop-hipaa-security', key: 's5p2', verdict: 'INACCURATE', claim: '"UnitedHealth Group ultimately disclosed that approximately 190 million Americans" (updated to 192.7 million in July 2025)', sources: CUM,
    pairs: [['UnitedHealth Group ultimately disclosed that approximately 190 million Americans had their personal and healthcare data compromised', 'UnitedHealth Group put the count at about 190 million in January 2025, and the HHS breach portal raised it to 192.7 million in July 2025']] },
  { id: 'interop-hipaa-security', key: 's5p3', verdict: 'INACCURATE', claim: '"fewer large breaches were reported than in 2023 (663 vs. 746, a 9% decrease)" (mixes counts; OCR 2023 = 732); "Fourteen of those actions cited Security Rule violations" (not in source); Risk Analysis Initiative "seven more ... in its first six months"', sources: OCR24 + ' | ' + OCR23,
    pairs: [['while fewer large breaches were reported than in 2023 (663 vs. 746, a 9% decrease), the total number of individuals affected reached 242.9 million', 'large breaches occurring in the year fell to 663 (from 732 in 2023), yet the total number of individuals affected reached 242.9 million'],
      [' Fourteen of those actions cited Security Rule violations, and the Risk Analysis Initiative that launched in late 2024 added seven more enforcement actions in its first six months alone.', ' The Risk Analysis Initiative that launched in October 2024 added eight enforcement actions by April 2025.']] },
  { id: 'interop-hipaa-security', key: 's5sg', verdict: 'UNVERIFIABLE', claim: 'stats "Change Healthcare Victims 190M"; "Total Since 2009 935M+"', sources: CUM,
    stats: { __byLabel: { 'Change Healthcare Victims': { value: '192.7M', context: 'Largest single healthcare data breach in U.S. history — UnitedHealth\'s Change Healthcare, 2024 (HHS breach portal, July 2025)' }, 'Total Since 2009': { value: '1B+', context: 'Individuals affected by breaches of 500+ reported to OCR, October 2009 through April 2026 (7,670 breaches)' } } } },
  { id: 'interop-hipaa-security', key: 's5ex', verdict: 'UNVERIFIABLE', claim: '"In a coordinated enforcement action, OCR announced settlements with four covered entities following ransomware attacks" (no such single announcement located)', sources: RW,
    pairs: [['In a coordinated enforcement action, OCR announced settlements with four covered entities following ransomware attacks, emphasizing that failure to conduct adequate risk analyses and implement appropriate access controls left these organizations vulnerable. The settlements ranged from tens of thousands to hundreds of thousands of dollars and included corrective action plans requiring implementation of the security controls that had been absent before the attacks.', 'Through 2024, OCR closed a run of ransomware investigations — Heritage Valley Health System ($950,000), Plastic Surgery Associates of South Dakota ($500,000), Cascade Eye and Skin Centers ($250,000), and Providence Medical Institute ($240,000 civil money penalty) — repeatedly citing failures to conduct adequate risk analyses and to implement appropriate security controls. Settlements came with corrective action plans requiring the controls that had been absent before the attacks.'],
      ['OCR Settles Four Ransomware Investigations Simultaneously', 'OCR\'s 2024 Run of Ransomware Enforcement Actions']] },
  { id: 'interop-hipaa-security', key: 's6tk', verdict: 'INACCURATE', claim: 'takeaways "effective April 21, 2005"; "Risk Analysis Initiative has generated seven enforcement actions"; "Change Healthcare ... approximately 190 million"; "final 2025/2026 Security Rule"', sources: SRDATE + ' | ' + OCR24 + ' | ' + CUM + ' | ' + NPRMS,
    pairs: [['published February 2003 and effective April 21, 2005, governs', 'published February 2003 with compliance required by April 21, 2005, governs'],
      ["OCR's 2024 Risk Analysis Initiative has generated seven enforcement actions.", "OCR's Risk Analysis Initiative (launched October 2024) generated eight enforcement actions by April 2025."],
      ['the Change Healthcare ransomware attack alone affecting approximately 190 million Americans.', 'the Change Healthcare ransomware attack alone affecting about 192.7 million people.'],
      ['begin preparing for the final 2025/2026 Security Rule now', 'begin preparing for the final Security Rule now (final action projected for July 2027)']] },
  { id: 'interop-hipaa-security', key: 's8s1', verdict: 'INACCURATE', claim: 'source [1] "effective date (April 21, 2005)"', sources: SRDATE,
    pairs: [['Authoritative text of Security Rule effective date (April 21, 2005)', 'Authoritative text of Security Rule compliance date (April 21, 2005)']] },
  { id: 'interop-hipaa-security', key: 's8s2', verdict: 'MISATTRIBUTED', claim: 'source [2] HIPAA Journal 2024 report credited with "663 large breaches ... 242.9 million ... 99.45%" (those are OCR Report to Congress figures; HIPAA Journal reports 725 / 275 million)', sources: OCR24,
    pairs: [['Source for 663 large breaches in 2024, 242.9 million individuals affected, hacking/IT accounting for 99.45% of breached records, and the Change Healthcare 190 million figure.', 'Independent 2024 breach tally (725 breaches, about 275 million records) and the Change Healthcare entry; the 663 / 242.9 million / 99.45% figures in this lesson are from OCR\'s 2024 Report to Congress (source [4]).']] },
  { id: 'interop-hipaa-security', key: 's8s4', verdict: 'INACCURATE', claim: 'source [4] "Risk Analysis Initiative generating seven enforcement actions"', sources: OCR24,
    pairs: [['Source for 22 enforcement actions, $9.94 million in 2024 HIPAA settlements, and the Risk Analysis Initiative generating seven enforcement actions.', 'Source for 22 enforcement actions, $9.94 million in 2024 HIPAA settlements and penalties, and 2024 breach counts (663 incidents, 242.9 million individuals, 99.45% of affected individuals from hacking/IT).']] },
  { id: 'interop-hipaa-security', key: 's8s6', verdict: 'INACCURATE', claim: 'source [6] "seven enforcement actions in first six months"', sources: OCR24,
    pairs: [['seven enforcement actions in first six months', 'eight enforcement actions from October 2024 through April 2025']] },
  { id: 'interop-hipaa-security', key: 's1p2', verdict: 'INACCURATE', claim: 'fallback: summary "the 2024 updates requiring encryption and MFA" (proposed, not in force); callout "HHS proposed ... in 2024"; key_stat context "nearly three times the cross-industry average" (IBM 2023: $10.93M vs $4.45M)', sources: NPRMS + ' | ' + IBM,
    mirrorPairs: [
      ['and the 2024 updates requiring encryption and MFA.', 'and the proposed update (announced December 2024, not yet final) that would require encryption and MFA.'],
      ['HHS proposed significant updates to the HIPAA Security Rule in 2024 — the first major revision since 2013.', 'HHS proposed significant updates to the HIPAA Security Rule in December 2024 (published January 6, 2025) — the first major revision since 2013. As of 2026 the rule is not final; final action is projected for July 2027.'],
      ['2024 HIPAA Security Rule update: mandatory encryption and MFA', 'Proposed HIPAA Security Rule update: mandatory encryption and MFA'],
      ['$10.9 million per breach in 2023, nearly three times the cross-industry average.', '$10.93 million per breach in 2023, about two and a half times the cross-industry average of $4.45 million (IBM).']] },
);

// ---- Interop: interop-data-governance
const ROA = 'HHS OCR press release (Mar 6, 2025): $200,000 CMP against OHSU — OCR\'s 53rd Right of Access enforcement action (initiative launched 2019). No source located for "45+ states have medical records statutes".';
const QHINS = 'HHS press release Feb 12, 2024 (seven QHINs incl. Epic Nexus, CommonWell, eHealth Exchange, Health Gorilla, KONZA, MedAllies, Kno2); RCE: eClinicalWorks Jan 2025, Surescripts Apr 2025, Netsmart Aug 2025, Oracle Health Information Network Nov 2025 — 11 QHINs. Epic\'s QHIN is Epic Nexus; Carequality is a separate Sequoia Project framework. RCE "Exchange Purposes Explained": six purposes incl. Individual Access Services.';
const CA = 'Common Agreement v2.1 published in the Federal Register Nov 26, 2024; FHIR-based exchange support was introduced in Common Agreement v2.0 (released April 22, 2024; ExecutiveGov Apr 2024). Sequoia Project RCE contract 75P00123C00019, August 2023, five years.';
const NPI = 'HIPAA (1996) directed HHS to adopt a unique health identifier; since FY1999 (rider first enacted 1998, Rep. Ron Paul) the Labor-HHS appropriations rider, now Section 510, bars HHS from spending funds to promulgate or adopt one (AMIA / Patient ID Now letters; SC Media).';
const DIR = 'CMS Medicare Advantage Online Provider Directory Review reports: Round 1 (2016) 45.1%, Round 2 (2017) 52.2%, Round 3 (2017-18) 48.74% of listed provider locations had at least one inaccuracy.';
OPS.push(
  { id: 'interop-data-governance', key: 's1sg1', verdict: 'UNVERIFIABLE', claim: 'stat "Have Medical Records Statutes 45+ states"', sources: ROA,
    stats: { __byLabel: { 'Have Medical Records Statutes': { label: 'OCR Right of Access enforcement actions', value: '53', context: 'Since the 2019 Right of Access Initiative; the 53rd was a $200,000 penalty against OHSU announced in March 2025' } } } },
  { id: 'interop-data-governance', key: 's3p3', verdict: 'UNVERIFIABLE', claim: '"Duplicate or overlaid medical records are classified as a type of healthcare-acquired patient safety event"', sources: 'No classification source located; ECRI Institute has named patient misidentification among its top ten patient safety threats (AMIA / Patient ID Now coalition letters).',
    pairs: [['Duplicate or overlaid medical records are classified as a type of healthcare-acquired patient safety event.', 'Duplicate or overlaid medical records put the wrong history in front of clinicians, and ECRI has named patient misidentification among its top ten patient safety threats.']] },
  { id: 'interop-data-governance', key: 's4p3', verdict: 'INACCURATE', claim: 'QHIN list includes "Epic\'s Carequality network" (Epic\'s QHIN is Epic Nexus); exchange purposes omit Individual Access Services ("a small set of other permitted purposes")', sources: QHINS,
    pairs: [["including CommonWell Health Alliance, eHealth Exchange, Epic's Carequality network, Kno2, MedAllies,", 'including CommonWell Health Alliance, eHealth Exchange, Epic Nexus, Health Gorilla, KONZA, Kno2, MedAllies,'],
      ['individual treatment, payment, health care operations, public health, benefits determination, and a small set of other permitted purposes.', 'treatment, payment, health care operations, public health, government benefits determination, and individual access services.']] },
  { id: 'interop-data-governance', key: 's4sg1', verdict: 'INACCURATE', claim: 'stat context "Common Agreement v2.1 ... adds FHIR-based exchange as a major new capability" (FHIR came in v2.0)', sources: CA,
    stats: { __byLabel: { 'Current Common Agreement Version': { context: 'Published November 2024; builds on v2.0 (April 2024), which added FHIR-based exchange' } } } },
  { id: 'interop-data-governance', key: 'tkwy1', verdict: 'INACCURATE', claim: 'takeaway: "The DAMA-DMBOK ... and AHIMA\'s IGPHC framework define the three core governance roles" (IGPHC sets eight principles, not the roles)', sources: 'AHIMA IGPHC: eight principles (accountability, transparency, integrity, protection, compliance, availability, retention, disposition); the owner/steward/custodian roles are credited to DAMA-DMBOK in the lesson body.',
    pairs: [["The DAMA-DMBOK (currently v2, with v3 in development) and AHIMA's IGPHC framework define the three core governance roles: data owner (accountability), data steward (operations), and data custodian (technical infrastructure).", "The DAMA-DMBOK (currently v2, with v3 in development) defines the three core governance roles — data owner (accountability), data steward (operations), and data custodian (technical infrastructure) — while AHIMA's IGPHC sets eight enterprise-wide governance principles."]] },
  { id: 'interop-data-governance', key: 's1p1', verdict: 'INACCURATE', claim: 'fallback: "Congress prohibited HHS from creating one in the HIPAA era" (HIPAA mandated an identifier; an appropriations rider since 1998 blocks funding); key_stat "30-50% of provider directory entries are inaccurate ... Studies consistently find 30-50%"; "CommonWell" as a commercial vendor-operated network (it is a not-for-profit alliance)', sources: NPI + ' | ' + DIR,
    mirrorPairs: [
      ['The US has no universal patient identifier — a deliberate policy choice made in the HIPAA era when Congress prohibited HHS from creating one, citing privacy concerns.', 'The US has no universal patient identifier. HIPAA (1996) actually directed HHS to adopt one, but since 1998 an annual appropriations rider has barred HHS from spending funds to do so, citing privacy concerns.'],
      ['Congress prohibited HHS from creating one in the HIPAA era, citing privacy concerns about a universal health ID', 'Since 1998 an annual appropriations rider has barred HHS from funding one, citing privacy concerns about a universal health ID'],
      ['CommonWell, some regional networks', 'Surescripts, some regional networks'],
      ['Studies consistently find 30-50% error rates in payer provider directories, undermining', "CMS's three Medicare Advantage directory reviews (2016–2018) found 45–52% of listed provider locations had at least one inaccuracy, undermining"]],
    mirrorObjects: [{ match: { label: 'of provider directory entries are inaccurate in payer systems', value: '30-50%' }, set: { label: 'of Medicare Advantage directory locations had at least one inaccuracy (CMS reviews)', value: '45-52%' } }] },
);
