// Phase 7b source-integrity corrections (non-VBC Academy lessons). Each op targets one Sanity academyModule
// body block by _key. `pairs` are exact substring replacements inside that block's strings (each `old` must
// occur exactly once in the block, or be already replaced); `stats` replaces whole statGrid stat fields by stat _key.
// Every finding (claim, verdict, sources) is logged in docs/audits/phase7b_sources_2026-10.jsonl.

const SH = 'Shrank et al. (JAMA, 2019)';

export const OPS = [
  // ---------------- aiml-llm-clinical
  { id: 'aiml-llm-clinical', key: 's1stats', stats: {
      s1: { context: 'Nori and colleagues (Microsoft, 2023) found GPT-4 exceeded the USMLE passing score by more than 20 points without any medical fine-tuning or specialized prompting.',
            label: 'GPT-4 Margin Above USMLE Passing Score (Nori et al., Microsoft 2023)', value: '20+ pts' },
      s4: { context: 'A study of 263 clinicians across 6 US health systems using the Abridge ambient AI scribe found burnout fell from 51.9% to 38.8% (13.1 percentage points) and severe burnout fell 6.2 percentage points after 30 days.',
            label: 'Burnout Reduction with Ambient AI Scribe (JAMA Network Open, 2025)', value: '13.1pp' } },
    pairs: [['Med-PaLM 2 Accuracy on MedQA (Nature Medicine, 2024)', 'Med-PaLM 2 Accuracy on MedQA (Nature Medicine, 2025)']] },
  { id: 'aiml-llm-clinical', key: 'takeaways', pairs: [
      ['GPT-4 at approximately the 90th percentile on USMLE (Nori et al., Microsoft 2023) and Med-PaLM 2 at 86.5% accuracy on MedQA (Nature Medicine, 2024)',
       'GPT-4 exceeding the USMLE passing score by more than 20 points (Nori et al., Microsoft 2023) and Med-PaLM 2 at 86.5% accuracy on MedQA (Nature Medicine, 2025)'],
      ['A JAMA Network Open 2024 study of 186 clinicians across 6 health systems found a net 13.9 percentage-point reduction in burnout after one month of using the Abridge ambient AI scribe, with significant reductions in after-hours documentation time.',
       'A JAMA Network Open 2025 study of 263 clinicians across 6 health systems found burnout fell from 51.9% to 38.8% after 30 days of using the Abridge ambient AI scribe, with less after-hours documentation time.']] },
  { id: 'aiml-llm-clinical', key: 's1p3', pairs: [['the follow-on Med-PaLM 2 paper in Nature Medicine (2024)', 'the follow-on Med-PaLM 2 paper in Nature Medicine (2025)']] },
  { id: 'aiml-llm-clinical', key: 's2p2', pairs: [
      ['A Microsoft survey of 879 clinicians in 2024 found an average of 5 minutes saved per encounter; other implementations have reported up to 50% reductions in documentation time, with some institutions reporting 7 minutes saved per visit. Nuance\'s own data showed a 70% reduction in feelings of burnout and fatigue among DAX users.',
       'Microsoft reports that clinicians using DAX Copilot save an average of five minutes per encounter and that 70% of clinicians report reduced feelings of burnout and fatigue — vendor-reported figures that independent evaluations are still testing.']] },
  { id: 'aiml-llm-clinical', key: 's2example', pairs: [
      ['MUSC Health reported a 20% reduction in documentation time following DAX Copilot adoption.',
       'MUSC Health reported that providers who used DAX Copilot for five months saw a 20% decrease in time spent charting outside of work hours.']] },

  // ---------------- aiml-change-management
  { id: 'aiml-change-management', key: 's1p1', pairs: [
      ['A widely cited analysis drawing on data from RAND Corporation and McKinsey found that nearly 79 percent of healthcare AI initiatives fail to deliver their intended value.',
       'A 2024 RAND Corporation study, based on interviews with experienced data scientists and engineers, found that more than 80 percent of AI projects across industries fail — twice the failure rate of IT projects that do not involve AI.']] },
  { id: 'aiml-change-management', key: 's2p1', pairs: [
      ['No single factor predicts AI implementation success more reliably than the presence of engaged clinical champions. A 2022 systematic review published in Implementation Science Communications screened over 7,500 records and synthesized 35 studies on champion effectiveness across healthcare innovation deployments. The review found that champions serve as promoters and cultural translators — bridging the language gap between technology teams and frontline clinicians, and lending social credibility to tools that might otherwise be viewed with suspicion. The most effective champions shared a specific profile: they were respected peers at the clinical level, possessed genuine subject-matter expertise, and carried formal backing from executive leadership.',
       'Clinical champions are one of the most widely used implementation strategies, and the evidence for them is encouraging but thinner than their popularity suggests. A 2022 systematic review published in Implementation Science Communications screened 7,566 records and included 35 quantitative studies of champions in health care. In a subset of seven studies, five found that exposure to champions was associated with increased organizational use of best practices, programs, or technologies; evidence on use by individual clinicians and patients, and on outcomes, was mixed or scarce. The practical lesson for AI deployment: appoint champions, but define what they do and evaluate whether it works.']] },
  { id: 'aiml-change-management', key: 's2ex', pairs: [
      ['During EHR-based predictive model deployments studied in a 2020 PMC systematic review, 22 of 32 studies (69%) that included structured clinical engagement demonstrated improvement in patient outcomes after model implementation. Systems that lacked designated clinical advocates showed consistently lower adoption rates and higher rates of alert fatigue — clinicians learned to dismiss AI outputs reflexively rather than engage with them thoughtfully.',
       'A 2020 systematic review of predictive models embedded in EHRs (Lee et al., Informatics) found that of 32 implementations that reported effects on clinical outcomes, 22 (69%) showed improvement after the model went live. The barriers the review catalogued — alert fatigue, lack of training, and added workload for the care team — are exactly the problems a clinical champion exists to surface and manage.']] },
  { id: 'aiml-change-management', key: 's3p3', pairs: [
      ['A 2022 PubMed-indexed study applying FMEA to an automated clinical contouring and treatment planning tool identified 126 distinct workflow errors — the leading categories were automation bias, operator error, and software error — none of which would have been visible without prospective analysis.',
       'A 2019 FMEA of the Radiation Planning Assistant, an automated contouring and treatment-planning tool, identified 290 failure modes, 126 of them unique to the automated workflow; the ten highest-risk failure modes were driven by automation bias, operator error, and software error — none of which would have been visible without prospective analysis.']] },
  { id: 'aiml-change-management', key: 's5p2', pairs: [
      ['The AHRQ 2018 Patient Safety Survey found that 47 percent of respondents felt that unsafe event reports were held against them,',
       'In AHRQ\'s 2018 Hospital Survey on Patient Safety Culture database, covering 630 hospitals, "nonpunitive response to error" was the lowest-scoring dimension — only 47 percent responded positively, meaning roughly half of staff feel their mistakes and event reports are held against them —']] },
  { id: 'aiml-change-management', key: 's5sg', stats: {
      s1: { context: 'AHRQ Hospital Survey on Patient Safety Culture, 2018 database (lowest-scoring dimension)', label: 'Staff responding positively on "nonpunitive response to error"', value: '47%' },
      s3: { context: 'Lee et al., Informatics, 2020 — 22 of 32 EHR-embedded predictive models that reported clinical outcomes', label: 'of EHR-embedded predictive models showed improved outcomes', value: '69%' } } },

  // ---------------- aiml-clinical-decision-support
  { id: 'aiml-clinical-decision-support', key: 's2p2', pairs: [['A 2024 meta-analysis of randomized controlled trials found', 'A 2025 meta-analysis of randomized controlled trials found']] },

  // ---------------- aiml-deterioration-models
  { id: 'aiml-deterioration-models', key: 's4p2', pairs: [
      ['A 2017 BMC Medical Informatics study found that if a clinician overrode an alert the first time, subsequent identical alerts for the same patient were overridden at a rate of 87.9%.',
       'A 2017 study in BMC Medical Informatics and Decision Making found that the likelihood of a clinician accepting a reminder fell by 30% for each additional reminder in an encounter, and by 10% for each 5-point rise in the share of reminders that were repeats for the same patient.']] },
  { id: 'aiml-deterioration-models', key: 's5ex', pairs: [
      ['The prospective feasibility study by Churpek et al., published in CHEST (2016),', 'The prospective feasibility study by Kang, Churpek and colleagues, published in Critical Care Medicine (2016),'],
      ['In the subsequent Australian validation across 107,000+ patients, eCART (AUROC 0.801) consistently outperformed NEWS (0.718) and MEWS (0.698) on the same composite outcome',
       'In a subsequent comparison across 107,868 admissions at five U.S. hospitals (Green et al., Resuscitation, 2018), eCART (AUROC 0.801) outperformed NEWS (0.718), MEWS (0.698), and Australia\'s Between the Flags criteria (0.663) on the same composite outcome']] },

  // ---------------- aiml-fda-cleared-cases
  { id: 'aiml-fda-cleared-cases', key: 's5p2', pairs: [
      ['However, a 2024 scoping review published in npj Digital Medicine examined 903 FDA-cleared AI-enabled medical devices and found that only 55.9 percent had publicly available clinical performance data at the time of their clearance. Only 9.0 percent of cleared devices included a prospective post-market surveillance plan. Only 1.9 percent provided a link to a peer-reviewed scientific publication with full safety and efficacy data.',
       'However, a 2025 cross-sectional study in JAMA Network Open examined all 903 AI-enabled medical devices on the FDA\'s list as of August 2024 and found that clinical performance studies were reported for only 505 (55.9 percent); 218 (24.1 percent) explicitly stated that no performance study was conducted. Of the studies reported, only 8.1 percent were prospective and 2.4 percent randomized.']] },
  { id: 'aiml-fda-cleared-cases', key: 's5sg', stats: {
      s1: { context: 'Windecker et al., JAMA Network Open 2025 — all 903 FDA-listed AI devices as of Aug 2024', label: 'Cleared AI devices reporting a clinical performance study', value: '55.9%' },
      s2: { context: 'Windecker et al., JAMA Network Open 2025 — most evidence is retrospective', label: 'Reported performance studies that were prospective', value: '8.1%' } } },

  // ---------------- interop
  { id: 'interop-hie-models', key: 's5p3', pairs: [
      ['A 2025 global FHIR adoption survey found that 71 percent of respondents reported FHIR actively used in their country, up from 66 percent in 2024, and 78 percent of countries with electronic health data exchange regulations now mandate or advise FHIR.',
       'The 2025 State of FHIR survey by HL7 International and Firely, with respondents from 57 countries, found that 71 percent reported FHIR already in use for at least a few use cases in their country, and that FHIR is mandated or recommended in 73 percent of countries with health data regulation.']] },
  { id: 'interop-vermont-vitl', key: 's2_p5', pairs: [["Under Beth Anderson's leadership as CEO (2020-2025)", "Under Beth Anderson's leadership as CEO (2019-2025)"]] },
  { id: 'interop-vermont-vitl', key: 's5_p6', pairs: [
      ["The 2025 VITL Annual Report (submitted to the Vermont Legislature in January 2026) noted that the VITL team spent the end of 2025 mapping a new strategic future — exploring new technologies and interoperability approaches to meet the health system's evolving needs in 2026 and beyond. With a new CEO in place following Beth Anderson's departure in July 2025,",
       "With Randy Farmer — previously chief operating officer of the Delaware Health Information Network — in place as president and CEO since December 2025, following Beth Anderson's departure in July 2025,"]] },
  { id: 'interop-ehr-burden', key: 's1p2', pairs: [
      ['A 2024 study published in the Annals of Family Medicine found that for every 8 hours of scheduled patient visits, primary care physicians logged 5.3 additional hours in the EHR — 2.1 of those hours devoted exclusively to clinical documentation.',
       'A 2024 study of 141 academic primary care physicians, published in the Annals of Family Medicine, found that their EHR time per 8 hours of scheduled appointments kept rising after the pandemic — up 28.4 minutes (7.8%) between 2019–20 and 2022–23, driven by order entry (+58.9%) and the inbox (+24.4%).']] },
  // AMA names its surveys by fielding year: the 2024 survey (fielded Dec 2024, 1,000 physicians) = 39 PAs/week, 13 hrs,
  // 89% burnout, 29% serious adverse event; the 2023 survey (fielded Dec 2023) = 94% delays, 78% abandonment, 24% / 19% / 13% / 7%.
  { id: 'interop-ehr-burden', key: 'qz1', pairs: [
      ['The 2024 AMA survey of 1,000 practicing physicians found that approximately 24 percent — nearly one in four — reported',
       'The 2024 AMA survey of 1,000 practicing physicians (fielded December 2024) found that 29 percent — more than one in four — reported'],
      ['19% cited delays causing hospitalization, 13% identified life-threatening events, and 7% reported disability or death as downstream consequences of authorization delays.',
       'In the AMA\'s previous survey, fielded a year earlier, the share was 24 percent — the problem is growing, not shrinking.'],
      ['About 24% — nearly one in four physicians have seen serious patient harm from prior auth delays', 'About 29% — more than one in four physicians have seen serious patient harm from prior auth delays']] },
  { id: 'interop-ehr-burden', key: 'tkwy', pairs: [['94% of physicians say it causes burnout, and 24% report it has led to serious patient harm.', '89% of physicians say it contributes to burnout, and 29% report it has led to serious patient harm.']] },
  { id: 'interop-ehr-burden', key: 's3sg', stats: { __byLabel: {
      'Physicians: prior auth causes burnout': { context: 'AMA 2024 prior authorization physician survey (fielded December 2024): somewhat or significantly contributes to burnout', label: 'Physicians: prior auth contributes to burnout', value: '89%' },
      'Physicians: prior auth caused serious harm': { context: 'Serious adverse event such as hospitalization or permanent bodily damage (AMA 2024 survey, fielded December 2024)', value: '29%' } } } },
  { id: 'interop-ehr-burden', key: 's3p2', pairs: [
      ['94 percent of physicians in the 2024 AMA survey reported that prior authorization contributes to physician burnout.',
       '89 percent of physicians in the AMA\'s 2024 survey (fielded December 2024) reported that prior authorization somewhat or significantly contributes to physician burnout.']] },
  { id: 'interop-ehr-burden', key: 's3p3', pairs: [
      ['According to the 2024 AMA survey, 93 percent of physicians reported that prior authorization causes care delays, with more than half saying delays occur "always" or "often."',
       'According to the AMA\'s 2023 survey (fielded December 2023), 94 percent of physicians reported that prior authorization delays patients\' access to care.'],
      ['as downstream consequences of authorization delays.', 'as downstream consequences of authorization delays. In the AMA\'s 2024 survey, the share reporting a serious adverse event rose to 29 percent.']] },
  { id: 'interop-ehr-burden', key: 'src2', pairs: [
      ['94% burnout link, and 24% serious adverse events.', '89% burnout link, and 29% serious adverse events (2024 survey, fielded December 2024).']] },
  { id: 'interop-why-it-matters', key: 's1sg', stats: { __byLabel: { 'Redundant Testing Waste Per Year': {
      context: 'Among 85 patients transferred between two hospitals with incompatible EHRs, 32% had a test repeated within 12 hours and 20% at least one duplicate that was not clinically indicated (Stewart et al., JAMIA, 2010)',
      label: 'Transferred Patients With Duplicate Tests Within 12 Hours', value: '32%' } } } },
  { id: 'interop-why-it-matters', key: 's2p3', pairs: [
      ['A landmark study published in BMC Medical Informatics found that duplication of testing',
       'A study of 85 patients transferred between two hospitals with incompatible EHRs, published in the Journal of the American Medical Informatics Association in 2010, found that duplication of testing'],
      [' Across the system, redundant testing alone is estimated to waste up to $5 billion annually in the United States.', '']] },
  { id: 'interop-why-it-matters', key: 's2hl', pairs: [
      ['Duplicate and redundant medical testing — driven largely by inaccessible prior records — wastes an estimated $5 billion per year in the United States, according to research published in BMC Medical Informatics and affiliated studies.',
       'Duplicate testing follows inaccessible records: when two hospitals\' EHRs could not exchange data, nearly one in three transferred patients had a test repeated within 12 hours (Stewart et al., JAMIA, 2010).']] },
  { id: 'interop-why-it-matters', key: 's8tk', pairs: [
      [', with redundant testing alone costing up to $5 billion per year in the United States.', ', and duplicate testing rises when records cannot follow the patient across incompatible EHRs.']] },
  { id: 'interop-why-it-matters', key: 's8qz', pairs: [
      [', while $5 billion estimates annual duplicate testing waste and $42 billion is the WHO\'s estimate of global annual medication error costs.',
       '; $42 billion is the WHO\'s estimate of global annual medication error costs, and $5 billion does not come from the CAQH Index.']] },
  { id: 'interop-why-it-matters', key: 's9s3', pairs: [
      ['Vest JR, Kern LM, Silver MD, Kaushal R. "The Potential For Increased Use Of Health Information Exchange To Reduce Costs And Improve Quality." Health Affairs.',
       'Chen M, Guo S, Tan X. "Does Health Information Exchange Improve Patient Outcomes? Empirical Evidence From Florida Hospitals." Health Affairs, 2019;38(2):197-204.']] },
  { id: 'interop-why-it-matters', key: 's9s5', pairs: [
      ['van Walraven C, Rokosh E. "What is necessary for high-quality discharge summaries?" American Journal of Medical Quality. PMC preliminary look at duplicate testing:',
       'Stewart BA, Fernandes S, Rodriguez-Huertas E, Landzberg M. "A preliminary look at duplicate testing associated with lack of electronic health record interoperability for transferred patients." Journal of the American Medical Informatics Association, 2010.']] },
  { id: 'interop-davinci-gravity', key: 's3example', pairs: [['At HIMSS 2025, MultiCare', 'At HIMSS23, MultiCare']] },
  { id: 'hie-21st-century-cures', key: 's5ex', pairs: [
      ['Epic Systems — the largest EHR vendor in the United States, used by roughly 35% of U.S. hospitals — built its "App Orchard" ecosystem directly in response to the Cures Act interoperability mandates. App Orchard is a marketplace where third-party developers publish SMART on FHIR applications that connect to Epic\'s FHIR R4 API.',
       'Epic Systems — the largest EHR vendor in the United States, used by about 42% of U.S. acute care hospitals at the end of 2024 (KLAS) — had launched its App Orchard developer marketplace in 2015, before the Cures Act was passed, and replaced it with Connection Hub and the Epic Showroom in 2022–2023. What the Cures Act changed was the floor: ONC\'s 2020 rule required certified EHRs to expose a standardized FHIR R4 API that third-party SMART on FHIR applications can connect to.'],
      ['Patients at Epic-using hospitals can authorize any App Orchard application — or any SMART on FHIR app they choose —', 'Patients at Epic-using hospitals can authorize any SMART on FHIR app they choose'],
      ["Epic's App Orchard and SMART on FHIR: A Cures Act Response", 'Epic and SMART on FHIR: What the Cures Act Changed']] },

  // ---------------- readmissions, quality, payment
  { id: 'aiml-readmission-prediction', key: 's1p3', pairs: [
      ['According to CMS projections for fiscal year 2026, the HRRP penalty is estimated to affect approximately 82.8 percent of all eligible hospitals — roughly 2,828 hospitals — making it one of the most broadly applied financial penalties in Medicare.',
       'Preliminary CMS data for fiscal year 2026 show only 641 hospitals (21.8 percent) escaping a penalty — so about 78 percent of evaluated hospitals are penalized, and 240 (8.1 percent) face reductions of 1 percent or more — making it one of the most broadly applied financial penalties in Medicare.']] },
  { id: 'aiml-readmission-prediction', key: 's5sg2', stats: { __byLabel: { 'Hospitals Penalized Under HRRP (FY2026)': {
      context: 'Preliminary CMS FY2026 data: only 641 hospitals (21.8%) avoid a penalty; 240 (8.1%) face cuts of 1% or more', value: '~78%' } } } },
  { id: 'social-risk-adjustment', key: 's2ex1', pairs: [
      ['The Hospital Readmissions Reduction Program (HRRP), established by the ACA in 2012,', 'The Hospital Readmissions Reduction Program (HRRP), created by the ACA in 2010 with penalties beginning in fiscal year 2013,'],
      ["A 2016 Health Affairs analysis found that safety-net hospitals were three times more likely to receive the maximum readmission penalty than non-safety-net hospitals, despite evidence that their readmission rates were largely driven by patients' social circumstances rather than poor hospital care. Congress partially addressed this in the Consolidated Appropriations Act of 2021, which created a peer-grouping system",
       "Critics argued that much of the gap reflected patients' social circumstances rather than poor hospital care. Congress partially addressed this in the 21st Century Cures Act of 2016, which required a peer-grouping system — applied from fiscal year 2019 —"]] },
  { id: 'fee-for-service-origins', key: 's2p2', pairs: [['A survey published in JAMA Internal Medicine found that physicians themselves reported', 'A 2017 survey of 2,106 physicians published in PLOS ONE found that physicians themselves reported']] },
  { id: 'bundled-payment-evidence', key: 's2sg1', stats: { __byLabel: {
      'Avg. Per-Episode Cost Reduction': { context: 'Hip and knee replacement under BPCI Model 2 — Dummit et al., JAMA 2016' },
      'CJR Mandatory Model Savings': { context: 'Net Medicare savings from Comprehensive Care for Joint Replacement, performance years 2016–2018, after reconciliation payments — CMS third annual evaluation', value: '$61.6M' },
      'Patient Satisfaction (CJR)': { context: 'CMS evaluation: CJR and control patients reported similar satisfaction with recovery and care management', label: 'Patient Satisfaction (CJR vs. control)', value: 'Similar' },
      'Lower Medical Costs vs. FFS': { context: 'Gross reduction in CJR episode payments, PY2016–2018, before $90.5M in reconciliation payments — CMS third annual evaluation', label: 'CJR Gross Medicare Savings', value: '$152.1M' } } } },
  { id: 'bundled-payment-evidence', key: 's3p1', pairs: [
      ['A rigorous study published in JAMA Internal Medicine evaluating BPCI Model 2 participation for heart failure', 'A 2024 study published in JAMA Cardiology evaluating BPCI Model 2 participation for heart failure (18 BPCI hospitals versus 211 comparison hospitals)'],
      ['In other words, the bundle had no detectable effect on either cost or quality for this high-volume condition.', 'In other words, the bundle had no detectable effect on quality or outcomes for this high-volume condition.']] },
  { id: 'bundled-payment-evidence', key: 's3ex1', pairs: [['A study published in early 2024 analyzing BPCI participation', 'A study published in JAMA Cardiology in early 2024 analyzing BPCI participation']] },
  { id: 'bundled-payment-mechanics', key: 's4ex1', pairs: [
      ['found that per-episode spending declined on average by $1,014 — approximately a 4% reduction — by Model Year 5, while the model as a whole saved Medicare',
       'are a large part of why the model as a whole saved Medicare']] },
  { id: 'bundled-payments-and-innovation', key: 's5p1', pairs: [
      ['found that only six produced statistically significant savings — and none exceeded about $220 million in annual savings. Factoring in CMMI’s operating budget, its net budgetary impact has been only marginally negative.',
       'found that only six of the 49 models it examined produced statistically significant savings, and that over 2011–2020 CMMI increased federal direct spending by about $5.4 billion — roughly 0.1 percent of net Medicare spending — once its operating costs were counted.']] },
  { id: 'chargemaster-gross-net-revenue', key: 's4ex1', pairs: [
      ['— yet CMS had fined only 18 hospitals nationwide.', '— yet by September 2024 CMS had issued only 14 civil monetary penalties nationwide, totaling about $4 million.']] },
  { id: 'aiml-population-health-ai', key: 's3ex', pairs: [
      ['A 12-provider rural ACO', 'Consider a hypothetical illustration: a 12-provider rural ACO'],
      ['A Regional ACO Closes Diabetic Retinal Exam Gaps', 'Illustrative Scenario: A Regional ACO Closes Diabetic Retinal Exam Gaps']] },

  // ---------------- Five Pillars course
  { id: 'academyModule-five-pillars-apm-readiness-vbc-financial-modeling', key: 'dcdf27455202', pairs: [
      ["Vermont's critical access hospitals carry an average 12% HCC coding gap, according to a 2025 Rural Health Redesign Center assessment -- real revenue and accuracy left on the table simply because documentation does not capture patients' actual complexity.",
       "Every uncoded condition is real revenue and accuracy left on the table simply because documentation does not capture patients' actual complexity."]] },
  { id: 'academyModule-five-pillars-knowledge-infrastructure-technical-assistance', key: '1362965736bb', removeStats: ['9659c63ce567'] },
  { id: 'academyModule-five-pillars-workforce-as-the-binding-constraint', key: '29c7bd6054a2', stats: {
      '771b1576790f': { context: 'Source: HTR book, operations metrics framework (a proposed target, not an AHS figure)', label: 'Target range for travel nursing as a share of total hospital labour cost in the HTR operations metrics framework' } } },
  { id: 'academyModule-five-pillars-voluntary-vs-mandatory-architecture', key: '34111ebafa9e', pairs: [
      ['found the plan saved $47.8 million in the two years after implementation.', 'found the plan saved an estimated $47.8 million in inpatient and outpatient costs over its first three years, state fiscal years 2017 through 2019.']] },

  // ---------------- Precision medicine course
  { id: 'academyModule-precision-medicine-m1', key: 'ae7statgrid3', stats: {
      ae7sg3s1: { context: 'Illness and death from non-optimized medication therapy cost an estimated $528.4 billion in 2016 — about 16% of US health spending. Genetic variation in drug response is one contributor pharmacogenomics can address. Source: Watanabe, McInnis & Hirsch, Annals of Pharmacotherapy, 2018.',
                  label: 'Estimated annual US cost of non-optimized medication therapy (2016)' } }, statsByIndex: { 2: {
                  context: 'Roughly 75,000 genetic tests were on the US market, with about ten new tests entering every day. Source: Phillips et al., Health Affairs, 2018.',
                  label: 'Genetic tests on the US market', value: '~75,000' } } },
  { id: 'academyModule-precision-medicine-m1', key: 'ae6example2', pairs: [
      ['managed care for approximately 190,000 Vermonters until both the model and OneCare wound down at the end of 2025.', 'coordinated care for Vermonters attributed through Medicare, Medicaid, and commercial payers until both the model and OneCare wound down at the end of 2025.'],
      ['OneCare Vermont 2025 Annual Report; Vermont Health Information Exchange overview.', 'OneCare Vermont wind-down announcement (November 2024), reported by VTDigger; Vermont Health Information Exchange overview.']] },
  { id: 'academyModule-precision-medicine-m1', key: 'ad4example1', pairs: [
      ['Among patients with actionable CYP2C19 variants, the program increased prescribing of alternative antiplatelet agents from 4.5% to 72.9%, demonstrating that pre-emptive genotyping with EHR integration can successfully redirect prescribing before harm occurs.',
       'Among 2,676 genotyped patients, 514 (19.2%) carried a CYP2C19 variant affecting clopidogrel; within 12 months, 57.6% of poor metabolizers and 33.2% of intermediate metabolizers had been switched to an alternative antiplatelet drug, and genotype was the strongest predictor of switching — showing that pre-emptive genotyping with EHR integration can redirect prescribing before harm occurs.'],
      ['Pulley et al., Clinical Pharmacology & Therapeutics, 2012; Vanderbilt PREDICT Program reports.', 'Pulley et al., Clinical Pharmacology & Therapeutics, 2012; Peterson et al., Clinical Pharmacology & Therapeutics, 2016.']] },
  { id: 'academyModule-precision-medicine-m3-economics', key: 'm3sg0003', stats: {
      m3st0007: { context: `${SH} estimated $760B–$935B in annual waste — about a quarter of US health spending — including $102B–$166B from failures of care delivery and $27B–$78B from failures of care coordination, the domains precision medicine can address.`,
                  label: 'Annual waste in U.S. healthcare (2019 estimate)', value: '$760B–$935B' },
      m3st0008: { context: `The same analysis put overtreatment and low-value care — including treatments that do not work for the patient receiving them — at $75.7B–$101.2B a year. (${SH})`,
                  label: 'Annual cost of overtreatment and low-value care', value: '$76B–$101B' },
      m3st0009: { context: 'Average insurer-allowed costs in the year after diagnosis were $82,121 for stage I/II breast cancer versus $134,682 for stage IV, making early detection an economic as well as clinical imperative. (Blumen et al., American Health & Drug Benefits, 2016)',
                  label: 'Cost differential: Stage I/II vs. Stage IV breast cancer treatment', value: '1.6x' } } },
  { id: 'academyModule-precision-medicine-m4-technology', key: 'm4ex0001', pairs: [
      ['Ambry Genetics, a major clinical genomics laboratory, published a landmark study tracking the reclassification of VUSs in hereditary cancer genes (BRCA1, BRCA2, and others) over a 5-year period. Of VUSs identified between 2012–2017, approximately 38% were subsequently reclassified — and the vast majority were reclassified as benign or likely benign rather than pathogenic.',
       'Mersch and colleagues examined hereditary cancer testing of 1.45 million people at a single large commercial laboratory between 2006 and 2016. Of 26,670 unique variants of uncertain significance, 7.7% were reclassified during follow-up — and 91.2% of those were downgraded to benign or likely benign rather than upgraded to pathogenic. Because many VUSs recur across patients, 24.9% of all VUS results reported to individuals were eventually reclassified.'],
      ['Ambry Genetics: Tracking VUS Reclassification Over Time', 'Tracking VUS Reclassification Over Time']] },
  { id: 'academyModule-precision-medicine-m4-technology', key: 'm4ex0002', pairs: [
      ['Over 14,000 patients were enrolled in the first phase.', 'Almost 15,000 patients had been genotyped through PREDICT as part of routine care by the mid-2010s.'],
      ['CDS alerts fired appropriately in 96% of relevant prescribing encounters, and the program demonstrated that pre-emptive PGx testing with EHR integration was technically feasible and clinically effective at scale — a model replicated by over 60 health systems including UVM Medical Center.',
       'The program demonstrated that pre-emptive PGx testing with EHR integration was feasible in routine care and changed prescribing: in a 2016 analysis of 2,676 genotyped patients, CYP2C19 status was the strongest predictor of switching away from clopidogrel.'],
      ["Dunnenberger HM et al., 'Preemptive Clinical Pharmacogenomics Testing: Mayo-Vanderbilt Collaborative Research Program,' Mayo Clinic Proceedings 2015", 'Pulley JM et al., Clinical Pharmacology & Therapeutics, 2012; Peterson JF et al., Clinical Pharmacology & Therapeutics, 2016']] },
  { id: 'academyModule-precision-medicine-m5-clinical', key: 'm5sg0002', stats: {
      m5st002a: { context: 'Varies by ancestry: about 2% of people of European ancestry, 4% of African Americans, and 14% of Chinese individuals are poor metabolizers who do not effectively activate clopidogrel. (NCBI Medical Genetics Summaries: Clopidogrel Therapy and CYP2C19 Genotype)',
                  label: 'CYP2C19 poor metabolizers, by ancestry', value: '2–14%' },
      m5st002b: { context: 'Prospective HLA-B*5701 screening before abacavir prescribing has virtually eliminated this life-threatening drug reaction. (Mallal et al., New England Journal of Medicine, 2008)' },
      m5st002c: { context: 'In 487,409 UK Biobank participants, 99.5% carried at least one genotype predicting an atypical response to a drug covered by CPIC guidance. (McInnes et al., Clinical Pharmacology & Therapeutics, 2021)' } } },
  { id: 'academyModule-precision-medicine-m6-equity', key: 'm6sg0001', stats: {
      m6st001a: { context: 'As of 2018, 78% of genome-wide association study participants were of European ancestry, 10% Asian, and 2% African. (Sirugo, Williams & Tishkoff, Cell, 2019)', label: 'GWAS participants of European ancestry (2018)' },
      m6st001b: { context: 'People of African ancestry — the most genetically diverse population on Earth — made up about 2% of GWAS participants as of 2018. (Sirugo, Williams & Tishkoff, Cell, 2019)', label: 'GWAS participants of African ancestry (2018)', value: '2%' },
      m6st001c: { context: 'Polygenic scores built from UK Biobank data predicted disease risk about 4.5 times more accurately for people of European ancestry than for people of African ancestry. (Martin et al., Nature Genetics, 2019)', label: 'PRS accuracy gap, European vs. African ancestry', value: '4.5x' } } },
  { id: 'academyModule-precision-medicine-m6-equity', key: 'm6blk009', pairs: [
      ['A 2019 study in Cell found that PRS trained on European populations had substantially lower predictive accuracy when applied to non-European populations — and that the gap was largest for individuals of African ancestry, who were farthest from the training population genetically.',
       'A 2019 study in Nature Genetics (Martin et al.) found that polygenic scores built from predominantly European data predicted risk about 4.5 times more accurately for people of European ancestry than for people of African ancestry, who are genetically farthest from the training population.']] },
  { id: 'academyModule-precision-medicine-m6-equity', key: 'm6blk040', pairs: [
      ['Rural patients with cancer face documented disparities in receiving tumor genomic profiling — the first step in precision oncology. A study published in JNCI Cancer Spectrum in 2023 found that rural cancer patients were significantly less likely to receive comprehensive genomic profiling than urban patients, even after controlling for insurance status, cancer stage, and cancer type. This means rural patients are less likely to be identified as candidates for targeted therapies they might benefit from.',
       'Rural patients with cancer have historically had less access to tumor genomic profiling — the first step in precision oncology — because testing and molecular expertise concentrate in academic centers. Programs that bring testing to community practices can close that gap: a 2024 study in JNCI Cancer Spectrum of 1,258 patients in the Maine Cancer Genomics Initiative, which deployed tumor testing through community and rural oncology practices, found that rurality was not associated with receipt of genome-matched treatment. Access, not geography itself, is the barrier.']] },
  {"id": "aiml-core-concepts", "key": "s2ex", "verdict": "FABRICATED", "claim": "Google DeepMind RL sepsis model; learned that aggressive early fluids then rapid weaning outperformed", "sources": "Komorowski M et al., 'The Artificial Intelligence Clinician learns optimal treatment strategies for sepsis in intensive care', Nature Medicine 2018;24:1716-1720 (Imperial College London; MIMIC-III + eRI)", "pairs": [["Researchers at Google DeepMind and academic medical centers trained a reinforcement learning model on retrospective ICU patient data from multiple health systems to recommend intravenous fluid volumes and vasopressor doses for septic patients on an hour-by-hour basis. The model learned treatment policies — sequences of dosing decisions — that were associated with lower 90-day mortality in historical cohorts compared to the average clinician approach. Importantly, the model did not simply maximize short-term stability; it learned that aggressive early fluid resuscitation followed by rapid weaning outperformed prolonged high-volume strategies.", "Researchers at Imperial College London (Komorowski et al., Nature Medicine, 2018) built the \"AI Clinician\", a reinforcement learning model trained on retrospective ICU data from two large US databases (MIMIC-III and the eICU Research Institute) to recommend intravenous fluid volumes and vasopressor doses for septic patients in four-hour windows. In held-out historical data, 90-day mortality was lowest in patients whose actual treatment matched the model's recommendations. On average the model favoured lower fluid volumes and higher vasopressor doses than clinicians gave."]]},
  {"id": "aiml-core-concepts", "key": "s5ex", "verdict": "UNVERIFIABLE", "claim": "Epic Deterioration Index uses gradient boosting; generating millions of alerts daily by 2024; arguably most widely deployed clinical ML model", "sources": "No primary source found for model type or alert volume (Epic does not publish them); Singh K et al., Ann Am Thorac Soc 2021 describes the DI as proprietary", "pairs": [["Epic Systems embedded a deterioration prediction model — using gradient boosting on vital signs, laboratory values, and nursing assessment inputs — across hundreds of health systems as part of its EHR platform. By 2024, the model was generating millions of patient risk alerts daily across the Epic network, making it arguably the most widely deployed clinical ML model in American healthcare.", "Epic Systems embedded a proprietary deterioration prediction model — scoring vital signs, laboratory values, and nursing assessment inputs — in its EHR platform, where it is available to hundreds of hospitals."]]},
  {"id": "aiml-core-concepts", "key": "s8s3", "verdict": "FABRICATED", "claim": "JMIR e76126 source line: journal/title mislabelled; 71%/66% predictive-AI figures attributed to the JMIR study", "sources": "Huang H et al., 'Adoption of Machine Learning in US Hospital Electronic Health Record Systems: Retrospective Observational Study', J Med Internet Res 2025;27:e76126 (PMC12688049: ~75% overall, metro 83.8% vs non-metro 61.3%); ONC Data Brief 2025: 71% of hospitals used EHR-integrated predictive AI in 2024 vs 66% in 2023", "pairs": [["JMIR Medical Informatics — Adoption of Machine Learning Functions in US Hospital Electronic Health Record Systems: Retrospective Study (2025) — https://www.jmir.org/2025/1/e76126 — 75% of non-federal acute-care hospitals had ML functions integrated in EHR systems; 71% used predictive AI in EHRs in 2024 (up from 66% in 2023); metropolitan hospitals 83.8% vs. non-metropolitan 61.3%.", "Journal of Medical Internet Research — Adoption of Machine Learning in US Hospital Electronic Health Record Systems: Retrospective Observational Study (2025) — https://www.jmir.org/2025/1/e76126 — About 75% of US general acute-care hospitals had ML functions in their EHR systems in 2023–2024; metropolitan hospitals 83.8% vs. non-metropolitan 61.3%. (Separately, ONC reports 71% of hospitals used EHR-integrated predictive AI in 2024, up from 66% in 2023.)"]]},
  {"id": "aiml-core-concepts", "key": "s8s5", "verdict": "FABRICATED", "claim": "npj Digital Medicine s41746-024-01316-0 cited under a title it does not have", "sources": "https://www.nature.com/articles/s41746-024-01316-0 — 'A Primer on Reinforcement Learning in Medicine for Clinicians' (npj Digit Med 2024)", "pairs": [["Nature npj Digital Medicine — Reinforcement Learning for Clinical Decision-Making and Dynamic Treatment Regimes (2024)", "npj Digital Medicine — A Primer on Reinforcement Learning in Medicine for Clinicians (2024)"]]},
  {"id": "aiml-performance-metrics", "key": "s5hi1", "verdict": "FABRICATED", "claim": "FDA 2023 AI/ML action plan and ONC HTI-1 both require equity-stratified performance reporting by race/ethnicity/sex/age", "sources": "ONC HTI-1 Final Rule, 89 FR 1192 (Jan 9 2024), 45 CFR 170.315(b)(11) source attributes incl. validity and fairness of prediction in test data; FDA AI/ML SaMD Action Plan is dated January 2021 and imposes no reporting requirement", "pairs": [["The FDA's 2023 AI/ML action plan and ONC's HTI-1 rule (Health Data, Technology, and Interoperability) both now require equity-stratified performance reporting for AI tools used in clinical decision support. Developers and health systems deploying predictive models are expected to report performance disaggregated by race, ethnicity, sex, and age. Equitable performance is moving from a best practice to a regulatory requirement.", "ONC's HTI-1 final rule (Health Data, Technology, and Interoperability, December 2023) requires developers of certified health IT to make source-attribute information available for predictive decision support interventions — including how validity and fairness were assessed in test data — so that deploying health systems can review it. No federal rule yet requires health systems to report model performance disaggregated by race, ethnicity, sex, and age, but transparency about subgroup performance is moving from a best practice toward a regulatory expectation."]]},
  {"id": "aiml-nlp-extraction", "key": "s1stats", "verdict": "UNVERIFIABLE", "claim": "Stat: 2.6M+ clinical notes generated daily in the US", "sources": "No primary source located for the figure; removed", "removeStats": ["s2"]},
  {"id": "aiml-nlp-extraction", "key": "s3p6", "verdict": "UNVERIFIABLE", "claim": "One EHR study found 32% of homeless patients, 19% of tobacco users, 10% of drug users documented only in the narrative", "sources": "No study with these figures found; replaced with Navathe AS et al., 'Hospital Readmission and Social Risk Factors Identified from Physician Notes', Health Services Research 2018;53(2):1110-1136 (poor social support 0.4% via codes/structured data vs 16.0% via physician notes)", "pairs": [["one EHR study found that 32% of homeless patients, 19% of current tobacco users, and 10% of drug users had these health risk factors documented only in the clinical narrative — invisible to structured-data analytics but findable by NLP.", "in one study of hospital admissions (Navathe et al., Health Services Research, 2018), poor social support was recorded for 0.4% of admissions in codes and structured EHR data but for 16.0% when physician notes were analyzed — information invisible to structured-data analytics but findable by NLP."]]},
  {"id": "aiml-fda-regulation", "key": "s2ex", "verdict": "FABRICATED", "claim": "IDx-DR De Novo spawned 510(k) lineage 'LumineticsCore (2021) and AEYE-DS (2022)'", "sources": "LumineticsCore is the 2023 rename of IDx-DR itself, not a separate 510(k) descendant; FDA 510(k) clearances for Eyenuk EyeArt (Aug 2020) and AEYE-DS (Nov 2022) cite the IDx-DR device type (21 CFR 886.1100)", "pairs": [["That single De Novo authorization spawned a lineage of 510(k) clearances—LumineticsCore (2021) and AEYE-DS (2022)—demonstrating", "That single De Novo authorization created the device type that later 510(k) clearances built on—Eyenuk's EyeArt (2020) and AEYE Health's AEYE-DS (2022)—demonstrating"]]},
  {"id": "aiml-fda-regulation", "key": "s5p4", "verdict": "FABRICATED", "claim": "'the 168 ML-enabled devices authorized that year' (conflicts with the lesson's own 253 for 2024)", "sources": "FDA AI-enabled device list: 253 authorizations in 2024; the 2024 cross-sectional study analyzed 168 ML-enabled Class II devices (Biomedicines 2025;13(12):3005)", "pairs": [["A 2024 study analyzing the 168 ML-enabled devices authorized that year", "A cross-sectional study of the 168 ML-enabled Class II devices FDA authorized in 2024"]]},
  {"id": "aiml-fda-regulation", "key": "s5sg", "verdict": "FABRICATED", "claim": "Stat context calls the 2021 Action Plan's five actions 'FDA's five GMLP commitments'", "sources": "FDA, AI/ML-Based SaMD Action Plan (Jan 2021): five actions — tailored regulatory framework incl. PCCP, GMLP, patient-centered approach/transparency, regulatory science for bias and robustness, real-world performance", "stats": {"__byLabel": {"2021 Action Plan Pillars": {"context": "The January 2021 AI/ML SaMD Action Plan's five actions: a tailored regulatory framework (PCCPs), Good Machine Learning Practice, patient-centered transparency, methods to evaluate bias and robustness, and real-world performance monitoring"}}}},
  {"id": "aiml-fairness-evaluation", "key": "s1warn", "verdict": "FABRICATED", "claim": "HTI-1 requires vendors AND their health system clients to disclose algorithm performance across demographic subgroups; ignoring bias audits is a compliance violation", "sources": "HTI-1 Final Rule 89 FR 1192 (Jan 9 2024), 45 CFR 170.315(b)(11): obligations fall on certified health IT developers (source attributes incl. validity and fairness of prediction in test data); HHS Section 1557 final rule 45 CFR 92.210 (compliance date May 1 2025): reasonable efforts to identify and mitigate discrimination risk from patient care decision support tools", "pairs": [["The ONC HTI-1 Final Rule (effective Dec 31, 2024) requires certified EHR vendors and their health system clients to disclose information about AI/predictive algorithms — including performance across demographic subgroups. Ignoring bias audits is no longer a strategic choice; it is a compliance violation.", "The ONC HTI-1 Final Rule (compliance date Dec 31, 2024) requires certified EHR developers to make source-attribute information about predictive algorithms available to their customers — including how validity and fairness were assessed in test data. HHS's Section 1557 rule separately requires covered providers and plans, from May 1, 2025, to make reasonable efforts to identify and mitigate discrimination risk from patient care decision support tools. Ignoring bias is no longer only a strategic risk; it is a compliance risk."]]},
  {"id": "aiml-fairness-evaluation", "key": "src4", "verdict": "FABRICATED", "claim": "Source annotation: HTI-1 requires disclosure of algorithm performance across demographic subgroups", "sources": "45 CFR 170.315(b)(11)(iv) source attributes", "pairs": [["including disclosure of AI/predictive algorithm performance across demographic subgroups, effective December 31, 2024.", "including source attributes on how a predictive algorithm's validity and fairness were assessed in test data, with a compliance date of December 31, 2024."]]},
  {"id": "aiml-fairness-evaluation", "key": "src5", "verdict": "FABRICATED", "claim": "Source annotation: Section 1557 requires risk management programs and ongoing monitoring of AI tools, effective July 2024", "sources": "45 CFR 92.210 (89 FR 37522, May 6 2024): prohibition on discrimination through patient care decision support tools; (b)-(c) reasonable efforts to identify and mitigate risk, compliance date May 1 2025", "pairs": [["Supports the requirement that covered healthcare providers and health plans implement risk management programs to prevent algorithmic discrimination and conduct ongoing monitoring of AI tools, effective July 2024.", "Supports the rule (45 CFR 92.210) that covered providers and health plans must not discriminate through patient care decision support tools and, from May 1, 2025, must make reasonable efforts to identify tools that use race, color, national origin, sex, age, or disability as inputs and to mitigate the risk of discrimination."]]},
  {"id": "aiml-fairness-evaluation", "key": "twblock", "verdict": "FABRICATED", "claim": "Takeaway: HTI-1 and Section 1557 made bias audits a regulatory requirement", "sources": "HTI-1 (developer transparency obligations only); 45 CFR 92.210 (reasonable-efforts duty, not an audit mandate)", "pairs": [["have made algorithm transparency and anti-discrimination compliance legally mandatory for covered health IT and providers — bias audits are now a regulatory requirement, not a best practice.", "have made algorithm transparency (for certified health IT developers) and reasonable efforts to identify and mitigate discrimination risk (for covered providers and plans) legal obligations — bias evaluation is moving from best practice to compliance expectation."]]},
  {"id": "aiml-equity-procurement", "key": "s2p3", "verdict": "UNVERIFIABLE", "claim": "'less than 5% of the training images in leading dermatology datasets depicted dark skin tones' attributed to Daneshjou 2022", "sources": "Daneshjou R et al., Sci Adv 2022;8(32):eabq6147 (PMC9374341): DeepDerm sensitivity 0.69 (FST I-II) vs 0.23 (FST V-VI) confirmed; paper gives no percentage — says DeepDerm and HAM10000 were trained on predominantly White patients", "pairs": [["The underlying cause was straightforward: less than 5% of the training images in leading dermatology datasets depicted dark skin tones (Fitzpatrick scale V–VI).", "The underlying cause was straightforward: the models had been trained on images of predominantly White patients, and leading dermatology datasets contained few images of dark skin tones (Fitzpatrick scale V–VI)."]]},
  {"id": "aiml-equity-procurement", "key": "s2sg", "verdict": "UNVERIFIABLE", "claim": "Stat: <5% of dermatology AI training images were Fitzpatrick V-VI (Daneshjou 2022)", "sources": "Daneshjou et al. Sci Adv 2022 (PMC9374341): DeepDerm sensitivity 0.69 vs 0.23", "stats": {"__byLabel": {"Dark Skin in Dermatology Datasets": {"context": "On the Diverse Dermatology Images set, the DeepDerm model's sensitivity for malignant lesions was 0.69 on light skin (Fitzpatrick I–II) but 0.23 on dark skin (Fitzpatrick V–VI) (Daneshjou et al., Science Advances, 2022)", "label": "DeepDerm Sensitivity, Dark Skin", "value": "0.23"}}}},
  {"id": "aiml-equity-procurement", "key": "src3", "verdict": "UNVERIFIABLE", "claim": "Source annotation: disparity 'driven by under-5% dark-skin representation in training data'", "sources": "PMC9374341", "pairs": [["Finds that leading dermatology AI models show nearly threefold sensitivity disparity between light and dark skin tones, driven by under-5% dark-skin representation in training data.", "Finds that state-of-the-art dermatology AI models lose 29–40% of their ROC-AUC on a diverse image set, with DeepDerm's sensitivity falling from 0.69 on light skin to 0.23 on dark skin; the models were trained predominantly on images of White patients."]]},
  {"id": "aiml-ethics", "key": "s2p2", "verdict": "FABRICATED", "claim": "EU AI Act high-risk obligations for medical-device AI (Art. 6(1)(b)) apply fully from August 2026", "sources": "Regulation (EU) 2024/1689 Art. 113: entered into force 1 Aug 2024; Annex III high-risk obligations apply 2 Aug 2026; Art. 6(1) product-safety high-risk (incl. MDR/IVDR devices) applies 2 Aug 2027", "pairs": [["The EU AI Act, which entered into application in 2024 and whose high-risk AI obligations apply fully from August 2026, classifies", "The EU AI Act, which entered into force in August 2024 and whose obligations for high-risk AI embedded in regulated products such as medical devices apply from August 2027, classifies"]]},
  {"id": "aiml-ethics", "key": "s2ex", "verdict": "UNVERIFIABLE", "claim": "Studies found Grad-CAM visualisations increase clinician confidence in radiology AI by ~30%", "sources": "No study located supporting a ~30% figure; removed", "pairs": [["Grad-CAM generates heat maps over medical images showing which pixels most activated a neural network's classification — studies have found that Grad-CAM visualisations increase clinician confidence in radiology AI by approximately 30%.", "Grad-CAM generates heat maps over medical images showing which pixels most activated a neural network's classification — useful for spotting a model that is attending to the wrong region, though a plausible-looking heat map does not prove the model is right."]]},
  {"id": "aiml-ethics", "key": "s3p4", "verdict": "FABRICATED", "claim": "'A 2025 scoping review' (cited source is a 2026 JMIR mixed-methods study)", "sources": "Maris MT et al., 'The Ethics of Leveraging Routinely Collected Patient Data for AI Development: Mixed Methods Study', J Med Internet Res 2026;28:e79863 (scoping review of 25 publications 2014-2024 plus stakeholder workshops)", "pairs": [["A 2025 scoping review published in a peer-reviewed journal identified four recurring themes in the literature", "A 2026 mixed-methods study in the Journal of Medical Internet Research, combining a scoping review of 25 publications with stakeholder workshops, identified four recurring themes in the literature"]]},
  {"id": "behavioral-health-burden", "key": "s2cmp1", "verdict": "FABRICATED", "claim": "2023 NSDUH: only 15.6% (~7.1M) of the 48.5M with SUD received treatment; 85.4% (~41M) untreated", "sources": "SAMHSA 2023 NSDUH Annual National Report (rpt47095): 54.2M people 12+ needed substance use treatment; 23.6% (12.8M) received it", "pairs": [["Only 15.6% (~7.1M) received any treatment", "54.2M needed substance use treatment; only 23.6% (12.8M) received it"], ["85.4% (~41M people) received NO treatment", "About 3 in 4 (~41M people) who needed treatment received none"]]},
  {"id": "behavioral-health-burden", "key": "qz", "verdict": "FABRICATED", "claim": "Quiz: only 15.6% of the 48.5M with SUD were treated, ~85% untreated", "sources": "SAMHSA 2023 NSDUH: 23.6% of the 54.2M needing substance use treatment received it", "pairs": [["and only 15.6% of the 48.5 million people with a substance use disorder were treated — leaving roughly 85% untreated.", "and only 23.6% of the 54.2 million people who needed substance use treatment received it — leaving roughly three in four untreated."], ["Roughly 46% of adults with any mental illness went untreated, and about 85% of people with a substance use disorder received no treatment.", "Roughly 46% of adults with any mental illness went untreated, and about three in four people who needed substance use treatment received none."]]},
  {"id": "behavioral-health-burden", "key": "s3sg1", "verdict": "FABRICATED", "claim": "Suicide 2nd leading cause of death ages 10-44 (2023)", "sources": "CDC Suicide Data and Statistics: in 2023 suicide was the second leading cause of death for people ages 10-34", "stats": {"__byLabel": {"Leading cause of death, ages 10–44": {"label": "Leading cause of death, ages 10–34"}}}},
  {"id": "behavioral-health-burden", "key": "src3", "verdict": "FABRICATED", "claim": "Source annotation: 2nd leading cause for ages 10-44", "sources": "CDC Suicide Data and Statistics (2023 data)", "pairs": [["2nd leading cause for ages 10–44.", "2nd leading cause for ages 10–34."]]},
  {"id": "behavioral-health-burden", "key": "s5p1", "verdict": "FABRICATED", "claim": "$282B study described as by 'economists affiliated with Yale and the NBER'", "sources": "Yale News 2024-04-22: Tsyvinski (Yale), Abramson (Columbia), Boerma (Wisconsin-Madison); NBER Working Paper 'Macroeconomics of Mental Health'", "pairs": [["A 2024 study by economists affiliated with Yale and the National Bureau of Economic Research estimated", "A 2024 study by economists at Yale, Columbia, and the University of Wisconsin–Madison (published as a National Bureau of Economic Research working paper) estimated"]]},
  {"id": "behavioral-health-burden", "key": "s5p2", "verdict": "UNVERIFIABLE", "claim": "Study attributed $83B to treatment, $10B to suicide, $189B to lost productivity", "sources": "Yale News 2024-04-22 gives no such breakdown: $282B/yr (~1.7% of aggregate consumption), ~30% above prior estimates, counting reduced consumption, lower investment, choice of less-demanding jobs and foregone treatment", "pairs": [["That figure is not mostly hospital bills. The study attributed about $83 billion to the direct costs of treatment, roughly $10 billion to years of life lost to suicide, and the largest share — about $189 billion — to reduced work productivity. In other words, the cost of untreated and undertreated behavioral illness shows up in lost wages, missed work, and diminished output far more than in clinical spending.", "That figure is not mostly hospital bills. The estimate — equal to about 1.7% of aggregate U.S. consumption and roughly 30% higher than earlier estimates — counts how mental illness changes economic behavior: reduced consumption, lower investment in housing and stocks, people choosing less-demanding jobs, and treatment that is never sought. In other words, the cost of untreated and undertreated behavioral illness shows up in the wider economy far more than in clinical spending."]]},
  {"id": "behavioral-health-burden", "key": "s5sg1", "verdict": "UNVERIFIABLE", "claim": "Stats: $189B lost productivity, $83B direct treatment (Yale/NBER)", "sources": "Yale News 2024-04-22 (1.7% of aggregate consumption; ~30% above previous estimates)", "stats": {"__byLabel": {"Lost work productivity": {"context": "Share of U.S. aggregate consumption lost to mental illness each year (2024 Yale/Columbia/Wisconsin NBER study)", "label": "Share of aggregate consumption", "value": "~1.7%"}, "Direct treatment costs": {"context": "How much larger the 2024 estimate is than previous estimates, because it counts behavioral and economic effects beyond treatment", "label": "Above prior estimates", "value": "~30%"}}}},
  {"id": "behavioral-health-burden", "key": "src4", "verdict": "UNVERIFIABLE", "claim": "Source annotation: $83B treatment, $189B lost productivity, $10B suicide", "sources": "Yale News 2024-04-22", "pairs": [["~$282B annual economic cost; $83B treatment, $189B lost productivity, $10B suicide.", "~$282B annual economic cost, about 1.7% of aggregate consumption and ~30% above previous estimates."]]},
  {"id": "substance-use-disorders-overview", "key": "s3p3", "verdict": "FABRICATED", "claim": "107,543 overdose deaths in 2023 (provisional count presented as the figure); 2024 ~80,000, nearly 27% drop", "sources": "CDC NCHS Data Brief 549 'Drug Overdose Deaths in the United States, 2023–2024': 107,941 (2022), 105,007 (2023), 79,384 (2024); age-adjusted rate fell 26.2%", "pairs": [["There were an estimated 107,543 drug overdose deaths in the United States in 2023 — the first annual decline since 2018 — and provisional data show deaths fell sharply again in 2024, to roughly 80,000, a nearly 27% drop.", "There were 105,007 drug overdose deaths in the United States in 2023 — the first annual decline since 2018 — and deaths fell sharply again in 2024, to 79,384, a 26% drop in the age-adjusted death rate."]]},
  {"id": "substance-use-disorders-overview", "key": "s3sg1", "verdict": "FABRICATED", "claim": "Stats: ~107,543 deaths 2023; ~80,000 2024 provisional down ~27%; ~5M adults with OUD", "sources": "CDC NCHS Data Brief 549; SAMHSA 2023 NSDUH: 5.7M people 12+ (2.0%) had OUD", "stats": {"__byLabel": {"Drug overdose deaths in 2023": {"value": "105,007"}, "Overdose deaths in 2024 (provisional)": {"context": "Age-adjusted rate down 26% from 2023 (CDC NCHS)", "label": "Overdose deaths in 2024", "value": "79,384"}, "Adults with opioid use disorder": {"context": "Past year, age 12+, 2023 (SAMHSA NSDUH)", "label": "People with opioid use disorder", "value": "5.7M"}}}},
  {"id": "substance-use-disorders-overview", "key": "src3", "verdict": "FABRICATED", "claim": "Source annotation: ~5M adults with OUD, 15.6% treatment rate", "sources": "SAMHSA 2023 NSDUH", "pairs": [["~5M adults with opioid use disorder, 15.6% treatment rate.", "5.7M (age 12+) with opioid use disorder; 23.6% of the 54.2M who needed substance use treatment received it."]]},
  {"id": "substance-use-disorders-overview", "key": "src4", "verdict": "FABRICATED", "claim": "Source annotation: ~107,543 deaths 2023; ~80,000 2024", "sources": "CDC NCHS Data Brief 549", "pairs": [["~107,543 overdose deaths in 2023 (first decline since 2018); ~80,000 in 2024; synthetic opioids the dominant driver.", "105,007 overdose deaths in 2023 (first decline since 2018); 79,384 in 2024; synthetic opioid deaths fell from 72,776 to 47,735."]]},
  {"id": "vermont-designated-agencies", "key": "s5ex1", "verdict": "UNVERIFIABLE", "claim": "Howard Center staff of around 1,300", "sources": "Howard Center public profiles report ~1,600 staff, 19,000 people helped in 2024, 60+ locations; staff count varies by source, so the specific figure was generalized", "pairs": [["with a staff of around 1,300 and supports", "with well over a thousand staff and supports"]]},
  {"id": "stratifying-measures-by-race", "key": "s2p2", "verdict": "UNVERIFIABLE", "claim": "CMS analysis: race x dual stratification revealed 24-pt gap, White non-dual 70.6% vs Black dual 46.8%", "sources": "CMS OMH, 'Disparities in Health Care in Medicare Advantage Associated with Dual Eligibility or Eligibility for a Low-Income Subsidy' (Sept 2021): figures 70.6/46.8/24 not found; report states within-race DE/LIS deficits (White: worse on 56% of measures, 12-pt breast cancer screening deficit; Black: worse on 38%)", "pairs": [["In one CMS analysis, stratifying a measure by both race and dual-eligibility (a marker of low income) at the same time revealed a 24 percentage-point gap between subgroups: White non-dual enrollees had the highest rate (about 70.6 percent) while Black dual-eligible enrollees had the lowest (about 46.8 percent). A single average would have buried that entire 24-point spread inside one unremarkable-looking number.", "In a 2021 CMS Office of Minority Health report on Medicare Advantage, stratifying by both race and dual-eligibility or low-income-subsidy status (markers of low income) at the same time showed gaps that a single average buries: within every racial group, low-income enrollees did worse on many clinical measures — on 56 percent of measures among White enrollees (including a 12-percentage-point deficit in breast cancer screening) and on 38 percent among Black enrollees."]]},
  {"id": "stratifying-measures-by-race", "key": "s2sg1", "verdict": "UNVERIFIABLE", "claim": "Stats 24 pts / 70.6% / 46.8% attributed to CMS OMH", "sources": "CMS OMH DE/LIS stratified report, Sept 2021, key findings", "stats": {"s1": {"context": "Breast cancer screening deficit for dual/LIS vs. other White MA enrollees (CMS OMH, 2021)", "label": "Hidden Disparity Gap", "value": "12 pts"}, "s2": {"context": "Share of clinical measures on which White dual/LIS enrollees did worse than White non-dual enrollees (CMS OMH, 2021)", "label": "Measures Worse, White Duals", "value": "56%"}, "s3": {"context": "Share of clinical measures on which Black dual/LIS enrollees did worse than Black non-dual enrollees (CMS OMH, 2021)", "label": "Measures Worse, Black Duals", "value": "38%"}}},
  {"id": "stratifying-measures-by-race", "key": "tw", "verdict": "UNVERIFIABLE", "claim": "Takeaway: 24-point gap (70.6% vs 46.8%)", "sources": "CMS OMH DE/LIS report 2021", "pairs": [["A CMS analysis found a 24-point gap between subgroups (White non-duals ~70.6% vs Black duals ~46.8%) that the aggregate would have buried.", "A 2021 CMS analysis that crossed race with dual-eligibility found low-income enrollees doing worse within every racial group — gaps the aggregate would have buried."]]},
  {"id": "stratifying-measures-by-race", "key": "src2", "verdict": "UNVERIFIABLE", "claim": "Source annotation: 24-point gap; 70.6% vs 46.8%", "sources": "CMS OMH DE/LIS report 2021", "pairs": [["24-point gap; White non-duals ~70.6% vs Black duals ~46.8%; intersection of race and dual status", "within-race deficits for dual/LIS enrollees (worse on 56% of measures among White and 38% among Black enrollees); intersection of race and dual status"]]},
  {"id": "academyModule-five-pillars-legislative-architecture-reform-cascade", "key": "7461ade99adf", "verdict": "FABRICATED", "claim": "'When the final report landed in late October 2024' (contradicts the lesson's own Sept 18 2024 issue date)", "sources": "Oliver Wyman final Act 167 report released September 2024 (GMCB); hospital data disputes reported late October 2024 (VTDigger 2024-10-29; Valley News 2024-10-30; Gifford statement, vermontbiz)", "pairs": [["When the final report landed in late October 2024, several hospitals publicly disputed the accuracy of the underlying data, and the dispute was covered statewide.", "Within weeks of the final report's September 2024 release, several hospitals publicly disputed the accuracy of the underlying data, and by late October the dispute was covered statewide."]]},
  {"id": "academyModule-five-pillars-cmmi-waivers-federal-state-interface", "key": "bb7767e2188f", "verdict": "FABRICATED", "claim": "Gobeille v. Liberty Mutual decided February 29, 2016", "sources": "Gobeille v. Liberty Mutual Ins. Co., 577 U.S. 312, decided March 1, 2016 (SCOTUSblog; Faegre Drinker 2016-03-01)", "pairs": [["Gobeille v. Liberty Mutual (February 29, 2016)", "Gobeille v. Liberty Mutual (March 1, 2016)"]]},
  {"id": "academyModule-five-pillars-apm-readiness-vbc-financial-modeling", "key": "6394cdeb55aa", "verdict": "UNVERIFIABLE", "claim": "Stat remnant of LEFT finding: 'Average HCC coding gap at Vermont critical access hospitals 12%' (2025 Vermont Rural Health Redesign Center assessment)", "sources": "No RHRC or AHS source located (prior phase-7b web search; prose already corrected in block dcdf27455202); stat removed", "removeStats": ["51ddc7213e1d"]},
  {"id": "academyModule-five-pillars-economics-as-design-vs-management", "key": "0a418939064b", "verdict": "UNVERIFIABLE", "claim": "Stat: 12% average HCC coding gap at Vermont CAHs (2025 Vermont Rural Health Redesign Center assessment) — same unverifiable claim as earlier LEFT lines", "sources": "No RHRC or AHS source located; removed as in the APM-readiness and knowledge-infrastructure lessons", "removeStats": ["a78130a73218"]},
  {"id": "academyModule-five-pillars-economics-as-design-vs-management", "key": "2c6262a469b5", "verdict": "UNVERIFIABLE", "claim": "Quote attributed to Owen Foster on signing AHEAD, Jan 2025: 'If the model is not adequately regulated and sufficiently resourced, it will fail dramatically...'", "sources": "No published source found for the quotation (web searches of VTDigger, Vermont Public, GMCB); removed rather than attribute words to a named person", "pairs": [["\"If the model is not adequately regulated and sufficiently resourced, it will fail dramatically and harm patients and harm our health system.\" -- Owen Foster, Chair of the Vermont Green Mountain Care Board, on signing the AHEAD State Agreement, January 2025. Regulation is design; resourcing is management. Foster's warning names both halves as necessary.", "Regulation is design; resourcing is management. A global budget needs both halves: a binding rule that sets the ceiling, and the analytic and operational capacity to live within it. Either one alone fails."]]},
  {"id": "academyModule-five-pillars-global-budgets-reference-based-pricing", "key": "b2cc9717ac17", "verdict": "FABRICATED", "claim": "Maryland HSCRC established in 1972 (the course's legislative lesson says 1971)", "sources": "Maryland HSCRC: created by the General Assembly in 1971 (Md. Health-General Art. Title 19, Subtitle 2); rate setting began 1974; Medicare waiver 1977", "pairs": [["was established in 1972 with a unique statutory authority", "was created by the Maryland General Assembly in 1971 with a unique statutory authority"]]},
  {"id": "academyModule-five-pillars-global-budgets-reference-based-pricing", "key": "c1e636d48b35", "verdict": "FABRICATED", "claim": "Maryland: 7% fewer Medicare admissions and '$800 million reduction in Medicare Part A and B spending (CMS evaluation)'", "sources": "RTI International, Evaluation of the Maryland All-Payer Model, Final Report (CMS, Nov 2019): total Medicare expenditures -2.8% ($975M), driven by -4.1% total hospital expenditures ($796M); Medicare admissions -7.2%; ACSC admissions -6.7%; HSCRC PY5 results: $1.4B Medicare hospital savings vs national trend", "pairs": [["and an estimated $800 million reduction in Medicare Part A and B spending (CMS evaluation).", "and, per the CMS-commissioned evaluation, $975 million less total Medicare spending (2.8% slower growth), $796 million of it in hospital spending."]]},
  {"id": "academyModule-five-pillars-global-budgets-reference-based-pricing", "key": "2ddf5f14c1f3", "verdict": "FABRICATED", "claim": "Stat: '$800M Reduction in Medicare Part A and B hospital spending (CMS evaluation)'", "sources": "RTI final evaluation (CMS, 2019): hospital expenditures $796M; total Medicare $975M", "stats": {"__byLabel": {"Reduction in Medicare Part A and B hospital spending": {"context": "Source: RTI International evaluation for CMS (2019); total Medicare savings were $975M", "label": "Reduction in Medicare hospital spending vs. comparison group, first 4.5 years", "value": "$796M"}}}},
];
