// Phase 8a part 3 — source-integrity corrections for the last two courses: Health Equity Analytics (hea-*) and
// Healthcare Interoperability & Data Exchange (interop-*, ehr-business-case-roi). Same op shape as _phase8a_ops.mjs.
// Applied with: node scripts/_phase8a_apply2.mjs [--commit] --only=<docId>. Ledger: docs/audits/phase7b_sources_2026-10.jsonl, "part":"8a".

const TRUONG = 'Truong HP, Luke AA, Hammond G, Wadhera RK, Reidhead M, Joynt Maddox KE, "Utilization of Social Determinants of Health ICD-10 Z-Codes Among Hospitalized Patients in the United States, 2016–2017," Medical Care 2020 (PMC7666017): 269,929 of 14.3M NIS admissions (1.9%) carried an SDOH Z-code. The previously cited PMC12608873 is Hau et al., Healthcare (Basel) 2025, a VA trial cohort study that reports 99.2% of SDOH codes were outpatient — it does not contain the 1.9% figure.';
const HEI = 'Federal Register 88 FR 22120 (12 Apr 2023, CY2024 MA/Part D final rule) finalized the Health Equity Index reward to replace the reward factor starting with 2027 Star Ratings; CMS CY2027 MA/Part D final rule fact sheet (2 Apr 2026) — HEI reward not implemented, historical reward factor continued.';

const NHQDR = 'AHRQ, 2017 National Healthcare Quality and Disparities Report: Introduction and Methods (stacks.cdc.gov/view/cdc/85040), pp.4, 10-11: disparity = absolute difference significant at p<0.05 AND relative difference [p1-p2]/p2 >= 10%; "The largest subgroup or the subgroup that often received the best healthcare is used as the reference group"; statistics with n<30 or RSE>30% suppressed. NBK600456 = "Methods of the National Healthcare Quality and Disparities Report and Related Chartbooks" (NCBI esummary).';
const MMD = 'CMS OMH, MMD Tool FAQs (cms.gov/About-CMS/Agency-Information/OMH/Downloads/MMDT-FAQs.pdf): Population View has ten outcome measures on "up to 60 specific chronic and potentially disabling conditions" and 27 preventive services, plus ESRD/disability; Hospital View; suppression for confidentiality. CMS press release 17 Mar 2016: launched to increase understanding of disparities.';

const RUSH = 'Ansell DA et al., "Health Equity as a System Strategy: The Rush University Medical Center Framework," NEJM Catalyst May 2021, DOI 10.1056/CAT.20.0674 (full text via cultureofhealth-leaders.org PDF): strategy launched from Chicago racial life-expectancy gaps / CHNA; "In January 2017, we organized an internal Anchor Mission committee that set targets for local hiring, career pathways, local spend, and volunteering"; Health Equity Governance Committee for inequities in outcomes; the West Side Anchor Committee is a cross-institution body of six West Side health anchors.';

export const OPS = [
  // ---------------- hea-measurement-foundations
  { id: 'hea-measurement-foundations', key: 'l1s1sg1', verdict: 'MISATTRIBUTED', claim: 'stat "1.9% inpatient admissions coded with an SDOH Z-code" sourced to "Peer-reviewed SDOH Z-code adoption study, PMC" (PMC12608873)', sources: TRUONG,
    stats: { __byLabel: { 'Inpatient admissions coded with an SDOH Z-code': { context: 'Truong et al., Medical Care 2020 — 2016–2017 National Inpatient Sample' } } },
    mirrorPairs: [['Inpatient admissions coded with an SDOH Z-code despite CDC/WHO emphasis', 'Inpatient admissions coded with an SDOH Z-code, 2016–2017'], ['PMC, SDOH Z-code adoption study', 'Truong et al., Medical Care 2020 (National Inpatient Sample)'], ['Peer-reviewed SDOH Z-code adoption study, PMC', 'Truong et al., Medical Care 2020 — 2016–2017 National Inpatient Sample']] },
  { id: 'hea-measurement-foundations', key: 'l1s4p2', verdict: 'MISATTRIBUTED', claim: '"one peer-reviewed study found that only about 1.9% of inpatient hospital admissions carried an SDOH Z-code" (cited to PMC12608873)', sources: TRUONG,
    pairs: [['one peer-reviewed study found that only about 1.9% of inpatient hospital admissions carried an SDOH Z-code', 'an analysis of the 2016–2017 National Inpatient Sample (Truong et al., Medical Care, 2020) found that only about 1.9% of inpatient hospital admissions carried an SDOH Z-code']] },
  { id: 'hea-measurement-foundations', key: 'src4', verdict: 'MISATTRIBUTED', claim: 'source [4] "SDOH ICD-10 Z-code adoption study — PMC12608873 — ~1.9% of inpatient admissions"', sources: TRUONG,
    pairs: [['[4] SDOH ICD-10 Z-code adoption study — https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12608873/ — ~1.9% of inpatient admissions coded with an SDOH Z-code',
      '[4] Truong HP et al., "Utilization of Social Determinants of Health ICD-10 Z-Codes Among Hospitalized Patients in the United States, 2016–2017," Medical Care (2020) — https://pmc.ncbi.nlm.nih.gov/articles/PMC7666017/ — 1.9% of 14.3 million admissions carried an SDOH Z-code']] },
  { id: 'hea-measurement-foundations', key: 'l1qz', verdict: 'UNVERIFIABLE', claim: 'quiz explanation: Z-code use is low "despite CDC/WHO emphasis on their use"', sources: 'No CDC or WHO campaign promoting SDOH Z-code use located; the codes are part of ICD-10-CM (maintained by CDC/NCHS) and the Gravity Project–AMA coding guide is real (AMA/Gravity Project, 2023).',
    pairs: [['National data shows SDOH Z-code use around 1.9% of inpatient admissions despite CDC/WHO emphasis on their use and active crosswalk tools from the Gravity Project and AMA',
      'National Inpatient Sample data (Truong et al., 2020) show SDOH Z-codes on about 1.9% of inpatient admissions, even though the codes are part of ICD-10-CM and the Gravity Project and AMA publish crosswalk tools for them']] },
  { id: 'hea-measurement-foundations', key: 'l1s2p1', verdict: 'INACCURATE', claim: 'HEROI weights attributed to "Chapter 10, section 13.1" of the book', sources: 'HTR_Book_v42 §10.13.1 "HEROI Components" (weights 25/25/25/15/10); HealthEquityStudio.tsx line 465 uses the same weights',
    pairs: [['(Chapter 10, section 13.1)', '(Chapter 10, section 10.13.1)']] },
  { id: 'hea-measurement-foundations', key: 'l1s3p2', verdict: 'INACCURATE', claim: 'Health Equity Index reward described as "previously proposed" (it was finalized in April 2023, then not implemented)', sources: HEI,
    pairs: [['did not implement the previously proposed Health Equity Index reward for Star Ratings', 'did not implement the Health Equity Index reward for Star Ratings that CMS had finalized in 2023']],
    mirrorPairs: [['declined to implement the previously proposed Health Equity Index reward', 'declined to implement the Health Equity Index reward it had finalized in 2023'],
      ['the Health Equity Index reward was proposed but not adopted for 2027.', 'the Health Equity Index reward was finalized in 2023 but not implemented for 2027.']] },
  { id: 'hea-measurement-foundations', key: 'l1tw', verdict: 'INACCURATE', claim: 'takeaway "CMS declined to implement a proposed Health Equity Index reward"', sources: HEI,
    pairs: [['CMS declined to implement a proposed Health Equity Index reward for 2027', 'CMS declined to implement its previously finalized Health Equity Index reward for 2027']] },,
  // ---------------- hea-disparity-decomposition
  { id: 'hea-disparity-decomposition', key: 'l2s1p2', verdict: 'INACCURATE', claim: 'AHRQ NHQDR "computes rate ratios ... as its headline disparity statistic"', sources: NHQDR,
    pairs: [['computes rate ratios between each priority population and a reference group as its headline disparity statistic.', 'uses both scales at once: it counts a gap as a disparity only when the absolute difference between a priority population and its reference group is statistically significant and the relative difference is at least 10%.']],
    mirrorPairs: [['computes rate ratios between each priority population and a reference group for its headline disparity tables.', 'counts a gap as a disparity only when the absolute difference between a priority population and its reference group is statistically significant and the relative difference is at least 10%.']] },
  { id: 'hea-disparity-decomposition', key: 'l2s1p3', verdict: 'INACCURATE', claim: '"AHRQ\'s NHQDR reports rate ratios rather than differences alone"', sources: NHQDR,
    pairs: [['This is exactly why AHRQ\'s NHQDR reports rate ratios rather than differences alone — the ratio surfaces gaps that a raw percentage-point comparison can hide.', 'This is why AHRQ\'s NHQDR tests the relative difference alongside the absolute one — the relative scale surfaces gaps that a raw percentage-point comparison can hide.']] },
  { id: 'hea-disparity-decomposition', key: 'l2s3p1', verdict: 'UNVERIFIABLE', claim: '"AHRQ\'s own methodology documentation is explicit that reference-group selection is an ongoing, actively reviewed methods decision"', sources: NHQDR,
    pairs: [['AHRQ\'s own methodology documentation is explicit that reference-group selection is an ongoing, actively reviewed methods decision, not a fixed convention: comparing', 'AHRQ\'s NHQDR methods documentation states its choice explicitly — the largest subgroup or the subgroup that typically receives the best care (for example non-Hispanic White, high income, private insurance) — and the choice matters: comparing']],
    mirrorPairs: [['AHRQ\'s own methodology documentation is explicit that this choice matters and is under continuous review: comparing', 'AHRQ\'s NHQDR methods documentation states its choice explicitly (the largest subgroup or the one that typically receives the best care), and the choice matters: comparing']] },
  { id: 'hea-disparity-decomposition', key: 'l2qz', verdict: 'UNVERIFIABLE', claim: 'quiz explanation: "the reference-group effect AHRQ\'s methodology documentation flags as a disclosed choice"', sources: NHQDR,
    pairs: [['this is exactly the reference-group effect AHRQ\'s methodology documentation flags as a disclosed choice.', 'which is why AHRQ\'s NHQDR methods documentation states its reference groups explicitly.']] },
  { id: 'hea-disparity-decomposition', key: 'l2s4p1', verdict: 'INACCURATE', claim: 'arithmetic: a rate from 20 patients "can swing from a 5% disparity to a 25% disparity with just two additional events" (two events on n=20 move a rate 10 points, 5% -> 15%)', sources: 'Arithmetic: 1/20 = 5%, 3/20 = 15%. AHRQ NHQDR 2017 Methods p.4: estimates with n<30 or RSE>30% suppressed.',
    pairs: [['can swing from a 5% disparity to a 25% disparity with just two additional events', 'can jump from 5% to 15% with just two additional events (1 of 20 to 3 of 20)']],
    mirrorPairs: [['can swing from a 5% disparity to a 25% disparity with two additional events', 'can jump from 5% to 15% with two additional events (1 of 20 to 3 of 20)']] },
  { id: 'hea-disparity-decomposition', key: 'l2ex1', verdict: 'INACCURATE', claim: 'MMD Tool tracks "18-plus chronic conditions"; launched "to make the reference-group and small-numbers problems ... solvable"', sources: MMD,
    pairs: [['launched the MMD Tool in March 2016 to make the reference-group and small-numbers problems this lesson describes solvable for public users', 'launched the MMD Tool in March 2016 to increase understanding of disparities among Medicare beneficiaries — and in doing so it makes the reference-group and small-numbers problems this lesson describes solvable for public users'],
      ['The tool tracks prevalence across 18-plus chronic conditions plus end-stage renal disease and disability status', 'The tool tracks up to 60 chronic and potentially disabling conditions plus end-stage renal disease and disability status']],
    mirrorPairs: [['in March 2016 specifically to solve the reference-group and small-numbers problems for public users.', 'in March 2016 to increase understanding of disparities among Medicare beneficiaries, and its design settles the reference-group and small-numbers problems for public users.'],
      ['across 18-plus chronic conditions.', 'across up to 60 chronic and potentially disabling conditions.']],
    mirrorObjects: [{ match: { label: 'Chronic conditions the MMD Tool tracks by race/ethnicity, geography, and dual-eligibility', value: '18+' }, set: { label: 'Chronic and potentially disabling conditions the MMD Tool tracks', value: 'Up to 60' } }] },
  { id: 'hea-disparity-decomposition', key: 'src2', verdict: 'INACCURATE', claim: 'source [2] described as "rate ratio methodology"', sources: NHQDR,
    pairs: [['— rate ratio methodology and reference-group documentation', '— disparity test (significant absolute difference plus relative difference of at least 10%), reference groups, and small-sample suppression']] },,
  // ---------------- hea-stratified-quality-measurement
  { id: 'hea-stratified-quality-measurement', key: 'l3s3p1', verdict: 'INACCURATE', claim: 'CMS "proposed a Health Equity Index reward — initially branded the Excellent Health Outcomes for All reward" (it was finalized in 2023 as the HEI and renamed EHO4all later)', sources: HEI + ' Rename: CY2025 final rate announcement renamed the HEI reward "Excellent Health Outcomes for All" (Rise Health / Becker\'s Payer coverage).',
    pairs: [['CMS proposed a Health Equity Index reward — initially branded the "Excellent Health Outcomes for All" reward — as a new', 'In April 2023 CMS finalized a Health Equity Index reward — later renamed the "Excellent Health Outcomes for All" reward — as a new']],
    mirrorPairs: [['the payment incentive that had been proposed as a Health Equity Index reward for Star Ratings', 'the renamed Health Equity Index reward CMS had finalized in 2023 for Star Ratings'],
      ['CMS did not implement the previously proposed Health Equity Index reward for 2027', 'CMS did not implement the Health Equity Index reward it had finalized in 2023 (set to begin with 2027 Star Ratings)']] },
  { id: 'hea-stratified-quality-measurement', key: 'l3tw', verdict: 'INACCURATE', claim: 'takeaways: "a proposed Health Equity Index reward"; Rush "converted stratified data into an Anchor Mission committee with authority over hiring, purchasing, and community investment"', sources: HEI + ' ' + RUSH,
    pairs: [['CMS declined to implement a proposed Health Equity Index reward for 2027', 'CMS declined to implement its previously finalized Health Equity Index reward for 2027'],
      ['Rush University Medical Center converted stratified data into an Anchor Mission committee with authority over hiring, purchasing, and community investment — not just a clinical protocol change.', 'Rush University Medical Center turned a documented life-expectancy gap into standing structures — an Anchor Mission committee with local hiring and spending targets, and a Health Equity Governance Committee steering improvement work on outcome inequities — not just a clinical protocol change.']] },
  { id: 'hea-stratified-quality-measurement', key: 'l3ex1', verdict: 'INACCURATE', claim: 'Rush case: strategy "built around what stratified quality and screening data showed"; "the West Side Anchor Committee" described as Rush\'s Anchor Mission structure tasked with hiring/purchasing/investment', sources: RUSH,
    pairs: [['documented in a 2021 NEJM Catalyst case study titled "Health Equity as a System Strategy," treated stratified data as an organizing principle for the whole institution rather than a compliance artifact filed once a year by the quality department. Rush built its strategy around what stratified quality and screening data showed about its surrounding West Side Chicago neighborhood.',
        'documented in a May 2021 NEJM Catalyst article, "Health Equity as a System Strategy: The Rush University Medical Center Framework" (Ansell et al.), started from what its community health needs assessment showed: large life-expectancy gaps between downtown Chicago and the West Side neighborhoods Rush serves. Rush made equity a system strategy, with an executive lead reporting to the CEO and executive pay tied to a Diversity Index.'],
      ['Concretely, that meant forming a dedicated Anchor Mission structure — the West Side Anchor Committee — explicitly tasked with translating what the data showed into hiring, purchasing, and community-investment decisions, not only clinical protocol changes.',
        'Concretely, Rush organized an internal Anchor Mission committee in January 2017 that set targets for local hiring, career pathways, local spending, and volunteering, reporting to senior leadership twice a year, and a multidisciplinary Health Equity Governance Committee that steers improvement projects on racial, ethnic, gender, and age inequities in patient outcomes — the kind of gap only stratified data can surface. (The separate West Side Anchor Committee coordinates six West Side health systems through West Side United.)']] ,
    mirrorPairs: [['treated data stratification as a system-level strategy rather than a compliance exercise: Rush restructured its own operations around what stratified data showed about its West Side Chicago neighborhood, including forming a dedicated Anchor Mission committee to translate what the numbers found into hiring, purchasing, and investment decisions in the surrounding community — not just clinical protocol changes.',
        'treated health equity as a system-level strategy rather than a compliance exercise: starting from the life-expectancy gap its community health needs assessment documented on Chicago\'s West Side, Rush formed an internal Anchor Mission committee with targets for local hiring, career pathways, local spending, and volunteering, and a Health Equity Governance Committee to steer improvement work on racial, ethnic, gender, and age inequities in patient outcomes — not just clinical protocol changes.'],
      ['It organized hiring, purchasing, and community investment decisions (an anchor-mission approach) around what the stratified data showed', 'It organized hiring, purchasing, and community investment decisions (an anchor-mission approach) around the health gaps it had documented in its community'],
      ['translating what stratified data showed into structural, community-facing action (an anchor-mission committee)', 'translating documented health gaps into structural, community-facing action (an anchor-mission committee)']] },
  { id: 'hea-stratified-quality-measurement', key: 'src4', verdict: 'INACCURATE', claim: 'source [4] described as a "West Side Anchor Committee case study" with no authors', sources: RUSH,
    pairs: [['[4] Rush University Medical Center, "Health Equity as a System Strategy," NEJM Catalyst 2021 — https://catalyst.nejm.org/doi/full/10.1056/CAT.20.0674 — West Side Anchor Committee case study',
      '[4] Ansell DA, Oliver-Hightower D, Goodman LJ, Lateef OB, Johnson TJ, "Health Equity as a System Strategy: The Rush University Medical Center Framework," NEJM Catalyst, May 2021 — https://catalyst.nejm.org/doi/full/10.1056/CAT.20.0674 — Anchor Mission committee, Health Equity Governance Committee, West Side United']] },
];
