// Regenerates the data behind docs/hero-revamp/hero-revamp-spec.html from the
// code that actually ships, so the spec can never show a superseded design:
//   - the five hero drawings, rendered by components/framework/FrameworkMapDiagram
//   - slide copy, figures, citations and links, from lib/briefings
//
//   npx tsx scripts/export-spec-data.tsx
import fs from "node:fs";
import path from "node:path";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import FrameworkMapDiagram, { PILLAR_QUESTION } from "../components/framework/FrameworkMapDiagram";
import { BRIEFINGS, citationOrder } from "../lib/briefings/briefings";
import { SOURCES } from "../lib/briefings/sources";
import { getPillar } from "../lib/taxonomy/pillars";
import { getTool } from "../lib/taxonomy/tools";
import { getChapter } from "../lib/taxonomy/chapters";

const svg = (props: Record<string, unknown>) => renderToStaticMarkup(React.createElement(FrameworkMapDiagram, props as never));

const data = {
  generated: new Date().toISOString().slice(0, 10),
  litSvg: svg({ lit: true, idPrefix: "spec-lit" }),
  briefings: BRIEFINGS.map((b) => {
    const p = getPillar(b.pillar);
    const order = citationOrder(b);
    return {
      slug: b.slug,
      pillar: p.label,
      color: p.hexStrong,
      question: PILLAR_QUESTION[b.pillar],
      asOf: b.asOf,
      headline: b.headline,
      dek: b.dek,
      facts: b.facts,
      equityLine: b.equityLine,
      sources: order,
      svg: svg({ selected: b.pillar, idPrefix: `spec-${b.pillar}` }),
      sections: b.sections.map((s) => s.heading),
      chapters: b.chapters.map((n) => `Ch ${n}: ${getChapter(n)?.title ?? ""}`),
      courses: b.courses.map((c) => `${c.title} (/academy/tracks/${c.slug})`),
      tools: b.tools.map((id) => `${getTool(id).label} (${getTool(id).href})`),
      platform: b.platform.map((x) => `${x.label} (${x.href})`),
    };
  }),
  sources: SOURCES,
};

const out = path.resolve(__dirname, "../../docs/hero-revamp/spec-data.js");
fs.writeFileSync(out, `// Generated by frontend/scripts/export-spec-data.tsx — do not edit by hand.\nwindow.SPEC = ${JSON.stringify(data)};\n`);
console.log("wrote", out, fs.statSync(out).size, "bytes");
