import {defineType, defineArrayMember} from 'sanity'

/**
 * This is the schema definition for the rich text fields used for
 * for this blog studio. 
 */
export const blockContentType = defineType({
  title: 'Block Content',
  name: 'blockContent',
  type: 'array',
  of: [
    defineArrayMember({
      title: 'Block',
      type: 'block',
      styles: [
        {title: 'Normal', value: 'normal'},
        {title: 'H1', value: 'h1'},
        {title: 'H2', value: 'h2'},
        {title: 'H3', value: 'h3'},
        {title: 'H4', value: 'h4'},
        {title: 'Quote', value: 'quote'},
        {title: 'Highlight', value: 'highlight'},
        // ADDED TO MATCH FRONTEND AND PROMPT V2.3
        {title: 'Callout', value: 'callout'}, 
      ],
      lists: [{title: 'Bullet', value: 'bullet'}, {title: 'Numbered', value: 'number'}],
      marks: {
        decorators: [
          {title: 'Strong', value: 'strong'},
          {title: 'Emphasis', value: 'em'},
          {title: 'Underline', value: 'underline'},
          {title: 'Strike', value: 'strike-through'},
        ],
        annotations: [
          {
            title: 'URL',
            name: 'link',
            type: 'object',
            fields: [
              {
                title: 'URL',
                name: 'href',
                type: 'url',
              },
            ],
          },
        ],
      },
    }),
    defineArrayMember({
      type: 'image',
      options: {hotspot: true},
      // Added fields to support the captions/alt generated by the AI
      fields: [
        {
          name: 'caption',
          type: 'string',
          title: 'Caption',
        },
        {
          name: 'alt',
          type: 'string',
          title: 'Alternative Text',
        }
      ]
    }),
    defineArrayMember({
      type: 'code',
      options: {language: 'json'},
    }),
    defineArrayMember({
      type: 'object',
      name: 'video',
      title: 'Video',
      fields: [
        {name: 'url', type: 'url', title: 'URL'},
        {name: 'caption', type: 'string', title: 'Caption'},
      ],
      preview: {
        select: {title: 'caption', subtitle: 'url'},
        prepare({title, subtitle}) {
          return {title: title || 'Video', subtitle}
        },
      },
    }),
    defineArrayMember({
      type: 'object',
      name: 'audio',
      title: 'Audio',
      fields: [
        {name: 'title', type: 'string', title: 'Title'},
        {name: 'url', type: 'url', title: 'URL'},
        {name: 'summary', type: 'string', title: 'Summary'},
      ],
      preview: {
        select: {title: 'title', subtitle: 'summary'},
        prepare({title, subtitle}) {
          return {title: title || 'Audio', subtitle}
        },
      },
    }),
  ],
})