# Phase 8b — builds the Medicaid Managed Care Operations fallback/quiz string-pair spec (mmc_fallbacks.json).
# Each old string is asserted present in the scratch dump of that lesson before the spec is written.
import json, sys, os
FB = sys.argv[1]
L = {"why-states-move-to-managed-care":"5abd1ca5-642e-4e07-bf12-d001e4ef1c16","medicaid-delivery-system-models":"78b0a932-569a-4c15-b900-a9fb8b29a1a8","federal-framework-438":"c0250996-29ce-4fd6-81bb-c602473d7a43","rfp-process-mco-selection":"5f52b8ec-98ed-4795-a194-862449ee48ba","contract-requirements":"d364b782-f8d1-4ed4-bdc9-5c429cbae045","monitoring-oversight-eqro":"7dea9b4b-c3b3-471a-beb0-efdc58ebab62","capitation-rate-setting":"445d7c79-cf76-4b39-aebf-90a5dbd3ea95","risk-adjustment-medicaid":"d2ecdda1-84dc-4384-8a78-d17f9bb6eadb","mlr-requirements":"b9547cc0-b01f-4589-8c02-01b98ad730ce","covered-benefits-carveins-carveouts":"3b0e959a-8a47-49d9-ad5e-5899c500be59","network-adequacy-standards":"b1b2c5fa-7453-4033-a917-a9a22734f155","provider-credentialing-mco":"59acbd07-d668-4f4b-a5bf-25682ca84386","hedis-medicaid-reporting":"6f997b68-4698-488e-9e0a-a861a5bc1fd2","ltss-mltss-care-coordination":"9319601f-c19e-4bc1-977e-8a8709e0290c","value-based-purchasing-medicaid":"b01ccd5e-1824-41c3-a85a-f66df7727cb1","section-1115-waivers":"70e72ac3-23eb-44a0-891c-c8545da8c1d1"}
P = []; QQ = set(); QO = set()
def p(lesson, old, new, claim, verdict, src, q=None, o=None):
    t = open(os.path.join(FB, lesson + '.txt')).read()
    probe = json.dumps(old, ensure_ascii=False)[1:-1] if '\n' in old else old
    assert (old in t) or (probe in t), f'NOT FOUND in {lesson}: {old[:80]}'
    if q: QQ.add(q)
    if o: QO.add(o)
    P.append(dict(old=old, new=new, claim=claim, verdict=verdict, src=src, note=f'Fallback/quiz of {lesson}.'))

CMS24 = 'CMS 2024 Medicaid Managed Care Enrollment report (fetched PDF); KFF 10 Things to Know About Medicaid Managed Care (fetched)'
p('why-states-move-to-managed-care', "Most states use Section 1915(b) waivers to mandate managed care enrollment.", "Many states use Section 1915(b) waivers to mandate managed care enrollment (others use the Section 1932(a) state plan option created by the Balanced Budget Act of 1997, or Section 1115).",
  'Most states use 1915(b) waivers to mandate managed care', 'UNVERIFIABLE', 'MACPAC managed care authorities (1932(a), 1915(a), 1915(b), 1115); no source that "most" use 1915(b)')
p('why-states-move-to-managed-care', "What federal authority do most states use to mandate Medicaid managed care enrollment?", "Which federal waiver authority lets states mandate Medicaid managed care enrollment by waiving freedom-of-choice requirements?",
  'quiz: "What federal authority do most states use..."', 'UNVERIFIABLE', 'same', q='c8f821b9-aa0c-44a8-afb1-b52a1908d0e2')
p('medicaid-delivery-system-models', "non-profit plans (UPMC, WellCare, local CCOs)", "non-profit plans (such as UPMC for You, CareSource, and Oregon's local CCOs)",
  'WellCare listed as a non-profit plan (it is for-profit, owned by Centene)', 'FABRICATED', 'Centene acquired WellCare (2020); CareSource and UPMC for You are nonprofit plans')
p('medicaid-delivery-system-models', "Ohio's Medicaid managed care program, for example, contracts with five MCOs covering over 3 million beneficiaries across the state.", "Ohio's Next Generation managed care program, launched in February 2023, for example, contracts with seven MCOs serving more than 3 million members.",
  'Ohio contracts with five MCOs', 'FABRICATED', 'Ohio Medicaid Next Generation (launched Feb 1 2023): seven MCOs (AmeriHealth Caritas, Anthem, Buckeye, CareSource, Humana, Molina, UnitedHealthcare), 3M+ members (Health Policy Ohio; ODM)')
p('medicaid-delivery-system-models', "(typically $2–$7 PMPM)", "(typically a few dollars PMPM)", 'PCCM fee typically $2-$7 PMPM', 'UNVERIFIABLE', 'No source found for the $2-$7 range; MACPAC/ASPE describe a small monthly fee')
p('medicaid-delivery-system-models', "Oregon's Coordinated Care Organizations (CCOs) and Vermont's All-Payer ACO Model represent hybrid approaches where provider-led entities take on population-level accountability with global budget caps.", "Oregon's Coordinated Care Organizations (CCOs), which operate under global budgets, and Vermont's All-Payer ACO Model (2017–2025) are hybrid approaches where provider-led entities take on population-level accountability.",
  'Vermont All-Payer ACO Model presented as current with global budget caps', 'FABRICATED', 'Vermont All-Payer ACO Model agreement ended Dec 31 2025 and OneCare Vermont wound down (Healthcare Innovation; VTDigger; UVM Health retrospective)')
SUB_OLD = "- **Subpart A** — General provisions, definitions (MCO, PAHP, PIHP, PCCM)\n- **Subpart B** — State responsibilities: contract requirements, actuarial soundness\n- **Subpart C** — Enrollee rights and protections, marketing standards\n- **Subpart D** — Access and availability: network adequacy, timely access\n- **Subpart E** — Quality measurement and improvement (QAP requirements)\n- **Subpart F** — Grievance and appeal systems\n- **Subpart G** — External Quality Review (EQRO requirements)\n- **Subpart H** — Payments: actuarial soundness, MLR, risk corridors"
SUB_NEW = "- **Subpart A** — General provisions: definitions, standard contract requirements (§438.3), actuarially sound rates (§§438.4–438.7), medical loss ratio (§438.8)\n- **Subpart B** — State responsibilities: enrollment and choice, state monitoring (§438.66), network adequacy standards (§438.68), MLR reporting (§438.74)\n- **Subpart C** — Enrollee rights and protections, marketing standards\n- **Subpart D** — MCO, PIHP and PAHP standards: availability of services, care coordination, coverage and authorization, provider selection\n- **Subpart E** — Quality measurement and improvement; External Quality Review (§§438.310–438.370)\n- **Subpart F** — Grievance and appeal system\n- **Subpart G** — Medicaid managed care quality rating system (added 2024)\n- **Subpart H** — Additional program integrity safeguards"
ECFR = 'eCFR structure API, 42 CFR Part 438 (fetched 2026-10-09): A General (438.1-438.16 incl. 438.3, 438.4-7, 438.8), B State Responsibilities (438.50-438.74 incl. 438.66, 438.68), C Enrollee Rights, D MCO/PIHP/PAHP Standards, E Quality Measurement and Improvement; External Quality Review (438.310-438.370), F Grievance and Appeal, G Quality Rating System, H Program Integrity, I Sanctions, J FFP, K Parity'
p('federal-framework-438', SUB_OLD, SUB_NEW, 'Part 438 subpart map (EQR in G, MLR/rates in H with "risk corridors", D = network adequacy)', 'FABRICATED', ECFR)
p('federal-framework-438', "First substantially revised in 2002 and comprehensively overhauled in 2016", "First issued in 2002 to implement the Balanced Budget Act of 1997, and comprehensively overhauled in 2016",
  'Part 438 "first substantially revised in 2002"', 'FABRICATED', 'Part 438 was created by the June 14, 2002 final rule implementing BBA 1997 (67 FR 40989); overhauled by 81 FR 27498 (May 6, 2016, FR API confirmed)')
p('federal-framework-438', "mandatory Medical Loss Ratio (MLR) floor of 85% for MCOs", "an 85% medical loss ratio (MLR) standard for setting capitation rates",
  '2016 rule created a mandatory 85% MLR floor for MCOs', 'FABRICATED', '42 CFR 438.4(b)(9) (rates set so plan can reasonably achieve 85% MLR) and 438.8(c) (any state minimum >= 85%); remittance is a state option (438.8(j)); CCF Georgetown March 2024 (fetched)')
p('federal-framework-438', "Subpart G of 42 CFR Part 438 (§§438.350–370) governs External Quality Review, including EQRO qualifications, mandatory activities, and state reporting requirements.", "Subpart E of 42 CFR Part 438 (\"Quality Measurement and Improvement; External Quality Review\") contains the EQR rules at §§438.350–438.370, including EQRO qualifications and mandatory activities. Subpart G, added in 2024, is the Medicaid managed care quality rating system.",
  'quiz explanation: EQR is in Subpart G', 'FABRICATED', ECFR, q='ec363f62-0006-429a-9593-0cfce6648186')
p('federal-framework-438', "The 2016 final rule established an 85% MLR floor for Medicaid MCOs, meaning at least 85 cents of every premium dollar must be spent on clinical services and quality improvement.", "The 2016 final rule set an 85% MLR standard: states must set capitation rates so each plan can reasonably achieve an MLR of at least 85% — at least 85 cents of each premium dollar going to claims, quality improvement, and fraud prevention.",
  'quiz explanation: mandatory 85% MLR floor', 'FABRICATED', '42 CFR 438.4(b)(9), 438.8', q='b2522dab-d5c3-43b8-a788-0c21fb96d74c')
R438 = '42 CFR 438.3(a) (Cornell LII, search-confirmed): proposed final contracts must be submitted to CMS no later than 90 days before the effective date when approval is sought by that date; CMS approval is a precondition for FFP'
p('rfp-process-mco-selection', "The process must comply with federal procurement standards at 42 CFR §438.3 and state procurement law. CMS must review and approve contracts before they take effect.", "The process must follow state procurement law, and the resulting contract must meet the federal contract requirements at 42 CFR §438.3. CMS must review and approve the contract — a precondition for federal matching of capitation payments.",
  '42 CFR 438.3 described as federal procurement standards', 'FABRICATED', R438)
p('rfp-process-mco-selection', "5. **CMS Review**: State submits executed contract; CMS has 90 days to review", "5. **CMS Review**: State submits the proposed final contract to CMS — no later than 90 days before the effective date if approval is needed by then (42 CFR §438.3(a))",
  'CMS has 90 days to review contracts', 'FABRICATED', R438)
p('rfp-process-mco-selection', "42 CFR §438.3 requires states to submit all Medicaid managed care contracts to CMS for review. CMS has 90 days to review and must approve the contract before it takes effect.", "42 CFR §438.3 requires states to submit all Medicaid managed care contracts to CMS for review and approval. States seeking approval by a specific effective date must submit the proposed final contract at least 90 days in advance, and CMS approval is a precondition for federal matching funds.",
  'quiz explanation: CMS has 90 days to review', 'FABRICATED', R438, q='6282303b-a2e4-43c3-bc53-833dd8960f68')
NY = 'New York State DOH report on MCO services/procurement (search-indexed text): the largest number of states (17) contract with 3-5 MCOs; ND 1, CA 26; 6 of 41 MCO states do not use procurement'
p('rfp-process-mco-selection', "Most state Medicaid markets contract with how many MCOs?", "What is the most common number of MCOs a state Medicaid program contracts with?", 'quiz: "Most state Medicaid markets contract with 3-5 MCOs"', 'UNVERIFIABLE', NY, q='470c9d33-2f1e-4e8a-a02d-439a024ce35b')
p('rfp-process-mco-selection', "Most states contract with 3 to 5 MCOs. This range maintains competitive pressure on plans while ensuring each has enough enrollment to operate viably and invest in care management.", "The largest group of states — 17 of the 41 with Medicaid managed care in a New York State Department of Health review — contract with 3 to 5 MCOs, balancing competition with enough enrollment per plan; the range runs from one (North Dakota) to 26 (California).",
  'quiz explanation: most states contract with 3-5 MCOs', 'UNVERIFIABLE', NY, q='470c9d33-2f1e-4e8a-a02d-439a024ce35b')
p('contract-requirements', "Incomplete encounter data was a major finding in OIG audits of multiple state Medicaid programs in 2019–2022.", "A 2021 HHS-OIG evaluation (OEI-02-19-00180) found that most states did not report complete and accurate managed care payment data in their T-MSIS encounter records.",
  'OIG audits of multiple states 2019-2022 found incomplete encounter data', 'UNVERIFIABLE', 'HHS-OIG OEI-02-19-00180 (2021), "Data on Medicaid Managed Care Payments to Providers Are Incomplete and Inaccurate"')
p('contract-requirements', "required under 42 CFR §438.240", "required under 42 CFR §438.330 (formerly §438.240)", 'QAP required under 42 CFR 438.240 (pre-2016 citation)', 'FABRICATED', 'eCFR: QAPI is 42 CFR 438.330 since the 2016 rule')
p('contract-requirements', "Federal network adequacy standards (strengthened in the 2024 Access rule) require routine primary care appointments to be available within 10 business days of a request.", "The 2024 Managed Care Access, Finance, and Quality rule requires routine primary care (and OB/GYN) appointments within 15 business days of a request; routine outpatient mental health and substance use disorder appointments must be available within 10 business days.",
  'quiz explanation: routine primary care within 10 business days', 'FABRICATED', 'eCFR 42 CFR 438.68(e)(1) (fetched): MH/SUD 10 business days; primary care 15; OB/GYN 15', q='39844eef-8ac0-4d29-98e9-d9e42994da39')
p('monitoring-oversight-eqro', "Under 42 CFR §438.358, EQROs must conduct three mandatory annual activities:", "Under 42 CFR §438.358, four EQR-related activities are mandatory for each plan:", 'three mandatory EQR activities', 'FABRICATED', 'eCFR 42 CFR 438.358(b)(1) (fetched)')
p('monitoring-oversight-eqro', "3. **Validation of Network Adequacy**: Reviewing whether the MCO's network meets state and federal standards", "3. **Validation of Network Adequacy**: Reviewing whether the MCO's network meets state and federal standards\n4. **Compliance Review**: A review, conducted within the previous three years, of the MCO's compliance with federal standards for access, enrollee rights, and quality",
  'compliance review omitted from mandatory activities', 'FABRICATED', 'eCFR 42 CFR 438.358(b)(1)(iii)')
p('monitoring-oversight-eqro', "Optional EQRO activities include: consumer surveys (CAHPS Medicaid), focused studies on specific quality issues, and assessment of new MCO systems.", "Optional EQRO activities include: encounter data validation, administering or validating consumer surveys (such as CAHPS), and focused studies on specific quality issues.",
  'optional activity "assessment of new MCO systems"', 'FABRICATED', 'eCFR 42 CFR 438.358(c) optional activities list (fetched)')
p('monitoring-oversight-eqro', "including civil monetary penalties, suspension of enrollment, and contract termination", "including civil money penalties, temporary management, suspension of new enrollment, and suspension of payment for new enrollees",
  'intermediate sanctions under 438.702 include contract termination', 'FABRICATED', '42 CFR 438.702(a) types of intermediate sanctions; termination is separate (438.708)')
p('monitoring-oversight-eqro', "Validating PIPs is one of three mandatory EQRO activities under 42 CFR §438.358.", "Validating PIPs is one of four mandatory EQR-related activities under 42 CFR §438.358.", 'quiz explanation: three mandatory activities', 'FABRICATED', 'eCFR 42 CFR 438.358(b)(1)', q='5a67982f-7fe1-4ebb-b016-d2463d0049a0')
ACT = '42 CFR 438.2 (actuary = meets American Academy of Actuaries qualification standards and follows Actuarial Standards Board practice standards); 438.4-438.5; CMS annual Medicaid Managed Care Rate Development Guide'
p('capitation-rate-setting', "Rates must be developed by a qualified actuary (ASA or FSA with relevant Medicaid experience)", "Rates must be developed and certified by a qualified actuary (one who meets the American Academy of Actuaries' qualification standards, per 42 CFR §438.2)",
  'qualified actuary = ASA or FSA', 'FABRICATED', ACT)
p('capitation-rate-setting', "(2) rates must reflect the specific MCO's operating environment — not just market averages.", "(2) rates must be developed in accordance with generally accepted actuarial principles and practices and the federal rate development standards in §438.5.",
  'actuarial soundness component (2): reflect the specific MCO operating environment', 'FABRICATED', ACT)
KFFPE = 'KFF Medicaid spending per full-benefit enrollee: children $3,321, individuals with disabilities $20,950 (verified in phase-7b ledger, KFF per-enrollee brief)'
p('capitation-rate-setting', "A child rate cell might be $180 PMPM while an aged/blind/disabled rate cell exceeds $1,200 PMPM, reflecting", "For scale, KFF puts Medicaid spending at about $3,321 a year per child enrollee (roughly $280 a month) versus about $20,950 per enrollee with disabilities (roughly $1,750 a month), reflecting",
  'child rate cell $180 PMPM vs ABD $1,200+ PMPM', 'UNVERIFIABLE', KFFPE)
p('capitation-rate-setting', "The CMS Actuarial Communication and Guidance document (released annually)", "CMS's annual Medicaid Managed Care Rate Development Guide", '"CMS Actuarial Communication and Guidance document"', 'FABRICATED', ACT)
p('capitation-rate-setting', "A qualified actuary (ASA or FSA)", "A qualified actuary (meeting American Academy of Actuaries qualification standards)", 'quiz option: qualified actuary (ASA or FSA)', 'FABRICATED', ACT, o='84dceb4d-b376-49a8-994b-eedc5089ff2c')
p('capitation-rate-setting', "42 CFR §438.4 requires that Medicaid capitation rates be certified as actuarially sound by a qualified actuary — typically an Associate or Fellow of the Society of Actuaries (ASA/FSA) with Medicaid experience.", "42 CFR §438.4 requires capitation rates to be certified as actuarially sound by an actuary who meets the American Academy of Actuaries' qualification standards and follows Actuarial Standards Board practice standards (42 CFR §438.2).",
  'quiz explanation: ASA/FSA', 'FABRICATED', ACT, q='7914e220-d666-4ee0-98f6-c76e45994855')
p('capitation-rate-setting', " Typical Medicaid medical trend factors range from 3–5% annually.", "", 'typical Medicaid trend 3-5% annually', 'UNVERIFIABLE', 'No source found for a typical 3-5% Medicaid trend range', q='8febc4ec-09e4-4b60-8721-b8b8135b8742')
CDPS = 'PMC10871574 (Medical Care 2024): 33 of 38 risk-adjusting Medicaid programs use CDPS'
p('risk-adjustment-medicaid', "CMS's HHS-HCC model (used in ACA marketplaces) and CMS's Medicare HCC model are commonly adapted for Medicaid.", "Medicare Advantage (CMS-HCC) and the ACA marketplaces (HHS-HCC) use HCC models, but most Medicaid programs use a Medicaid-specific diagnosis-based model instead — 33 of the 38 programs that risk-adjust MCO payments use the Chronic Illness and Disability Payment System (CDPS).",
  'HHS-HCC and Medicare HCC models commonly adapted for Medicaid', 'FABRICATED', CDPS)
p('risk-adjustment-medicaid', "the basis for most modern risk adjustment models", "the basis of Medicare Advantage and ACA marketplace risk adjustment (most Medicaid programs use the similar diagnosis-based CDPS model)", 'HCC = basis for most risk adjustment models (Medicaid context)', 'FABRICATED', CDPS)
MLR = '42 CFR 438.4(b)(9), 438.8 (numerator incl. fraud prevention; denominator net of taxes/fees; no QI cap; remittance is a state option 438.8(j)); Georgetown CCF March 2024 (fetched): states decide whether to set a minimum and whether to collect remittances'
p('mlr-requirements', "The 2016 Medicaid managed care final rule established a Medical Loss Ratio (MLR) floor of 85% for Medicaid MCOs, PIHPs, and PAHPs. This means MCOs must spend at least 85 cents of every capitation dollar on clinical services and quality improvement activities — limiting administrative costs and profit to 15%.", "The 2016 Medicaid managed care final rule set an 85% medical loss ratio (MLR) standard for MCOs, PIHPs, and PAHPs: states must set capitation rates so each plan can reasonably achieve an MLR of at least 85%, and any minimum MLR a state imposes must be at least 85%.",
  'mandatory 85% MLR floor limiting admin/profit to 15%', 'FABRICATED', MLR)
p('mlr-requirements', "MLR = (Incurred Claims + Quality Improvement Expenses) / Premium Revenue", "MLR = (Incurred Claims + Quality Improvement Expenditures + Fraud Prevention Activities) / (Premium Revenue − Taxes and Licensing/Regulatory Fees)", 'MLR formula omits fraud prevention and tax/fee adjustment', 'FABRICATED', MLR)
p('mlr-requirements', "If an MCO's MLR falls below 85%, it must remit the difference to the state. States can also require higher MLR thresholds in their contracts — some states require 88% or 90%.", "If a state requires remittance, a plan whose MLR falls below the state's minimum must pay back the difference. States can also set minimums above 85% in their contracts.",
  'MCO must remit below 85%; some states require 88% or 90%', 'FABRICATED', MLR)
p('mlr-requirements', "YES (capped at 3%)", "YES", 'quality improvement counts toward MLR "capped at 3%"', 'FABRICATED', MLR)
p('mlr-requirements', "If an MCO's annual MLR falls below the 85% threshold, the plan must remit the shortfall to the state Medicaid agency.", "If a state requires remittance and an MCO's annual MLR falls below the 85% threshold, the plan must remit the shortfall to the state Medicaid agency.", 'remittance mandatory', 'FABRICATED', MLR)
p('mlr-requirements', "Quality improvement expenses, including disease management programs, count toward the MLR numerator (capped at 3% of premium).", "Quality improvement expenses, including disease management programs, count toward the MLR numerator.", 'quiz explanation: QI capped at 3%', 'FABRICATED', MLR, q='5db988dc-b90f-4330-930a-881d90ecc3d7')
p('mlr-requirements', "The MCO's MLR of 84.5% is 0.5 percentage points below the 85% floor. The remittance owed = 0.5% × $400M = $2 million.", "If the state requires remittance at an 85% minimum, the MCO's MLR of 84.5% is 0.5 percentage points short, so it owes 0.5% × $400M = $2 million.", 'quiz explanation: remittance automatic', 'FABRICATED', MLR, q='c7608e7e-9c3d-40ea-a4f3-b3171d5d99f3')
p('covered-benefits-carveins-carveouts', "states like Arizona, Pennsylvania, and New York have integrated behavioral health", "states like Arizona, Washington, and New York have integrated behavioral health",
  'Pennsylvania listed as having integrated BH into MCO contracts (it carves BH out to county BH-MCOs under HealthChoices)', 'FABRICATED', 'Pennsylvania HealthChoices behavioral health program (separate BH-MCOs); Washington Integrated Managed Care statewide by Jan 2020; Arizona AHCCCS Complete Care (2018); NY HARPs')
p('covered-benefits-carveins-carveouts', "Increasingly (CMS encourages)", "Most MCO states", 'pharmacy carve-in "CMS encourages"', 'UNVERIFIABLE', 'No CMS guidance encouraging pharmacy carve-in found; KFF: most MCO states carve pharmacy in (35 in / 4 out, July 2019)')
p('covered-benefits-carveins-carveouts', "Strong carve-in trend", "Mixed — a few states (e.g., CA, NY) carved it out", 'pharmacy "strong carve-in trend"', 'FABRICATED', 'California (2022) and New York (2023) carved pharmacy out of MCO contracts (KFF budget survey)')
p('covered-benefits-carveins-carveouts', "Pharmacy (increasingly being carved back in)", "Pharmacy (carved out in a few states, such as California and New York)", 'pharmacy increasingly carved back in', 'FABRICATED', 'same')
NA = 'eCFR 42 CFR 438.68(b)(1) and (e)(1) (fetched): quantitative standard other than wait times for listed provider types incl. MH/SUD adult & pediatric; wait times MH/SUD 10, primary care 15, OB/GYN 15 business days plus one state-selected type; FR API: managed care rule = 89 FR 41002 (2024-08085); 89 FR 40542 is the separate Ensuring Access to Medicaid Services rule'
p('network-adequacy-standards', "42 CFR §438.68 requires states to establish network adequacy standards for Medicaid MCOs covering: time and distance to providers; appointment wait times; provider-to-enrollee ratios; and availability of providers who are not accepting new patients.", "42 CFR §438.68 requires states to set a quantitative network adequacy standard (such as time-and-distance or provider-to-enrollee ratios) for specified provider types and, since the 2024 rule, appointment wait time standards.",
  '438.68 requires standards covering time/distance, wait times, ratios, and providers not accepting new patients', 'FABRICATED', NA)
p('network-adequacy-standards', "behavioral health (outpatient and inpatient)", "mental health and substance use disorder (adult and pediatric)", '438.68 provider type "behavioral health (outpatient and inpatient)"', 'FABRICATED', NA)
p('network-adequacy-standards', "The 2024 Medicaid Access rule (89 FR 40542)", "The 2024 Managed Care Access, Finance, and Quality rule (89 FR 41002)", 'wrong rule/citation for managed care wait times', 'FABRICATED', NA)
p('network-adequacy-standards', "Under the 2024 Access rule, urgent care (non-emergency) must be available within:", "Under the 2024 Medicaid managed care rule, routine outpatient mental health and substance use disorder appointments must be available within:",
  'quiz: 48-hour urgent care standard', 'FABRICATED', NA, q='79a4b699-c29e-4c06-862a-10bab172294c')
p('network-adequacy-standards', "The 2024 Medicaid Access rule requires MCOs to provide access to urgent (non-emergency) care within 48 hours of a request.", "The 2024 Managed Care Access, Finance, and Quality rule sets a 10-business-day standard for routine outpatient mental health and substance use disorder appointments (15 business days for primary care and OB/GYN). It does not set a federal 48-hour urgent care standard.",
  'quiz explanation: urgent care within 48 hours', 'FABRICATED', NA, q='79a4b699-c29e-4c06-862a-10bab172294c')
CR = 'eCFR 42 CFR 438.214 (fetched 2026-10-09): state sets a uniform credentialing/recredentialing policy; MCO follows a documented process; no 3-year interval, PSV, or delegation language; 438.230 governs subcontracting/delegation; NCQA credentialing standards require recredentialing at least every 36 months and PSV'
p('provider-credentialing-mco', "Under 42 CFR §438.214, MCOs must: verify that providers meet state licensing and certification requirements; have procedures to exclude providers excluded from federal programs; and recredential providers at least every three years.", "Under 42 CFR §438.214, each state must set a uniform credentialing and recredentialing policy that its MCOs follow, and MCOs may not employ or contract with providers excluded from federal health care programs. Most plans also follow NCQA credentialing standards, which require recredentialing at least every three years.",
  '438.214 requires recredentialing every three years', 'FABRICATED', CR)
p('provider-credentialing-mco', "This is permitted under 42 CFR §438.214 if the MCO maintains oversight and can audit the delegate's credentialing files.", "This is permitted under NCQA standards and 42 CFR §438.230 (subcontracting and delegation), which keeps the MCO fully responsible, if the MCO maintains oversight and can audit the delegate's credentialing files.",
  'delegation permitted under 438.214', 'FABRICATED', CR)
p('provider-credentialing-mco', "(medical board, DEA, NPDB) — required under 42 CFR §438.214", "(medical board, DEA, NPDB) — required under NCQA credentialing standards", 'PSV required under 438.214', 'FABRICATED', CR)
p('provider-credentialing-mco', "42 CFR §438.214 requires MCOs to recredential all network providers at least every three years", "NCQA credentialing standards (which most MCOs follow) require recredentialing all network providers at least every three years", 'stat: 438.214 requires 3-year recredentialing', 'FABRICATED', CR)
p('provider-credentialing-mco', "Under 42 CFR §438.214, how often must MCOs recredential network providers?", "Under NCQA credentialing standards, how often must health plans recredential network providers?", 'quiz: 438.214 recredentialing interval', 'FABRICATED', CR, q='858bf5b0-f0c6-41e1-9336-bc4ef94303b1')
p('provider-credentialing-mco', "42 CFR §438.214 requires MCOs to recredential all network providers at minimum every three years, ensuring that credentials remain current and adverse actions are identified.", "NCQA credentialing standards require health plans to recredential network providers at least every three years; 42 CFR §438.214 requires each state to set a uniform credentialing and recredentialing policy that its MCOs follow.",
  'quiz explanation: 438.214 three years', 'FABRICATED', CR, q='858bf5b0-f0c6-41e1-9336-bc4ef94303b1')
HE = 'NCQA HEDIS MY2022+ (CDC retired; HBD/EED/KED; AMR; CBP); C-section and developmental screening are CMS Core Set measures (PC-02, DEV-CH), not HEDIS; CMS MyCare Ohio quality withhold reports: 1% (yr1), 2% (yr2), 3% (yr3), tiered repayment by share of measures met'
p('hedis-medicaid-reporting', "- **Chronic Disease Management**: Comprehensive diabetes care (HbA1c, eye exams, nephropathy screening), asthma management, blood pressure control", "- **Chronic Disease Management**: Diabetes care (glycemic status, eye exams, kidney health evaluation), asthma medication ratio, controlling high blood pressure", 'Comprehensive Diabetes Care measure (retired)', 'FABRICATED', HE)
p('hedis-medicaid-reporting', "- **Maternal Health**: Prenatal and postpartum care (PPC), C-section rates", "- **Maternal Health**: Prenatal and postpartum care (PPC)", 'C-section rates listed as HEDIS', 'FABRICATED', HE)
p('hedis-medicaid-reporting', "- **Children**: EPSDT screens, developmental screening, lead screening", "- **Children**: Well-child visits, childhood immunization status, lead screening in children (developmental screening is reported through the CMS Child Core Set rather than HEDIS)", 'EPSDT screens / developmental screening listed as HEDIS', 'FABRICATED', HE)
p('hedis-medicaid-reporting', "For example, Tennessee's CoverKids (CHIP) and Ohio Medicaid both use quality withholds where 1–2% of capitation is held back and returned only if MCOs meet HEDIS benchmarks.", "For example, the MyCare Ohio demonstration for dually eligible enrollees withheld 1% of capitation in its first year, rising to 3% by year three, and repaid it on a sliding scale according to how many quality measures (including HEDIS and CAHPS) each plan met.",
  'Tennessee CoverKids and Ohio Medicaid withhold 1-2%', 'UNVERIFIABLE', HE)
p('hedis-medicaid-reporting', "States like Tennessee (CoverKids) and Ohio Medicaid use quality withholds to:", "Quality withholds, like the one used in the MyCare Ohio demonstration, are designed to:", 'quiz: Tennessee CoverKids / Ohio 1-2% withholds', 'UNVERIFIABLE', HE, q='7a1e23be-fad6-4695-9c3a-a312cec878b5')
p('hedis-medicaid-reporting', "Hold back 1–2% of capitation and return it only if MCOs meet HEDIS benchmarks", "Hold back a share of capitation and return it based on quality-measure performance", 'quiz option: 1-2% withhold', 'UNVERIFIABLE', HE, o='96369cb2-0a6b-44de-a764-7c76a11c18a8')
p('hedis-medicaid-reporting', "Quality withholds retain 1–2% of capitation payments and return those funds to MCOs that achieve defined HEDIS performance benchmarks, creating financial incentives for quality improvement.", "Quality withholds retain a share of capitation (MyCare Ohio: 1% rising to 3%) and return it to plans according to their performance on quality measures such as HEDIS and CAHPS, creating a financial incentive for quality improvement.",
  'quiz explanation: 1-2% withhold', 'UNVERIFIABLE', HE, q='7a1e23be-fad6-4695-9c3a-a312cec878b5')
p('ltss-mltss-care-coordination', "As of 2023, over 20 states operate MLTSS programs covering approximately 1.5 million beneficiaries.", "As of 2023, about two dozen states operated MLTSS programs, and CMS counted about 1.9 million MLTSS users nationwide as of July 2024.",
  'MLTSS covers ~1.5 million beneficiaries', 'FABRICATED', 'CMS 2024 Medicaid Managed Care Enrollment report (fetched PDF): ~1.9M MLTSS users July 1 2024 (1.8M in 2023); 24 states with MLTSS as of Dec 2023 (search-confirmed)')
VB = 'HCP-LAN APM Framework categories 1-4 (2A-2C, 3A/3B, 4A-4C); no "CMS Medicaid VBP framework" with tiers and no CMS targets for state Medicaid VBP shares; MACPAC 2020 VBP report (fetched): NY required MCOs at 80% VBP by March 2020; CMMI Accountable Health Communities tested screening/navigation, not Medicaid VBP'
p('value-based-purchasing-medicaid', "CMS encourages VBP through its Medicaid VBP framework and has set targets for states to move specified percentages of Medicaid payments into VBP arrangements.", "Many states use the Health Care Payment Learning & Action Network (HCP-LAN) framework to classify these arrangements.", '"CMS Medicaid VBP framework" with CMS targets for states', 'FABRICATED', VB)
p('value-based-purchasing-medicaid', "including the Integrated Care for Kids (InCK) model and the Accountable Health Communities model.", "including the Integrated Care for Kids (InCK) model, which supports state Medicaid alternative payment models for children's services.", 'Accountable Health Communities model tested Medicaid VBP', 'FABRICATED', VB)
p('value-based-purchasing-medicaid', "In the CMS Medicaid VBP framework, Tier 1 arrangements are characterized by:", "In the HCP-LAN payment framework, Category 2 arrangements are characterized by:", 'quiz: CMS Medicaid VBP framework Tier 1', 'FABRICATED', VB, q='c56ee4ae-4f54-49a2-b8ae-6de045e9c38a')
p('value-based-purchasing-medicaid', "Tier 1 VBP arrangements add quality bonuses or penalties on top of the existing FFS payment structure, with minimal risk transfer.", "HCP-LAN Category 2 arrangements add quality bonuses or penalties on top of the existing fee-for-service payment structure, with minimal risk transfer.", 'quiz explanation: Tier 1', 'FABRICATED', VB, q='c56ee4ae-4f54-49a2-b8ae-6de045e9c38a')
p('value-based-purchasing-medicaid', "Global capitation to a provider organization represents which tier of the VBP framework?", "Global capitation to a provider organization falls in which HCP-LAN category?", 'quiz: tier of the VBP framework', 'FABRICATED', VB, q='ae76f557-9226-40e6-be89-e30f4e9138ce')
p('value-based-purchasing-medicaid', "Tier 4 represents the highest level of provider risk:", "HCP-LAN Category 4 (population-based payment) represents the highest level of provider risk:", 'quiz explanation: Tier 4', 'FABRICATED', VB, q='ae76f557-9226-40e6-be89-e30f4e9138ce')
p('section-1115-waivers', "premium requirements for able-bodied adults; drug testing for enrollment; and time-limited enrollment", "premium requirements for able-bodied adults; and time-limited enrollment", '1115 waivers used to test drug testing for enrollment (never approved)', 'FABRICATED', 'No CMS approval of Medicaid drug-testing conditions found (Wisconsin requested; not approved)')
p('section-1115-waivers', "(struck down by courts in Arkansas, Kentucky; recently re-approved for Georgia)", "(struck down by courts in Arkansas and Kentucky; Georgia's Pathways program runs under a 2020 approval reinstated by a federal court in 2022; Congress wrote community engagement requirements into federal law in July 2025)",
  'Georgia "recently re-approved"; omits 2025 statute', 'FABRICATED', 'Georgia v. Becerra (S.D. Ga. Aug 2022) vacated CMS rescission; Pathways launched July 2023; P.L. 119-21 July 4 2025')
p('section-1115-waivers', "Statewide managed care with closed enrollment", "Statewide mandatory managed care since 1994", 'TennCare "statewide managed care with closed enrollment"', 'FABRICATED', 'TennCare launched Jan 1994 under 1115; enrollment closures were temporary (e.g., 2005 disenrollment), not a defining feature')
spec = dict(pairs=P, supa=[dict(table='lessons', col='content_blocks', ids=list(L.values())),
    dict(table='quiz_questions', col='question', ids=sorted(QQ)), dict(table='quiz_questions', col='explanation', ids=sorted(QQ)),
    dict(table='quiz_options', col='text', ids=sorted(QO))],
    files=['frontend/content/course_medicaid_managed_care.json', 'frontend/content/courses_tier3.json'])
json.dump(spec, open(os.path.join(os.path.dirname(__file__), 'mmc_fallbacks.json'), 'w'), indent=1, ensure_ascii=False)
print(len(P), 'pairs', len(QQ), 'questions', len(QO), 'options')
